"use strict";
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.defineExtension = exports.NullsOrder = exports.JsonNullValueFilter = exports.QueryMode = exports.JsonNullValueInput = exports.NullableJsonNullValueInput = exports.SortOrder = exports.PromoCodeScalarFieldEnum = exports.ReviewScalarFieldEnum = exports.EmailLogScalarFieldEnum = exports.AuditLogScalarFieldEnum = exports.SeatLockScalarFieldEnum = exports.CheckinScalarFieldEnum = exports.PassengerScalarFieldEnum = exports.ManifestScalarFieldEnum = exports.WebhookEventScalarFieldEnum = exports.PaymentScalarFieldEnum = exports.BookingItemScalarFieldEnum = exports.BookingScalarFieldEnum = exports.TripSeatScalarFieldEnum = exports.PriceTierScalarFieldEnum = exports.TripScheduleScalarFieldEnum = exports.TripScalarFieldEnum = exports.VesselScalarFieldEnum = exports.OperatorScalarFieldEnum = exports.UserScalarFieldEnum = exports.TransactionIsolationLevel = exports.ModelName = exports.AnyNull = exports.JsonNull = exports.DbNull = exports.NullTypes = exports.prismaVersion = exports.getExtensionContext = exports.Decimal = exports.Sql = exports.raw = exports.join = exports.empty = exports.sql = exports.PrismaClientValidationError = exports.PrismaClientInitializationError = exports.PrismaClientRustPanicError = exports.PrismaClientUnknownRequestError = exports.PrismaClientKnownRequestError = void 0;
var runtime = require("@prisma/client/runtime/client");
/**
 * Prisma Errors
 */
exports.PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError;
exports.PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError;
exports.PrismaClientRustPanicError = runtime.PrismaClientRustPanicError;
exports.PrismaClientInitializationError = runtime.PrismaClientInitializationError;
exports.PrismaClientValidationError = runtime.PrismaClientValidationError;
/**
 * Re-export of sql-template-tag
 */
exports.sql = runtime.sqltag;
exports.empty = runtime.empty;
exports.join = runtime.join;
exports.raw = runtime.raw;
exports.Sql = runtime.Sql;
/**
 * Decimal.js
 */
exports.Decimal = runtime.Decimal;
exports.getExtensionContext = runtime.Extensions.getExtensionContext;
/**
 * Prisma Client JS version: 7.4.0
 * Query Engine version: ab56fe763f921d033a6c195e7ddeb3e255bdbb57
 */
exports.prismaVersion = {
    client: "7.4.0",
    engine: "ab56fe763f921d033a6c195e7ddeb3e255bdbb57"
};
exports.NullTypes = {
    DbNull: runtime.NullTypes.DbNull,
    JsonNull: runtime.NullTypes.JsonNull,
    AnyNull: runtime.NullTypes.AnyNull,
};
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
exports.DbNull = runtime.DbNull;
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
exports.JsonNull = runtime.JsonNull;
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
exports.AnyNull = runtime.AnyNull;
exports.ModelName = {
    User: 'User',
    Operator: 'Operator',
    Vessel: 'Vessel',
    Trip: 'Trip',
    TripSchedule: 'TripSchedule',
    PriceTier: 'PriceTier',
    TripSeat: 'TripSeat',
    Booking: 'Booking',
    BookingItem: 'BookingItem',
    Payment: 'Payment',
    WebhookEvent: 'WebhookEvent',
    Manifest: 'Manifest',
    Passenger: 'Passenger',
    Checkin: 'Checkin',
    SeatLock: 'SeatLock',
    AuditLog: 'AuditLog',
    EmailLog: 'EmailLog',
    Review: 'Review',
    PromoCode: 'PromoCode'
};
/**
 * Enums
 */
exports.TransactionIsolationLevel = runtime.makeStrictEnum({
    ReadUncommitted: 'ReadUncommitted',
    ReadCommitted: 'ReadCommitted',
    RepeatableRead: 'RepeatableRead',
    Serializable: 'Serializable'
});
exports.UserScalarFieldEnum = {
    id: 'id',
    email: 'email',
    phone: 'phone',
    fullName: 'fullName',
    role: 'role',
    profilePictureUrl: 'profilePictureUrl',
    isActive: 'isActive',
    metadata: 'metadata',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt',
    deletedAt: 'deletedAt'
};
exports.OperatorScalarFieldEnum = {
    id: 'id',
    userId: 'userId',
    organizationName: 'organizationName',
    companyName: 'companyName',
    contactEmail: 'contactEmail',
    contactPhone: 'contactPhone',
    verified: 'verified',
    rating: 'rating',
    metadata: 'metadata',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt',
    deletedAt: 'deletedAt'
};
exports.VesselScalarFieldEnum = {
    id: 'id',
    operatorId: 'operatorId',
    name: 'name',
    registrationNo: 'registrationNo',
    capacity: 'capacity',
    description: 'description',
    vesselMetadata: 'vesselMetadata',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt',
    deletedAt: 'deletedAt'
};
exports.TripScalarFieldEnum = {
    id: 'id',
    vesselId: 'vesselId',
    operatorId: 'operatorId',
    title: 'title',
    description: 'description',
    category: 'category',
    externalReference: 'externalReference',
    durationMinutes: 'durationMinutes',
    isRecurring: 'isRecurring',
    amenities: 'amenities',
    highlights: 'highlights',
    isActive: 'isActive',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt',
    deletedAt: 'deletedAt'
};
exports.TripScheduleScalarFieldEnum = {
    id: 'id',
    tripId: 'tripId',
    startTime: 'startTime',
    endTime: 'endTime',
    capacity: 'capacity',
    bookedSeats: 'bookedSeats',
    status: 'status',
    departurePort: 'departurePort',
    arrivalPort: 'arrivalPort',
    baseCurrency: 'baseCurrency',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
};
exports.PriceTierScalarFieldEnum = {
    id: 'id',
    tripScheduleId: 'tripScheduleId',
    name: 'name',
    description: 'description',
    amountKobo: 'amountKobo',
    priceKobo: 'priceKobo',
    capacity: 'capacity',
    position: 'position',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
};
exports.TripSeatScalarFieldEnum = {
    id: 'id',
    tripScheduleId: 'tripScheduleId',
    seatLabel: 'seatLabel',
    tierId: 'tierId',
    isActive: 'isActive',
    createdAt: 'createdAt'
};
exports.BookingScalarFieldEnum = {
    id: 'id',
    userId: 'userId',
    tripScheduleId: 'tripScheduleId',
    operatorId: 'operatorId',
    priceTierId: 'priceTierId',
    status: 'status',
    paymentStatus: 'paymentStatus',
    bookingReference: 'bookingReference',
    numberOfPassengers: 'numberOfPassengers',
    totalAmountKobo: 'totalAmountKobo',
    currency: 'currency',
    holdExpiresAt: 'holdExpiresAt',
    promoCode: 'promoCode',
    discountKobo: 'discountKobo',
    qrCode: 'qrCode',
    confirmedAt: 'confirmedAt',
    failureReason: 'failureReason',
    metadata: 'metadata',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt',
    cancelledAt: 'cancelledAt'
};
exports.BookingItemScalarFieldEnum = {
    id: 'id',
    bookingId: 'bookingId',
    priceTierId: 'priceTierId',
    tripSeatId: 'tripSeatId',
    passengerName: 'passengerName',
    passengerPhone: 'passengerPhone',
    ticketReference: 'ticketReference',
    status: 'status',
    createdAt: 'createdAt'
};
exports.PaymentScalarFieldEnum = {
    id: 'id',
    bookingId: 'bookingId',
    provider: 'provider',
    providerPaymentId: 'providerPaymentId',
    status: 'status',
    amountKobo: 'amountKobo',
    currency: 'currency',
    rawResponse: 'rawResponse',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
};
exports.WebhookEventScalarFieldEnum = {
    id: 'id',
    provider: 'provider',
    eventType: 'eventType',
    providerEventId: 'providerEventId',
    payload: 'payload',
    signature: 'signature',
    receivedAt: 'receivedAt',
    processed: 'processed',
    processedAt: 'processedAt',
    processingError: 'processingError'
};
exports.ManifestScalarFieldEnum = {
    id: 'id',
    tripScheduleId: 'tripScheduleId',
    generatedById: 'generatedById',
    generatedAt: 'generatedAt',
    payload: 'payload'
};
exports.PassengerScalarFieldEnum = {
    id: 'id',
    bookingId: 'bookingId',
    priceTierId: 'priceTierId',
    fullName: 'fullName',
    phone: 'phone',
    email: 'email',
    emergencyContact: 'emergencyContact',
    specialNeeds: 'specialNeeds',
    metadata: 'metadata',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
};
exports.CheckinScalarFieldEnum = {
    id: 'id',
    bookingItemId: 'bookingItemId',
    bookingId: 'bookingId',
    passengerId: 'passengerId',
    checkedInById: 'checkedInById',
    checkedInAt: 'checkedInAt',
    method: 'method'
};
exports.SeatLockScalarFieldEnum = {
    id: 'id',
    tripScheduleId: 'tripScheduleId',
    tripSeatId: 'tripSeatId',
    bookingId: 'bookingId',
    lockedById: 'lockedById',
    lockedAt: 'lockedAt',
    expiresAt: 'expiresAt'
};
exports.AuditLogScalarFieldEnum = {
    id: 'id',
    entityType: 'entityType',
    entityId: 'entityId',
    action: 'action',
    userId: 'userId',
    changes: 'changes',
    metadata: 'metadata',
    createdAt: 'createdAt'
};
exports.EmailLogScalarFieldEnum = {
    id: 'id',
    userId: 'userId',
    recipient: 'recipient',
    channel: 'channel',
    type: 'type',
    subject: 'subject',
    body: 'body',
    metadata: 'metadata',
    provider: 'provider',
    providerMsgId: 'providerMsgId',
    status: 'status',
    errorMessage: 'errorMessage',
    sentAt: 'sentAt',
    createdAt: 'createdAt'
};
exports.ReviewScalarFieldEnum = {
    id: 'id',
    tripId: 'tripId',
    userId: 'userId',
    rating: 'rating',
    title: 'title',
    comment: 'comment',
    isVerified: 'isVerified',
    isPublic: 'isPublic',
    adminResponse: 'adminResponse',
    respondedAt: 'respondedAt',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
};
exports.PromoCodeScalarFieldEnum = {
    id: 'id',
    code: 'code',
    description: 'description',
    discountType: 'discountType',
    discountValue: 'discountValue',
    priceTierId: 'priceTierId',
    minPurchase: 'minPurchase',
    maxDiscount: 'maxDiscount',
    usageLimit: 'usageLimit',
    usageCount: 'usageCount',
    perUserLimit: 'perUserLimit',
    validFrom: 'validFrom',
    validUntil: 'validUntil',
    isActive: 'isActive',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
};
exports.SortOrder = {
    asc: 'asc',
    desc: 'desc'
};
exports.NullableJsonNullValueInput = {
    DbNull: exports.DbNull,
    JsonNull: exports.JsonNull
};
exports.JsonNullValueInput = {
    JsonNull: exports.JsonNull
};
exports.QueryMode = {
    default: 'default',
    insensitive: 'insensitive'
};
exports.JsonNullValueFilter = {
    DbNull: exports.DbNull,
    JsonNull: exports.JsonNull,
    AnyNull: exports.AnyNull
};
exports.NullsOrder = {
    first: 'first',
    last: 'last'
};
exports.defineExtension = runtime.Extensions.defineExtension;
