
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Checkin` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Checkin
 * 
 */
export type CheckinModel = runtime.Types.Result.DefaultSelection<Prisma.$CheckinPayload>

export type AggregateCheckin = {
  _count: CheckinCountAggregateOutputType | null
  _min: CheckinMinAggregateOutputType | null
  _max: CheckinMaxAggregateOutputType | null
}

export type CheckinMinAggregateOutputType = {
  id: string | null
  bookingItemId: string | null
  bookingId: string | null
  passengerId: string | null
  checkedInById: string | null
  checkedInAt: Date | null
  method: string | null
}

export type CheckinMaxAggregateOutputType = {
  id: string | null
  bookingItemId: string | null
  bookingId: string | null
  passengerId: string | null
  checkedInById: string | null
  checkedInAt: Date | null
  method: string | null
}

export type CheckinCountAggregateOutputType = {
  id: number
  bookingItemId: number
  bookingId: number
  passengerId: number
  checkedInById: number
  checkedInAt: number
  method: number
  _all: number
}


export type CheckinMinAggregateInputType = {
  id?: true
  bookingItemId?: true
  bookingId?: true
  passengerId?: true
  checkedInById?: true
  checkedInAt?: true
  method?: true
}

export type CheckinMaxAggregateInputType = {
  id?: true
  bookingItemId?: true
  bookingId?: true
  passengerId?: true
  checkedInById?: true
  checkedInAt?: true
  method?: true
}

export type CheckinCountAggregateInputType = {
  id?: true
  bookingItemId?: true
  bookingId?: true
  passengerId?: true
  checkedInById?: true
  checkedInAt?: true
  method?: true
  _all?: true
}

export type CheckinAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Checkin to aggregate.
   */
  where?: Prisma.CheckinWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Checkins to fetch.
   */
  orderBy?: Prisma.CheckinOrderByWithRelationInput | Prisma.CheckinOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CheckinWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Checkins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Checkins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Checkins
  **/
  _count?: true | CheckinCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CheckinMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CheckinMaxAggregateInputType
}

export type GetCheckinAggregateType<T extends CheckinAggregateArgs> = {
      [P in keyof T & keyof AggregateCheckin]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCheckin[P]>
    : Prisma.GetScalarType<T[P], AggregateCheckin[P]>
}




export type CheckinGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CheckinWhereInput
  orderBy?: Prisma.CheckinOrderByWithAggregationInput | Prisma.CheckinOrderByWithAggregationInput[]
  by: Prisma.CheckinScalarFieldEnum[] | Prisma.CheckinScalarFieldEnum
  having?: Prisma.CheckinScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CheckinCountAggregateInputType | true
  _min?: CheckinMinAggregateInputType
  _max?: CheckinMaxAggregateInputType
}

export type CheckinGroupByOutputType = {
  id: string
  bookingItemId: string | null
  bookingId: string | null
  passengerId: string | null
  checkedInById: string | null
  checkedInAt: Date
  method: string
  _count: CheckinCountAggregateOutputType | null
  _min: CheckinMinAggregateOutputType | null
  _max: CheckinMaxAggregateOutputType | null
}

type GetCheckinGroupByPayload<T extends CheckinGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CheckinGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CheckinGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CheckinGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CheckinGroupByOutputType[P]>
      }
    >
  >



export type CheckinWhereInput = {
  AND?: Prisma.CheckinWhereInput | Prisma.CheckinWhereInput[]
  OR?: Prisma.CheckinWhereInput[]
  NOT?: Prisma.CheckinWhereInput | Prisma.CheckinWhereInput[]
  id?: Prisma.StringFilter<"Checkin"> | string
  bookingItemId?: Prisma.StringNullableFilter<"Checkin"> | string | null
  bookingId?: Prisma.StringNullableFilter<"Checkin"> | string | null
  passengerId?: Prisma.StringNullableFilter<"Checkin"> | string | null
  checkedInById?: Prisma.UuidNullableFilter<"Checkin"> | string | null
  checkedInAt?: Prisma.DateTimeFilter<"Checkin"> | Date | string
  method?: Prisma.StringFilter<"Checkin"> | string
  bookingItem?: Prisma.XOR<Prisma.BookingItemNullableScalarRelationFilter, Prisma.BookingItemWhereInput> | null
  booking?: Prisma.XOR<Prisma.BookingNullableScalarRelationFilter, Prisma.BookingWhereInput> | null
  passenger?: Prisma.XOR<Prisma.PassengerNullableScalarRelationFilter, Prisma.PassengerWhereInput> | null
  checkedInBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type CheckinOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  bookingItemId?: Prisma.SortOrderInput | Prisma.SortOrder
  bookingId?: Prisma.SortOrderInput | Prisma.SortOrder
  passengerId?: Prisma.SortOrderInput | Prisma.SortOrder
  checkedInById?: Prisma.SortOrderInput | Prisma.SortOrder
  checkedInAt?: Prisma.SortOrder
  method?: Prisma.SortOrder
  bookingItem?: Prisma.BookingItemOrderByWithRelationInput
  booking?: Prisma.BookingOrderByWithRelationInput
  passenger?: Prisma.PassengerOrderByWithRelationInput
  checkedInBy?: Prisma.UserOrderByWithRelationInput
}

export type CheckinWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  bookingItemId?: string
  passengerId?: string
  AND?: Prisma.CheckinWhereInput | Prisma.CheckinWhereInput[]
  OR?: Prisma.CheckinWhereInput[]
  NOT?: Prisma.CheckinWhereInput | Prisma.CheckinWhereInput[]
  bookingId?: Prisma.StringNullableFilter<"Checkin"> | string | null
  checkedInById?: Prisma.UuidNullableFilter<"Checkin"> | string | null
  checkedInAt?: Prisma.DateTimeFilter<"Checkin"> | Date | string
  method?: Prisma.StringFilter<"Checkin"> | string
  bookingItem?: Prisma.XOR<Prisma.BookingItemNullableScalarRelationFilter, Prisma.BookingItemWhereInput> | null
  booking?: Prisma.XOR<Prisma.BookingNullableScalarRelationFilter, Prisma.BookingWhereInput> | null
  passenger?: Prisma.XOR<Prisma.PassengerNullableScalarRelationFilter, Prisma.PassengerWhereInput> | null
  checkedInBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id" | "bookingItemId" | "passengerId">

export type CheckinOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  bookingItemId?: Prisma.SortOrderInput | Prisma.SortOrder
  bookingId?: Prisma.SortOrderInput | Prisma.SortOrder
  passengerId?: Prisma.SortOrderInput | Prisma.SortOrder
  checkedInById?: Prisma.SortOrderInput | Prisma.SortOrder
  checkedInAt?: Prisma.SortOrder
  method?: Prisma.SortOrder
  _count?: Prisma.CheckinCountOrderByAggregateInput
  _max?: Prisma.CheckinMaxOrderByAggregateInput
  _min?: Prisma.CheckinMinOrderByAggregateInput
}

export type CheckinScalarWhereWithAggregatesInput = {
  AND?: Prisma.CheckinScalarWhereWithAggregatesInput | Prisma.CheckinScalarWhereWithAggregatesInput[]
  OR?: Prisma.CheckinScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CheckinScalarWhereWithAggregatesInput | Prisma.CheckinScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Checkin"> | string
  bookingItemId?: Prisma.StringNullableWithAggregatesFilter<"Checkin"> | string | null
  bookingId?: Prisma.StringNullableWithAggregatesFilter<"Checkin"> | string | null
  passengerId?: Prisma.StringNullableWithAggregatesFilter<"Checkin"> | string | null
  checkedInById?: Prisma.UuidNullableWithAggregatesFilter<"Checkin"> | string | null
  checkedInAt?: Prisma.DateTimeWithAggregatesFilter<"Checkin"> | Date | string
  method?: Prisma.StringWithAggregatesFilter<"Checkin"> | string
}

export type CheckinCreateInput = {
  id?: string
  checkedInAt?: Date | string
  method?: string
  bookingItem?: Prisma.BookingItemCreateNestedOneWithoutCheckinInput
  booking?: Prisma.BookingCreateNestedOneWithoutCheckinRecordsInput
  passenger?: Prisma.PassengerCreateNestedOneWithoutCheckinInput
  checkedInBy?: Prisma.UserCreateNestedOneWithoutCheckinsInput
}

export type CheckinUncheckedCreateInput = {
  id?: string
  bookingItemId?: string | null
  bookingId?: string | null
  passengerId?: string | null
  checkedInById?: string | null
  checkedInAt?: Date | string
  method?: string
}

export type CheckinUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  checkedInAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  method?: Prisma.StringFieldUpdateOperationsInput | string
  bookingItem?: Prisma.BookingItemUpdateOneWithoutCheckinNestedInput
  booking?: Prisma.BookingUpdateOneWithoutCheckinRecordsNestedInput
  passenger?: Prisma.PassengerUpdateOneWithoutCheckinNestedInput
  checkedInBy?: Prisma.UserUpdateOneWithoutCheckinsNestedInput
}

export type CheckinUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bookingItemId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookingId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkedInById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkedInAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  method?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CheckinCreateManyInput = {
  id?: string
  bookingItemId?: string | null
  bookingId?: string | null
  passengerId?: string | null
  checkedInById?: string | null
  checkedInAt?: Date | string
  method?: string
}

export type CheckinUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  checkedInAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  method?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CheckinUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bookingItemId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookingId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkedInById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkedInAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  method?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CheckinListRelationFilter = {
  every?: Prisma.CheckinWhereInput
  some?: Prisma.CheckinWhereInput
  none?: Prisma.CheckinWhereInput
}

export type CheckinOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CheckinNullableScalarRelationFilter = {
  is?: Prisma.CheckinWhereInput | null
  isNot?: Prisma.CheckinWhereInput | null
}

export type CheckinCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bookingItemId?: Prisma.SortOrder
  bookingId?: Prisma.SortOrder
  passengerId?: Prisma.SortOrder
  checkedInById?: Prisma.SortOrder
  checkedInAt?: Prisma.SortOrder
  method?: Prisma.SortOrder
}

export type CheckinMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bookingItemId?: Prisma.SortOrder
  bookingId?: Prisma.SortOrder
  passengerId?: Prisma.SortOrder
  checkedInById?: Prisma.SortOrder
  checkedInAt?: Prisma.SortOrder
  method?: Prisma.SortOrder
}

export type CheckinMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bookingItemId?: Prisma.SortOrder
  bookingId?: Prisma.SortOrder
  passengerId?: Prisma.SortOrder
  checkedInById?: Prisma.SortOrder
  checkedInAt?: Prisma.SortOrder
  method?: Prisma.SortOrder
}

export type CheckinCreateNestedManyWithoutCheckedInByInput = {
  create?: Prisma.XOR<Prisma.CheckinCreateWithoutCheckedInByInput, Prisma.CheckinUncheckedCreateWithoutCheckedInByInput> | Prisma.CheckinCreateWithoutCheckedInByInput[] | Prisma.CheckinUncheckedCreateWithoutCheckedInByInput[]
  connectOrCreate?: Prisma.CheckinCreateOrConnectWithoutCheckedInByInput | Prisma.CheckinCreateOrConnectWithoutCheckedInByInput[]
  createMany?: Prisma.CheckinCreateManyCheckedInByInputEnvelope
  connect?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
}

export type CheckinUncheckedCreateNestedManyWithoutCheckedInByInput = {
  create?: Prisma.XOR<Prisma.CheckinCreateWithoutCheckedInByInput, Prisma.CheckinUncheckedCreateWithoutCheckedInByInput> | Prisma.CheckinCreateWithoutCheckedInByInput[] | Prisma.CheckinUncheckedCreateWithoutCheckedInByInput[]
  connectOrCreate?: Prisma.CheckinCreateOrConnectWithoutCheckedInByInput | Prisma.CheckinCreateOrConnectWithoutCheckedInByInput[]
  createMany?: Prisma.CheckinCreateManyCheckedInByInputEnvelope
  connect?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
}

export type CheckinUpdateManyWithoutCheckedInByNestedInput = {
  create?: Prisma.XOR<Prisma.CheckinCreateWithoutCheckedInByInput, Prisma.CheckinUncheckedCreateWithoutCheckedInByInput> | Prisma.CheckinCreateWithoutCheckedInByInput[] | Prisma.CheckinUncheckedCreateWithoutCheckedInByInput[]
  connectOrCreate?: Prisma.CheckinCreateOrConnectWithoutCheckedInByInput | Prisma.CheckinCreateOrConnectWithoutCheckedInByInput[]
  upsert?: Prisma.CheckinUpsertWithWhereUniqueWithoutCheckedInByInput | Prisma.CheckinUpsertWithWhereUniqueWithoutCheckedInByInput[]
  createMany?: Prisma.CheckinCreateManyCheckedInByInputEnvelope
  set?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
  disconnect?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
  delete?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
  connect?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
  update?: Prisma.CheckinUpdateWithWhereUniqueWithoutCheckedInByInput | Prisma.CheckinUpdateWithWhereUniqueWithoutCheckedInByInput[]
  updateMany?: Prisma.CheckinUpdateManyWithWhereWithoutCheckedInByInput | Prisma.CheckinUpdateManyWithWhereWithoutCheckedInByInput[]
  deleteMany?: Prisma.CheckinScalarWhereInput | Prisma.CheckinScalarWhereInput[]
}

export type CheckinUncheckedUpdateManyWithoutCheckedInByNestedInput = {
  create?: Prisma.XOR<Prisma.CheckinCreateWithoutCheckedInByInput, Prisma.CheckinUncheckedCreateWithoutCheckedInByInput> | Prisma.CheckinCreateWithoutCheckedInByInput[] | Prisma.CheckinUncheckedCreateWithoutCheckedInByInput[]
  connectOrCreate?: Prisma.CheckinCreateOrConnectWithoutCheckedInByInput | Prisma.CheckinCreateOrConnectWithoutCheckedInByInput[]
  upsert?: Prisma.CheckinUpsertWithWhereUniqueWithoutCheckedInByInput | Prisma.CheckinUpsertWithWhereUniqueWithoutCheckedInByInput[]
  createMany?: Prisma.CheckinCreateManyCheckedInByInputEnvelope
  set?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
  disconnect?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
  delete?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
  connect?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
  update?: Prisma.CheckinUpdateWithWhereUniqueWithoutCheckedInByInput | Prisma.CheckinUpdateWithWhereUniqueWithoutCheckedInByInput[]
  updateMany?: Prisma.CheckinUpdateManyWithWhereWithoutCheckedInByInput | Prisma.CheckinUpdateManyWithWhereWithoutCheckedInByInput[]
  deleteMany?: Prisma.CheckinScalarWhereInput | Prisma.CheckinScalarWhereInput[]
}

export type CheckinCreateNestedManyWithoutBookingInput = {
  create?: Prisma.XOR<Prisma.CheckinCreateWithoutBookingInput, Prisma.CheckinUncheckedCreateWithoutBookingInput> | Prisma.CheckinCreateWithoutBookingInput[] | Prisma.CheckinUncheckedCreateWithoutBookingInput[]
  connectOrCreate?: Prisma.CheckinCreateOrConnectWithoutBookingInput | Prisma.CheckinCreateOrConnectWithoutBookingInput[]
  createMany?: Prisma.CheckinCreateManyBookingInputEnvelope
  connect?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
}

export type CheckinUncheckedCreateNestedManyWithoutBookingInput = {
  create?: Prisma.XOR<Prisma.CheckinCreateWithoutBookingInput, Prisma.CheckinUncheckedCreateWithoutBookingInput> | Prisma.CheckinCreateWithoutBookingInput[] | Prisma.CheckinUncheckedCreateWithoutBookingInput[]
  connectOrCreate?: Prisma.CheckinCreateOrConnectWithoutBookingInput | Prisma.CheckinCreateOrConnectWithoutBookingInput[]
  createMany?: Prisma.CheckinCreateManyBookingInputEnvelope
  connect?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
}

export type CheckinUpdateManyWithoutBookingNestedInput = {
  create?: Prisma.XOR<Prisma.CheckinCreateWithoutBookingInput, Prisma.CheckinUncheckedCreateWithoutBookingInput> | Prisma.CheckinCreateWithoutBookingInput[] | Prisma.CheckinUncheckedCreateWithoutBookingInput[]
  connectOrCreate?: Prisma.CheckinCreateOrConnectWithoutBookingInput | Prisma.CheckinCreateOrConnectWithoutBookingInput[]
  upsert?: Prisma.CheckinUpsertWithWhereUniqueWithoutBookingInput | Prisma.CheckinUpsertWithWhereUniqueWithoutBookingInput[]
  createMany?: Prisma.CheckinCreateManyBookingInputEnvelope
  set?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
  disconnect?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
  delete?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
  connect?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
  update?: Prisma.CheckinUpdateWithWhereUniqueWithoutBookingInput | Prisma.CheckinUpdateWithWhereUniqueWithoutBookingInput[]
  updateMany?: Prisma.CheckinUpdateManyWithWhereWithoutBookingInput | Prisma.CheckinUpdateManyWithWhereWithoutBookingInput[]
  deleteMany?: Prisma.CheckinScalarWhereInput | Prisma.CheckinScalarWhereInput[]
}

export type CheckinUncheckedUpdateManyWithoutBookingNestedInput = {
  create?: Prisma.XOR<Prisma.CheckinCreateWithoutBookingInput, Prisma.CheckinUncheckedCreateWithoutBookingInput> | Prisma.CheckinCreateWithoutBookingInput[] | Prisma.CheckinUncheckedCreateWithoutBookingInput[]
  connectOrCreate?: Prisma.CheckinCreateOrConnectWithoutBookingInput | Prisma.CheckinCreateOrConnectWithoutBookingInput[]
  upsert?: Prisma.CheckinUpsertWithWhereUniqueWithoutBookingInput | Prisma.CheckinUpsertWithWhereUniqueWithoutBookingInput[]
  createMany?: Prisma.CheckinCreateManyBookingInputEnvelope
  set?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
  disconnect?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
  delete?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
  connect?: Prisma.CheckinWhereUniqueInput | Prisma.CheckinWhereUniqueInput[]
  update?: Prisma.CheckinUpdateWithWhereUniqueWithoutBookingInput | Prisma.CheckinUpdateWithWhereUniqueWithoutBookingInput[]
  updateMany?: Prisma.CheckinUpdateManyWithWhereWithoutBookingInput | Prisma.CheckinUpdateManyWithWhereWithoutBookingInput[]
  deleteMany?: Prisma.CheckinScalarWhereInput | Prisma.CheckinScalarWhereInput[]
}

export type CheckinCreateNestedOneWithoutBookingItemInput = {
  create?: Prisma.XOR<Prisma.CheckinCreateWithoutBookingItemInput, Prisma.CheckinUncheckedCreateWithoutBookingItemInput>
  connectOrCreate?: Prisma.CheckinCreateOrConnectWithoutBookingItemInput
  connect?: Prisma.CheckinWhereUniqueInput
}

export type CheckinUncheckedCreateNestedOneWithoutBookingItemInput = {
  create?: Prisma.XOR<Prisma.CheckinCreateWithoutBookingItemInput, Prisma.CheckinUncheckedCreateWithoutBookingItemInput>
  connectOrCreate?: Prisma.CheckinCreateOrConnectWithoutBookingItemInput
  connect?: Prisma.CheckinWhereUniqueInput
}

export type CheckinUpdateOneWithoutBookingItemNestedInput = {
  create?: Prisma.XOR<Prisma.CheckinCreateWithoutBookingItemInput, Prisma.CheckinUncheckedCreateWithoutBookingItemInput>
  connectOrCreate?: Prisma.CheckinCreateOrConnectWithoutBookingItemInput
  upsert?: Prisma.CheckinUpsertWithoutBookingItemInput
  disconnect?: Prisma.CheckinWhereInput | boolean
  delete?: Prisma.CheckinWhereInput | boolean
  connect?: Prisma.CheckinWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CheckinUpdateToOneWithWhereWithoutBookingItemInput, Prisma.CheckinUpdateWithoutBookingItemInput>, Prisma.CheckinUncheckedUpdateWithoutBookingItemInput>
}

export type CheckinUncheckedUpdateOneWithoutBookingItemNestedInput = {
  create?: Prisma.XOR<Prisma.CheckinCreateWithoutBookingItemInput, Prisma.CheckinUncheckedCreateWithoutBookingItemInput>
  connectOrCreate?: Prisma.CheckinCreateOrConnectWithoutBookingItemInput
  upsert?: Prisma.CheckinUpsertWithoutBookingItemInput
  disconnect?: Prisma.CheckinWhereInput | boolean
  delete?: Prisma.CheckinWhereInput | boolean
  connect?: Prisma.CheckinWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CheckinUpdateToOneWithWhereWithoutBookingItemInput, Prisma.CheckinUpdateWithoutBookingItemInput>, Prisma.CheckinUncheckedUpdateWithoutBookingItemInput>
}

export type CheckinCreateNestedOneWithoutPassengerInput = {
  create?: Prisma.XOR<Prisma.CheckinCreateWithoutPassengerInput, Prisma.CheckinUncheckedCreateWithoutPassengerInput>
  connectOrCreate?: Prisma.CheckinCreateOrConnectWithoutPassengerInput
  connect?: Prisma.CheckinWhereUniqueInput
}

export type CheckinUncheckedCreateNestedOneWithoutPassengerInput = {
  create?: Prisma.XOR<Prisma.CheckinCreateWithoutPassengerInput, Prisma.CheckinUncheckedCreateWithoutPassengerInput>
  connectOrCreate?: Prisma.CheckinCreateOrConnectWithoutPassengerInput
  connect?: Prisma.CheckinWhereUniqueInput
}

export type CheckinUpdateOneWithoutPassengerNestedInput = {
  create?: Prisma.XOR<Prisma.CheckinCreateWithoutPassengerInput, Prisma.CheckinUncheckedCreateWithoutPassengerInput>
  connectOrCreate?: Prisma.CheckinCreateOrConnectWithoutPassengerInput
  upsert?: Prisma.CheckinUpsertWithoutPassengerInput
  disconnect?: Prisma.CheckinWhereInput | boolean
  delete?: Prisma.CheckinWhereInput | boolean
  connect?: Prisma.CheckinWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CheckinUpdateToOneWithWhereWithoutPassengerInput, Prisma.CheckinUpdateWithoutPassengerInput>, Prisma.CheckinUncheckedUpdateWithoutPassengerInput>
}

export type CheckinUncheckedUpdateOneWithoutPassengerNestedInput = {
  create?: Prisma.XOR<Prisma.CheckinCreateWithoutPassengerInput, Prisma.CheckinUncheckedCreateWithoutPassengerInput>
  connectOrCreate?: Prisma.CheckinCreateOrConnectWithoutPassengerInput
  upsert?: Prisma.CheckinUpsertWithoutPassengerInput
  disconnect?: Prisma.CheckinWhereInput | boolean
  delete?: Prisma.CheckinWhereInput | boolean
  connect?: Prisma.CheckinWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CheckinUpdateToOneWithWhereWithoutPassengerInput, Prisma.CheckinUpdateWithoutPassengerInput>, Prisma.CheckinUncheckedUpdateWithoutPassengerInput>
}

export type CheckinCreateWithoutCheckedInByInput = {
  id?: string
  checkedInAt?: Date | string
  method?: string
  bookingItem?: Prisma.BookingItemCreateNestedOneWithoutCheckinInput
  booking?: Prisma.BookingCreateNestedOneWithoutCheckinRecordsInput
  passenger?: Prisma.PassengerCreateNestedOneWithoutCheckinInput
}

export type CheckinUncheckedCreateWithoutCheckedInByInput = {
  id?: string
  bookingItemId?: string | null
  bookingId?: string | null
  passengerId?: string | null
  checkedInAt?: Date | string
  method?: string
}

export type CheckinCreateOrConnectWithoutCheckedInByInput = {
  where: Prisma.CheckinWhereUniqueInput
  create: Prisma.XOR<Prisma.CheckinCreateWithoutCheckedInByInput, Prisma.CheckinUncheckedCreateWithoutCheckedInByInput>
}

export type CheckinCreateManyCheckedInByInputEnvelope = {
  data: Prisma.CheckinCreateManyCheckedInByInput | Prisma.CheckinCreateManyCheckedInByInput[]
  skipDuplicates?: boolean
}

export type CheckinUpsertWithWhereUniqueWithoutCheckedInByInput = {
  where: Prisma.CheckinWhereUniqueInput
  update: Prisma.XOR<Prisma.CheckinUpdateWithoutCheckedInByInput, Prisma.CheckinUncheckedUpdateWithoutCheckedInByInput>
  create: Prisma.XOR<Prisma.CheckinCreateWithoutCheckedInByInput, Prisma.CheckinUncheckedCreateWithoutCheckedInByInput>
}

export type CheckinUpdateWithWhereUniqueWithoutCheckedInByInput = {
  where: Prisma.CheckinWhereUniqueInput
  data: Prisma.XOR<Prisma.CheckinUpdateWithoutCheckedInByInput, Prisma.CheckinUncheckedUpdateWithoutCheckedInByInput>
}

export type CheckinUpdateManyWithWhereWithoutCheckedInByInput = {
  where: Prisma.CheckinScalarWhereInput
  data: Prisma.XOR<Prisma.CheckinUpdateManyMutationInput, Prisma.CheckinUncheckedUpdateManyWithoutCheckedInByInput>
}

export type CheckinScalarWhereInput = {
  AND?: Prisma.CheckinScalarWhereInput | Prisma.CheckinScalarWhereInput[]
  OR?: Prisma.CheckinScalarWhereInput[]
  NOT?: Prisma.CheckinScalarWhereInput | Prisma.CheckinScalarWhereInput[]
  id?: Prisma.StringFilter<"Checkin"> | string
  bookingItemId?: Prisma.StringNullableFilter<"Checkin"> | string | null
  bookingId?: Prisma.StringNullableFilter<"Checkin"> | string | null
  passengerId?: Prisma.StringNullableFilter<"Checkin"> | string | null
  checkedInById?: Prisma.UuidNullableFilter<"Checkin"> | string | null
  checkedInAt?: Prisma.DateTimeFilter<"Checkin"> | Date | string
  method?: Prisma.StringFilter<"Checkin"> | string
}

export type CheckinCreateWithoutBookingInput = {
  id?: string
  checkedInAt?: Date | string
  method?: string
  bookingItem?: Prisma.BookingItemCreateNestedOneWithoutCheckinInput
  passenger?: Prisma.PassengerCreateNestedOneWithoutCheckinInput
  checkedInBy?: Prisma.UserCreateNestedOneWithoutCheckinsInput
}

export type CheckinUncheckedCreateWithoutBookingInput = {
  id?: string
  bookingItemId?: string | null
  passengerId?: string | null
  checkedInById?: string | null
  checkedInAt?: Date | string
  method?: string
}

export type CheckinCreateOrConnectWithoutBookingInput = {
  where: Prisma.CheckinWhereUniqueInput
  create: Prisma.XOR<Prisma.CheckinCreateWithoutBookingInput, Prisma.CheckinUncheckedCreateWithoutBookingInput>
}

export type CheckinCreateManyBookingInputEnvelope = {
  data: Prisma.CheckinCreateManyBookingInput | Prisma.CheckinCreateManyBookingInput[]
  skipDuplicates?: boolean
}

export type CheckinUpsertWithWhereUniqueWithoutBookingInput = {
  where: Prisma.CheckinWhereUniqueInput
  update: Prisma.XOR<Prisma.CheckinUpdateWithoutBookingInput, Prisma.CheckinUncheckedUpdateWithoutBookingInput>
  create: Prisma.XOR<Prisma.CheckinCreateWithoutBookingInput, Prisma.CheckinUncheckedCreateWithoutBookingInput>
}

export type CheckinUpdateWithWhereUniqueWithoutBookingInput = {
  where: Prisma.CheckinWhereUniqueInput
  data: Prisma.XOR<Prisma.CheckinUpdateWithoutBookingInput, Prisma.CheckinUncheckedUpdateWithoutBookingInput>
}

export type CheckinUpdateManyWithWhereWithoutBookingInput = {
  where: Prisma.CheckinScalarWhereInput
  data: Prisma.XOR<Prisma.CheckinUpdateManyMutationInput, Prisma.CheckinUncheckedUpdateManyWithoutBookingInput>
}

export type CheckinCreateWithoutBookingItemInput = {
  id?: string
  checkedInAt?: Date | string
  method?: string
  booking?: Prisma.BookingCreateNestedOneWithoutCheckinRecordsInput
  passenger?: Prisma.PassengerCreateNestedOneWithoutCheckinInput
  checkedInBy?: Prisma.UserCreateNestedOneWithoutCheckinsInput
}

export type CheckinUncheckedCreateWithoutBookingItemInput = {
  id?: string
  bookingId?: string | null
  passengerId?: string | null
  checkedInById?: string | null
  checkedInAt?: Date | string
  method?: string
}

export type CheckinCreateOrConnectWithoutBookingItemInput = {
  where: Prisma.CheckinWhereUniqueInput
  create: Prisma.XOR<Prisma.CheckinCreateWithoutBookingItemInput, Prisma.CheckinUncheckedCreateWithoutBookingItemInput>
}

export type CheckinUpsertWithoutBookingItemInput = {
  update: Prisma.XOR<Prisma.CheckinUpdateWithoutBookingItemInput, Prisma.CheckinUncheckedUpdateWithoutBookingItemInput>
  create: Prisma.XOR<Prisma.CheckinCreateWithoutBookingItemInput, Prisma.CheckinUncheckedCreateWithoutBookingItemInput>
  where?: Prisma.CheckinWhereInput
}

export type CheckinUpdateToOneWithWhereWithoutBookingItemInput = {
  where?: Prisma.CheckinWhereInput
  data: Prisma.XOR<Prisma.CheckinUpdateWithoutBookingItemInput, Prisma.CheckinUncheckedUpdateWithoutBookingItemInput>
}

export type CheckinUpdateWithoutBookingItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  checkedInAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  method?: Prisma.StringFieldUpdateOperationsInput | string
  booking?: Prisma.BookingUpdateOneWithoutCheckinRecordsNestedInput
  passenger?: Prisma.PassengerUpdateOneWithoutCheckinNestedInput
  checkedInBy?: Prisma.UserUpdateOneWithoutCheckinsNestedInput
}

export type CheckinUncheckedUpdateWithoutBookingItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bookingId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkedInById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkedInAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  method?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CheckinCreateWithoutPassengerInput = {
  id?: string
  checkedInAt?: Date | string
  method?: string
  bookingItem?: Prisma.BookingItemCreateNestedOneWithoutCheckinInput
  booking?: Prisma.BookingCreateNestedOneWithoutCheckinRecordsInput
  checkedInBy?: Prisma.UserCreateNestedOneWithoutCheckinsInput
}

export type CheckinUncheckedCreateWithoutPassengerInput = {
  id?: string
  bookingItemId?: string | null
  bookingId?: string | null
  checkedInById?: string | null
  checkedInAt?: Date | string
  method?: string
}

export type CheckinCreateOrConnectWithoutPassengerInput = {
  where: Prisma.CheckinWhereUniqueInput
  create: Prisma.XOR<Prisma.CheckinCreateWithoutPassengerInput, Prisma.CheckinUncheckedCreateWithoutPassengerInput>
}

export type CheckinUpsertWithoutPassengerInput = {
  update: Prisma.XOR<Prisma.CheckinUpdateWithoutPassengerInput, Prisma.CheckinUncheckedUpdateWithoutPassengerInput>
  create: Prisma.XOR<Prisma.CheckinCreateWithoutPassengerInput, Prisma.CheckinUncheckedCreateWithoutPassengerInput>
  where?: Prisma.CheckinWhereInput
}

export type CheckinUpdateToOneWithWhereWithoutPassengerInput = {
  where?: Prisma.CheckinWhereInput
  data: Prisma.XOR<Prisma.CheckinUpdateWithoutPassengerInput, Prisma.CheckinUncheckedUpdateWithoutPassengerInput>
}

export type CheckinUpdateWithoutPassengerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  checkedInAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  method?: Prisma.StringFieldUpdateOperationsInput | string
  bookingItem?: Prisma.BookingItemUpdateOneWithoutCheckinNestedInput
  booking?: Prisma.BookingUpdateOneWithoutCheckinRecordsNestedInput
  checkedInBy?: Prisma.UserUpdateOneWithoutCheckinsNestedInput
}

export type CheckinUncheckedUpdateWithoutPassengerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bookingItemId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookingId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkedInById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkedInAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  method?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CheckinCreateManyCheckedInByInput = {
  id?: string
  bookingItemId?: string | null
  bookingId?: string | null
  passengerId?: string | null
  checkedInAt?: Date | string
  method?: string
}

export type CheckinUpdateWithoutCheckedInByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  checkedInAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  method?: Prisma.StringFieldUpdateOperationsInput | string
  bookingItem?: Prisma.BookingItemUpdateOneWithoutCheckinNestedInput
  booking?: Prisma.BookingUpdateOneWithoutCheckinRecordsNestedInput
  passenger?: Prisma.PassengerUpdateOneWithoutCheckinNestedInput
}

export type CheckinUncheckedUpdateWithoutCheckedInByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bookingItemId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookingId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkedInAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  method?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CheckinUncheckedUpdateManyWithoutCheckedInByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bookingItemId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookingId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkedInAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  method?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CheckinCreateManyBookingInput = {
  id?: string
  bookingItemId?: string | null
  passengerId?: string | null
  checkedInById?: string | null
  checkedInAt?: Date | string
  method?: string
}

export type CheckinUpdateWithoutBookingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  checkedInAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  method?: Prisma.StringFieldUpdateOperationsInput | string
  bookingItem?: Prisma.BookingItemUpdateOneWithoutCheckinNestedInput
  passenger?: Prisma.PassengerUpdateOneWithoutCheckinNestedInput
  checkedInBy?: Prisma.UserUpdateOneWithoutCheckinsNestedInput
}

export type CheckinUncheckedUpdateWithoutBookingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bookingItemId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkedInById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkedInAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  method?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CheckinUncheckedUpdateManyWithoutBookingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bookingItemId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkedInById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  checkedInAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  method?: Prisma.StringFieldUpdateOperationsInput | string
}



export type CheckinSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bookingItemId?: boolean
  bookingId?: boolean
  passengerId?: boolean
  checkedInById?: boolean
  checkedInAt?: boolean
  method?: boolean
  bookingItem?: boolean | Prisma.Checkin$bookingItemArgs<ExtArgs>
  booking?: boolean | Prisma.Checkin$bookingArgs<ExtArgs>
  passenger?: boolean | Prisma.Checkin$passengerArgs<ExtArgs>
  checkedInBy?: boolean | Prisma.Checkin$checkedInByArgs<ExtArgs>
}, ExtArgs["result"]["checkin"]>

export type CheckinSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bookingItemId?: boolean
  bookingId?: boolean
  passengerId?: boolean
  checkedInById?: boolean
  checkedInAt?: boolean
  method?: boolean
  bookingItem?: boolean | Prisma.Checkin$bookingItemArgs<ExtArgs>
  booking?: boolean | Prisma.Checkin$bookingArgs<ExtArgs>
  passenger?: boolean | Prisma.Checkin$passengerArgs<ExtArgs>
  checkedInBy?: boolean | Prisma.Checkin$checkedInByArgs<ExtArgs>
}, ExtArgs["result"]["checkin"]>

export type CheckinSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bookingItemId?: boolean
  bookingId?: boolean
  passengerId?: boolean
  checkedInById?: boolean
  checkedInAt?: boolean
  method?: boolean
  bookingItem?: boolean | Prisma.Checkin$bookingItemArgs<ExtArgs>
  booking?: boolean | Prisma.Checkin$bookingArgs<ExtArgs>
  passenger?: boolean | Prisma.Checkin$passengerArgs<ExtArgs>
  checkedInBy?: boolean | Prisma.Checkin$checkedInByArgs<ExtArgs>
}, ExtArgs["result"]["checkin"]>

export type CheckinSelectScalar = {
  id?: boolean
  bookingItemId?: boolean
  bookingId?: boolean
  passengerId?: boolean
  checkedInById?: boolean
  checkedInAt?: boolean
  method?: boolean
}

export type CheckinOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "bookingItemId" | "bookingId" | "passengerId" | "checkedInById" | "checkedInAt" | "method", ExtArgs["result"]["checkin"]>
export type CheckinInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bookingItem?: boolean | Prisma.Checkin$bookingItemArgs<ExtArgs>
  booking?: boolean | Prisma.Checkin$bookingArgs<ExtArgs>
  passenger?: boolean | Prisma.Checkin$passengerArgs<ExtArgs>
  checkedInBy?: boolean | Prisma.Checkin$checkedInByArgs<ExtArgs>
}
export type CheckinIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bookingItem?: boolean | Prisma.Checkin$bookingItemArgs<ExtArgs>
  booking?: boolean | Prisma.Checkin$bookingArgs<ExtArgs>
  passenger?: boolean | Prisma.Checkin$passengerArgs<ExtArgs>
  checkedInBy?: boolean | Prisma.Checkin$checkedInByArgs<ExtArgs>
}
export type CheckinIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bookingItem?: boolean | Prisma.Checkin$bookingItemArgs<ExtArgs>
  booking?: boolean | Prisma.Checkin$bookingArgs<ExtArgs>
  passenger?: boolean | Prisma.Checkin$passengerArgs<ExtArgs>
  checkedInBy?: boolean | Prisma.Checkin$checkedInByArgs<ExtArgs>
}

export type $CheckinPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Checkin"
  objects: {
    bookingItem: Prisma.$BookingItemPayload<ExtArgs> | null
    booking: Prisma.$BookingPayload<ExtArgs> | null
    passenger: Prisma.$PassengerPayload<ExtArgs> | null
    checkedInBy: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    bookingItemId: string | null
    bookingId: string | null
    passengerId: string | null
    checkedInById: string | null
    checkedInAt: Date
    method: string
  }, ExtArgs["result"]["checkin"]>
  composites: {}
}

export type CheckinGetPayload<S extends boolean | null | undefined | CheckinDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CheckinPayload, S>

export type CheckinCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CheckinFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CheckinCountAggregateInputType | true
  }

export interface CheckinDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Checkin'], meta: { name: 'Checkin' } }
  /**
   * Find zero or one Checkin that matches the filter.
   * @param {CheckinFindUniqueArgs} args - Arguments to find a Checkin
   * @example
   * // Get one Checkin
   * const checkin = await prisma.checkin.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CheckinFindUniqueArgs>(args: Prisma.SelectSubset<T, CheckinFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CheckinClient<runtime.Types.Result.GetResult<Prisma.$CheckinPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Checkin that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CheckinFindUniqueOrThrowArgs} args - Arguments to find a Checkin
   * @example
   * // Get one Checkin
   * const checkin = await prisma.checkin.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CheckinFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CheckinFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CheckinClient<runtime.Types.Result.GetResult<Prisma.$CheckinPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Checkin that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckinFindFirstArgs} args - Arguments to find a Checkin
   * @example
   * // Get one Checkin
   * const checkin = await prisma.checkin.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CheckinFindFirstArgs>(args?: Prisma.SelectSubset<T, CheckinFindFirstArgs<ExtArgs>>): Prisma.Prisma__CheckinClient<runtime.Types.Result.GetResult<Prisma.$CheckinPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Checkin that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckinFindFirstOrThrowArgs} args - Arguments to find a Checkin
   * @example
   * // Get one Checkin
   * const checkin = await prisma.checkin.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CheckinFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CheckinFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CheckinClient<runtime.Types.Result.GetResult<Prisma.$CheckinPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Checkins that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckinFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Checkins
   * const checkins = await prisma.checkin.findMany()
   * 
   * // Get first 10 Checkins
   * const checkins = await prisma.checkin.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const checkinWithIdOnly = await prisma.checkin.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CheckinFindManyArgs>(args?: Prisma.SelectSubset<T, CheckinFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckinPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Checkin.
   * @param {CheckinCreateArgs} args - Arguments to create a Checkin.
   * @example
   * // Create one Checkin
   * const Checkin = await prisma.checkin.create({
   *   data: {
   *     // ... data to create a Checkin
   *   }
   * })
   * 
   */
  create<T extends CheckinCreateArgs>(args: Prisma.SelectSubset<T, CheckinCreateArgs<ExtArgs>>): Prisma.Prisma__CheckinClient<runtime.Types.Result.GetResult<Prisma.$CheckinPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Checkins.
   * @param {CheckinCreateManyArgs} args - Arguments to create many Checkins.
   * @example
   * // Create many Checkins
   * const checkin = await prisma.checkin.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CheckinCreateManyArgs>(args?: Prisma.SelectSubset<T, CheckinCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Checkins and returns the data saved in the database.
   * @param {CheckinCreateManyAndReturnArgs} args - Arguments to create many Checkins.
   * @example
   * // Create many Checkins
   * const checkin = await prisma.checkin.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Checkins and only return the `id`
   * const checkinWithIdOnly = await prisma.checkin.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CheckinCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CheckinCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckinPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Checkin.
   * @param {CheckinDeleteArgs} args - Arguments to delete one Checkin.
   * @example
   * // Delete one Checkin
   * const Checkin = await prisma.checkin.delete({
   *   where: {
   *     // ... filter to delete one Checkin
   *   }
   * })
   * 
   */
  delete<T extends CheckinDeleteArgs>(args: Prisma.SelectSubset<T, CheckinDeleteArgs<ExtArgs>>): Prisma.Prisma__CheckinClient<runtime.Types.Result.GetResult<Prisma.$CheckinPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Checkin.
   * @param {CheckinUpdateArgs} args - Arguments to update one Checkin.
   * @example
   * // Update one Checkin
   * const checkin = await prisma.checkin.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CheckinUpdateArgs>(args: Prisma.SelectSubset<T, CheckinUpdateArgs<ExtArgs>>): Prisma.Prisma__CheckinClient<runtime.Types.Result.GetResult<Prisma.$CheckinPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Checkins.
   * @param {CheckinDeleteManyArgs} args - Arguments to filter Checkins to delete.
   * @example
   * // Delete a few Checkins
   * const { count } = await prisma.checkin.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CheckinDeleteManyArgs>(args?: Prisma.SelectSubset<T, CheckinDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Checkins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckinUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Checkins
   * const checkin = await prisma.checkin.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CheckinUpdateManyArgs>(args: Prisma.SelectSubset<T, CheckinUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Checkins and returns the data updated in the database.
   * @param {CheckinUpdateManyAndReturnArgs} args - Arguments to update many Checkins.
   * @example
   * // Update many Checkins
   * const checkin = await prisma.checkin.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Checkins and only return the `id`
   * const checkinWithIdOnly = await prisma.checkin.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CheckinUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CheckinUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckinPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Checkin.
   * @param {CheckinUpsertArgs} args - Arguments to update or create a Checkin.
   * @example
   * // Update or create a Checkin
   * const checkin = await prisma.checkin.upsert({
   *   create: {
   *     // ... data to create a Checkin
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Checkin we want to update
   *   }
   * })
   */
  upsert<T extends CheckinUpsertArgs>(args: Prisma.SelectSubset<T, CheckinUpsertArgs<ExtArgs>>): Prisma.Prisma__CheckinClient<runtime.Types.Result.GetResult<Prisma.$CheckinPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Checkins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckinCountArgs} args - Arguments to filter Checkins to count.
   * @example
   * // Count the number of Checkins
   * const count = await prisma.checkin.count({
   *   where: {
   *     // ... the filter for the Checkins we want to count
   *   }
   * })
  **/
  count<T extends CheckinCountArgs>(
    args?: Prisma.Subset<T, CheckinCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CheckinCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Checkin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckinAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CheckinAggregateArgs>(args: Prisma.Subset<T, CheckinAggregateArgs>): Prisma.PrismaPromise<GetCheckinAggregateType<T>>

  /**
   * Group by Checkin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckinGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CheckinGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CheckinGroupByArgs['orderBy'] }
      : { orderBy?: CheckinGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CheckinGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCheckinGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Checkin model
 */
readonly fields: CheckinFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Checkin.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CheckinClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  bookingItem<T extends Prisma.Checkin$bookingItemArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Checkin$bookingItemArgs<ExtArgs>>): Prisma.Prisma__BookingItemClient<runtime.Types.Result.GetResult<Prisma.$BookingItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  booking<T extends Prisma.Checkin$bookingArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Checkin$bookingArgs<ExtArgs>>): Prisma.Prisma__BookingClient<runtime.Types.Result.GetResult<Prisma.$BookingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  passenger<T extends Prisma.Checkin$passengerArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Checkin$passengerArgs<ExtArgs>>): Prisma.Prisma__PassengerClient<runtime.Types.Result.GetResult<Prisma.$PassengerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  checkedInBy<T extends Prisma.Checkin$checkedInByArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Checkin$checkedInByArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Checkin model
 */
export interface CheckinFieldRefs {
  readonly id: Prisma.FieldRef<"Checkin", 'String'>
  readonly bookingItemId: Prisma.FieldRef<"Checkin", 'String'>
  readonly bookingId: Prisma.FieldRef<"Checkin", 'String'>
  readonly passengerId: Prisma.FieldRef<"Checkin", 'String'>
  readonly checkedInById: Prisma.FieldRef<"Checkin", 'String'>
  readonly checkedInAt: Prisma.FieldRef<"Checkin", 'DateTime'>
  readonly method: Prisma.FieldRef<"Checkin", 'String'>
}
    

// Custom InputTypes
/**
 * Checkin findUnique
 */
export type CheckinFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkin
   */
  select?: Prisma.CheckinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkin
   */
  omit?: Prisma.CheckinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckinInclude<ExtArgs> | null
  /**
   * Filter, which Checkin to fetch.
   */
  where: Prisma.CheckinWhereUniqueInput
}

/**
 * Checkin findUniqueOrThrow
 */
export type CheckinFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkin
   */
  select?: Prisma.CheckinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkin
   */
  omit?: Prisma.CheckinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckinInclude<ExtArgs> | null
  /**
   * Filter, which Checkin to fetch.
   */
  where: Prisma.CheckinWhereUniqueInput
}

/**
 * Checkin findFirst
 */
export type CheckinFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkin
   */
  select?: Prisma.CheckinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkin
   */
  omit?: Prisma.CheckinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckinInclude<ExtArgs> | null
  /**
   * Filter, which Checkin to fetch.
   */
  where?: Prisma.CheckinWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Checkins to fetch.
   */
  orderBy?: Prisma.CheckinOrderByWithRelationInput | Prisma.CheckinOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Checkins.
   */
  cursor?: Prisma.CheckinWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Checkins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Checkins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Checkins.
   */
  distinct?: Prisma.CheckinScalarFieldEnum | Prisma.CheckinScalarFieldEnum[]
}

/**
 * Checkin findFirstOrThrow
 */
export type CheckinFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkin
   */
  select?: Prisma.CheckinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkin
   */
  omit?: Prisma.CheckinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckinInclude<ExtArgs> | null
  /**
   * Filter, which Checkin to fetch.
   */
  where?: Prisma.CheckinWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Checkins to fetch.
   */
  orderBy?: Prisma.CheckinOrderByWithRelationInput | Prisma.CheckinOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Checkins.
   */
  cursor?: Prisma.CheckinWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Checkins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Checkins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Checkins.
   */
  distinct?: Prisma.CheckinScalarFieldEnum | Prisma.CheckinScalarFieldEnum[]
}

/**
 * Checkin findMany
 */
export type CheckinFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkin
   */
  select?: Prisma.CheckinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkin
   */
  omit?: Prisma.CheckinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckinInclude<ExtArgs> | null
  /**
   * Filter, which Checkins to fetch.
   */
  where?: Prisma.CheckinWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Checkins to fetch.
   */
  orderBy?: Prisma.CheckinOrderByWithRelationInput | Prisma.CheckinOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Checkins.
   */
  cursor?: Prisma.CheckinWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Checkins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Checkins.
   */
  skip?: number
  distinct?: Prisma.CheckinScalarFieldEnum | Prisma.CheckinScalarFieldEnum[]
}

/**
 * Checkin create
 */
export type CheckinCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkin
   */
  select?: Prisma.CheckinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkin
   */
  omit?: Prisma.CheckinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckinInclude<ExtArgs> | null
  /**
   * The data needed to create a Checkin.
   */
  data?: Prisma.XOR<Prisma.CheckinCreateInput, Prisma.CheckinUncheckedCreateInput>
}

/**
 * Checkin createMany
 */
export type CheckinCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Checkins.
   */
  data: Prisma.CheckinCreateManyInput | Prisma.CheckinCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Checkin createManyAndReturn
 */
export type CheckinCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkin
   */
  select?: Prisma.CheckinSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Checkin
   */
  omit?: Prisma.CheckinOmit<ExtArgs> | null
  /**
   * The data used to create many Checkins.
   */
  data: Prisma.CheckinCreateManyInput | Prisma.CheckinCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckinIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Checkin update
 */
export type CheckinUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkin
   */
  select?: Prisma.CheckinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkin
   */
  omit?: Prisma.CheckinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckinInclude<ExtArgs> | null
  /**
   * The data needed to update a Checkin.
   */
  data: Prisma.XOR<Prisma.CheckinUpdateInput, Prisma.CheckinUncheckedUpdateInput>
  /**
   * Choose, which Checkin to update.
   */
  where: Prisma.CheckinWhereUniqueInput
}

/**
 * Checkin updateMany
 */
export type CheckinUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Checkins.
   */
  data: Prisma.XOR<Prisma.CheckinUpdateManyMutationInput, Prisma.CheckinUncheckedUpdateManyInput>
  /**
   * Filter which Checkins to update
   */
  where?: Prisma.CheckinWhereInput
  /**
   * Limit how many Checkins to update.
   */
  limit?: number
}

/**
 * Checkin updateManyAndReturn
 */
export type CheckinUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkin
   */
  select?: Prisma.CheckinSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Checkin
   */
  omit?: Prisma.CheckinOmit<ExtArgs> | null
  /**
   * The data used to update Checkins.
   */
  data: Prisma.XOR<Prisma.CheckinUpdateManyMutationInput, Prisma.CheckinUncheckedUpdateManyInput>
  /**
   * Filter which Checkins to update
   */
  where?: Prisma.CheckinWhereInput
  /**
   * Limit how many Checkins to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckinIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Checkin upsert
 */
export type CheckinUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkin
   */
  select?: Prisma.CheckinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkin
   */
  omit?: Prisma.CheckinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckinInclude<ExtArgs> | null
  /**
   * The filter to search for the Checkin to update in case it exists.
   */
  where: Prisma.CheckinWhereUniqueInput
  /**
   * In case the Checkin found by the `where` argument doesn't exist, create a new Checkin with this data.
   */
  create: Prisma.XOR<Prisma.CheckinCreateInput, Prisma.CheckinUncheckedCreateInput>
  /**
   * In case the Checkin was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CheckinUpdateInput, Prisma.CheckinUncheckedUpdateInput>
}

/**
 * Checkin delete
 */
export type CheckinDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkin
   */
  select?: Prisma.CheckinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkin
   */
  omit?: Prisma.CheckinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckinInclude<ExtArgs> | null
  /**
   * Filter which Checkin to delete.
   */
  where: Prisma.CheckinWhereUniqueInput
}

/**
 * Checkin deleteMany
 */
export type CheckinDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Checkins to delete
   */
  where?: Prisma.CheckinWhereInput
  /**
   * Limit how many Checkins to delete.
   */
  limit?: number
}

/**
 * Checkin.bookingItem
 */
export type Checkin$bookingItemArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookingItem
   */
  select?: Prisma.BookingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookingItem
   */
  omit?: Prisma.BookingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingItemInclude<ExtArgs> | null
  where?: Prisma.BookingItemWhereInput
}

/**
 * Checkin.booking
 */
export type Checkin$bookingArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Booking
   */
  select?: Prisma.BookingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Booking
   */
  omit?: Prisma.BookingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingInclude<ExtArgs> | null
  where?: Prisma.BookingWhereInput
}

/**
 * Checkin.passenger
 */
export type Checkin$passengerArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Passenger
   */
  select?: Prisma.PassengerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Passenger
   */
  omit?: Prisma.PassengerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PassengerInclude<ExtArgs> | null
  where?: Prisma.PassengerWhereInput
}

/**
 * Checkin.checkedInBy
 */
export type Checkin$checkedInByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Checkin without action
 */
export type CheckinDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkin
   */
  select?: Prisma.CheckinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkin
   */
  omit?: Prisma.CheckinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckinInclude<ExtArgs> | null
}
