
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PromoCode` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PromoCode
 * 
 */
export type PromoCodeModel = runtime.Types.Result.DefaultSelection<Prisma.$PromoCodePayload>

export type AggregatePromoCode = {
  _count: PromoCodeCountAggregateOutputType | null
  _avg: PromoCodeAvgAggregateOutputType | null
  _sum: PromoCodeSumAggregateOutputType | null
  _min: PromoCodeMinAggregateOutputType | null
  _max: PromoCodeMaxAggregateOutputType | null
}

export type PromoCodeAvgAggregateOutputType = {
  discountValue: number | null
  minPurchase: number | null
  maxDiscount: number | null
  usageLimit: number | null
  usageCount: number | null
  perUserLimit: number | null
}

export type PromoCodeSumAggregateOutputType = {
  discountValue: number | null
  minPurchase: bigint | null
  maxDiscount: bigint | null
  usageLimit: number | null
  usageCount: number | null
  perUserLimit: number | null
}

export type PromoCodeMinAggregateOutputType = {
  id: string | null
  code: string | null
  description: string | null
  discountType: string | null
  discountValue: number | null
  priceTierId: string | null
  minPurchase: bigint | null
  maxDiscount: bigint | null
  usageLimit: number | null
  usageCount: number | null
  perUserLimit: number | null
  validFrom: Date | null
  validUntil: Date | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PromoCodeMaxAggregateOutputType = {
  id: string | null
  code: string | null
  description: string | null
  discountType: string | null
  discountValue: number | null
  priceTierId: string | null
  minPurchase: bigint | null
  maxDiscount: bigint | null
  usageLimit: number | null
  usageCount: number | null
  perUserLimit: number | null
  validFrom: Date | null
  validUntil: Date | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PromoCodeCountAggregateOutputType = {
  id: number
  code: number
  description: number
  discountType: number
  discountValue: number
  priceTierId: number
  minPurchase: number
  maxDiscount: number
  usageLimit: number
  usageCount: number
  perUserLimit: number
  validFrom: number
  validUntil: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PromoCodeAvgAggregateInputType = {
  discountValue?: true
  minPurchase?: true
  maxDiscount?: true
  usageLimit?: true
  usageCount?: true
  perUserLimit?: true
}

export type PromoCodeSumAggregateInputType = {
  discountValue?: true
  minPurchase?: true
  maxDiscount?: true
  usageLimit?: true
  usageCount?: true
  perUserLimit?: true
}

export type PromoCodeMinAggregateInputType = {
  id?: true
  code?: true
  description?: true
  discountType?: true
  discountValue?: true
  priceTierId?: true
  minPurchase?: true
  maxDiscount?: true
  usageLimit?: true
  usageCount?: true
  perUserLimit?: true
  validFrom?: true
  validUntil?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type PromoCodeMaxAggregateInputType = {
  id?: true
  code?: true
  description?: true
  discountType?: true
  discountValue?: true
  priceTierId?: true
  minPurchase?: true
  maxDiscount?: true
  usageLimit?: true
  usageCount?: true
  perUserLimit?: true
  validFrom?: true
  validUntil?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type PromoCodeCountAggregateInputType = {
  id?: true
  code?: true
  description?: true
  discountType?: true
  discountValue?: true
  priceTierId?: true
  minPurchase?: true
  maxDiscount?: true
  usageLimit?: true
  usageCount?: true
  perUserLimit?: true
  validFrom?: true
  validUntil?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PromoCodeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PromoCode to aggregate.
   */
  where?: Prisma.PromoCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PromoCodes to fetch.
   */
  orderBy?: Prisma.PromoCodeOrderByWithRelationInput | Prisma.PromoCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PromoCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PromoCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PromoCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PromoCodes
  **/
  _count?: true | PromoCodeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PromoCodeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PromoCodeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PromoCodeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PromoCodeMaxAggregateInputType
}

export type GetPromoCodeAggregateType<T extends PromoCodeAggregateArgs> = {
      [P in keyof T & keyof AggregatePromoCode]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePromoCode[P]>
    : Prisma.GetScalarType<T[P], AggregatePromoCode[P]>
}




export type PromoCodeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PromoCodeWhereInput
  orderBy?: Prisma.PromoCodeOrderByWithAggregationInput | Prisma.PromoCodeOrderByWithAggregationInput[]
  by: Prisma.PromoCodeScalarFieldEnum[] | Prisma.PromoCodeScalarFieldEnum
  having?: Prisma.PromoCodeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PromoCodeCountAggregateInputType | true
  _avg?: PromoCodeAvgAggregateInputType
  _sum?: PromoCodeSumAggregateInputType
  _min?: PromoCodeMinAggregateInputType
  _max?: PromoCodeMaxAggregateInputType
}

export type PromoCodeGroupByOutputType = {
  id: string
  code: string
  description: string | null
  discountType: string
  discountValue: number
  priceTierId: string | null
  minPurchase: bigint | null
  maxDiscount: bigint | null
  usageLimit: number | null
  usageCount: number
  perUserLimit: number | null
  validFrom: Date
  validUntil: Date
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: PromoCodeCountAggregateOutputType | null
  _avg: PromoCodeAvgAggregateOutputType | null
  _sum: PromoCodeSumAggregateOutputType | null
  _min: PromoCodeMinAggregateOutputType | null
  _max: PromoCodeMaxAggregateOutputType | null
}

type GetPromoCodeGroupByPayload<T extends PromoCodeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PromoCodeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PromoCodeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PromoCodeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PromoCodeGroupByOutputType[P]>
      }
    >
  >



export type PromoCodeWhereInput = {
  AND?: Prisma.PromoCodeWhereInput | Prisma.PromoCodeWhereInput[]
  OR?: Prisma.PromoCodeWhereInput[]
  NOT?: Prisma.PromoCodeWhereInput | Prisma.PromoCodeWhereInput[]
  id?: Prisma.StringFilter<"PromoCode"> | string
  code?: Prisma.StringFilter<"PromoCode"> | string
  description?: Prisma.StringNullableFilter<"PromoCode"> | string | null
  discountType?: Prisma.StringFilter<"PromoCode"> | string
  discountValue?: Prisma.IntFilter<"PromoCode"> | number
  priceTierId?: Prisma.StringNullableFilter<"PromoCode"> | string | null
  minPurchase?: Prisma.BigIntNullableFilter<"PromoCode"> | bigint | number | null
  maxDiscount?: Prisma.BigIntNullableFilter<"PromoCode"> | bigint | number | null
  usageLimit?: Prisma.IntNullableFilter<"PromoCode"> | number | null
  usageCount?: Prisma.IntFilter<"PromoCode"> | number
  perUserLimit?: Prisma.IntNullableFilter<"PromoCode"> | number | null
  validFrom?: Prisma.DateTimeFilter<"PromoCode"> | Date | string
  validUntil?: Prisma.DateTimeFilter<"PromoCode"> | Date | string
  isActive?: Prisma.BoolFilter<"PromoCode"> | boolean
  createdAt?: Prisma.DateTimeFilter<"PromoCode"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PromoCode"> | Date | string
  priceTier?: Prisma.XOR<Prisma.PriceTierNullableScalarRelationFilter, Prisma.PriceTierWhereInput> | null
}

export type PromoCodeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  discountType?: Prisma.SortOrder
  discountValue?: Prisma.SortOrder
  priceTierId?: Prisma.SortOrderInput | Prisma.SortOrder
  minPurchase?: Prisma.SortOrderInput | Prisma.SortOrder
  maxDiscount?: Prisma.SortOrderInput | Prisma.SortOrder
  usageLimit?: Prisma.SortOrderInput | Prisma.SortOrder
  usageCount?: Prisma.SortOrder
  perUserLimit?: Prisma.SortOrderInput | Prisma.SortOrder
  validFrom?: Prisma.SortOrder
  validUntil?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  priceTier?: Prisma.PriceTierOrderByWithRelationInput
}

export type PromoCodeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  code?: string
  AND?: Prisma.PromoCodeWhereInput | Prisma.PromoCodeWhereInput[]
  OR?: Prisma.PromoCodeWhereInput[]
  NOT?: Prisma.PromoCodeWhereInput | Prisma.PromoCodeWhereInput[]
  description?: Prisma.StringNullableFilter<"PromoCode"> | string | null
  discountType?: Prisma.StringFilter<"PromoCode"> | string
  discountValue?: Prisma.IntFilter<"PromoCode"> | number
  priceTierId?: Prisma.StringNullableFilter<"PromoCode"> | string | null
  minPurchase?: Prisma.BigIntNullableFilter<"PromoCode"> | bigint | number | null
  maxDiscount?: Prisma.BigIntNullableFilter<"PromoCode"> | bigint | number | null
  usageLimit?: Prisma.IntNullableFilter<"PromoCode"> | number | null
  usageCount?: Prisma.IntFilter<"PromoCode"> | number
  perUserLimit?: Prisma.IntNullableFilter<"PromoCode"> | number | null
  validFrom?: Prisma.DateTimeFilter<"PromoCode"> | Date | string
  validUntil?: Prisma.DateTimeFilter<"PromoCode"> | Date | string
  isActive?: Prisma.BoolFilter<"PromoCode"> | boolean
  createdAt?: Prisma.DateTimeFilter<"PromoCode"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PromoCode"> | Date | string
  priceTier?: Prisma.XOR<Prisma.PriceTierNullableScalarRelationFilter, Prisma.PriceTierWhereInput> | null
}, "id" | "code">

export type PromoCodeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  discountType?: Prisma.SortOrder
  discountValue?: Prisma.SortOrder
  priceTierId?: Prisma.SortOrderInput | Prisma.SortOrder
  minPurchase?: Prisma.SortOrderInput | Prisma.SortOrder
  maxDiscount?: Prisma.SortOrderInput | Prisma.SortOrder
  usageLimit?: Prisma.SortOrderInput | Prisma.SortOrder
  usageCount?: Prisma.SortOrder
  perUserLimit?: Prisma.SortOrderInput | Prisma.SortOrder
  validFrom?: Prisma.SortOrder
  validUntil?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PromoCodeCountOrderByAggregateInput
  _avg?: Prisma.PromoCodeAvgOrderByAggregateInput
  _max?: Prisma.PromoCodeMaxOrderByAggregateInput
  _min?: Prisma.PromoCodeMinOrderByAggregateInput
  _sum?: Prisma.PromoCodeSumOrderByAggregateInput
}

export type PromoCodeScalarWhereWithAggregatesInput = {
  AND?: Prisma.PromoCodeScalarWhereWithAggregatesInput | Prisma.PromoCodeScalarWhereWithAggregatesInput[]
  OR?: Prisma.PromoCodeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PromoCodeScalarWhereWithAggregatesInput | Prisma.PromoCodeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PromoCode"> | string
  code?: Prisma.StringWithAggregatesFilter<"PromoCode"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"PromoCode"> | string | null
  discountType?: Prisma.StringWithAggregatesFilter<"PromoCode"> | string
  discountValue?: Prisma.IntWithAggregatesFilter<"PromoCode"> | number
  priceTierId?: Prisma.StringNullableWithAggregatesFilter<"PromoCode"> | string | null
  minPurchase?: Prisma.BigIntNullableWithAggregatesFilter<"PromoCode"> | bigint | number | null
  maxDiscount?: Prisma.BigIntNullableWithAggregatesFilter<"PromoCode"> | bigint | number | null
  usageLimit?: Prisma.IntNullableWithAggregatesFilter<"PromoCode"> | number | null
  usageCount?: Prisma.IntWithAggregatesFilter<"PromoCode"> | number
  perUserLimit?: Prisma.IntNullableWithAggregatesFilter<"PromoCode"> | number | null
  validFrom?: Prisma.DateTimeWithAggregatesFilter<"PromoCode"> | Date | string
  validUntil?: Prisma.DateTimeWithAggregatesFilter<"PromoCode"> | Date | string
  isActive?: Prisma.BoolWithAggregatesFilter<"PromoCode"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PromoCode"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PromoCode"> | Date | string
}

export type PromoCodeCreateInput = {
  id?: string
  code: string
  description?: string | null
  discountType: string
  discountValue: number
  minPurchase?: bigint | number | null
  maxDiscount?: bigint | number | null
  usageLimit?: number | null
  usageCount?: number
  perUserLimit?: number | null
  validFrom: Date | string
  validUntil: Date | string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  priceTier?: Prisma.PriceTierCreateNestedOneWithoutPromoCodesInput
}

export type PromoCodeUncheckedCreateInput = {
  id?: string
  code: string
  description?: string | null
  discountType: string
  discountValue: number
  priceTierId?: string | null
  minPurchase?: bigint | number | null
  maxDiscount?: bigint | number | null
  usageLimit?: number | null
  usageCount?: number
  perUserLimit?: number | null
  validFrom: Date | string
  validUntil: Date | string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PromoCodeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discountType?: Prisma.StringFieldUpdateOperationsInput | string
  discountValue?: Prisma.IntFieldUpdateOperationsInput | number
  minPurchase?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  maxDiscount?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  usageLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  usageCount?: Prisma.IntFieldUpdateOperationsInput | number
  perUserLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validUntil?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  priceTier?: Prisma.PriceTierUpdateOneWithoutPromoCodesNestedInput
}

export type PromoCodeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discountType?: Prisma.StringFieldUpdateOperationsInput | string
  discountValue?: Prisma.IntFieldUpdateOperationsInput | number
  priceTierId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  minPurchase?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  maxDiscount?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  usageLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  usageCount?: Prisma.IntFieldUpdateOperationsInput | number
  perUserLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validUntil?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PromoCodeCreateManyInput = {
  id?: string
  code: string
  description?: string | null
  discountType: string
  discountValue: number
  priceTierId?: string | null
  minPurchase?: bigint | number | null
  maxDiscount?: bigint | number | null
  usageLimit?: number | null
  usageCount?: number
  perUserLimit?: number | null
  validFrom: Date | string
  validUntil: Date | string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PromoCodeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discountType?: Prisma.StringFieldUpdateOperationsInput | string
  discountValue?: Prisma.IntFieldUpdateOperationsInput | number
  minPurchase?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  maxDiscount?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  usageLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  usageCount?: Prisma.IntFieldUpdateOperationsInput | number
  perUserLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validUntil?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PromoCodeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discountType?: Prisma.StringFieldUpdateOperationsInput | string
  discountValue?: Prisma.IntFieldUpdateOperationsInput | number
  priceTierId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  minPurchase?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  maxDiscount?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  usageLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  usageCount?: Prisma.IntFieldUpdateOperationsInput | number
  perUserLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validUntil?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PromoCodeListRelationFilter = {
  every?: Prisma.PromoCodeWhereInput
  some?: Prisma.PromoCodeWhereInput
  none?: Prisma.PromoCodeWhereInput
}

export type PromoCodeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PromoCodeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  description?: Prisma.SortOrder
  discountType?: Prisma.SortOrder
  discountValue?: Prisma.SortOrder
  priceTierId?: Prisma.SortOrder
  minPurchase?: Prisma.SortOrder
  maxDiscount?: Prisma.SortOrder
  usageLimit?: Prisma.SortOrder
  usageCount?: Prisma.SortOrder
  perUserLimit?: Prisma.SortOrder
  validFrom?: Prisma.SortOrder
  validUntil?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PromoCodeAvgOrderByAggregateInput = {
  discountValue?: Prisma.SortOrder
  minPurchase?: Prisma.SortOrder
  maxDiscount?: Prisma.SortOrder
  usageLimit?: Prisma.SortOrder
  usageCount?: Prisma.SortOrder
  perUserLimit?: Prisma.SortOrder
}

export type PromoCodeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  description?: Prisma.SortOrder
  discountType?: Prisma.SortOrder
  discountValue?: Prisma.SortOrder
  priceTierId?: Prisma.SortOrder
  minPurchase?: Prisma.SortOrder
  maxDiscount?: Prisma.SortOrder
  usageLimit?: Prisma.SortOrder
  usageCount?: Prisma.SortOrder
  perUserLimit?: Prisma.SortOrder
  validFrom?: Prisma.SortOrder
  validUntil?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PromoCodeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  description?: Prisma.SortOrder
  discountType?: Prisma.SortOrder
  discountValue?: Prisma.SortOrder
  priceTierId?: Prisma.SortOrder
  minPurchase?: Prisma.SortOrder
  maxDiscount?: Prisma.SortOrder
  usageLimit?: Prisma.SortOrder
  usageCount?: Prisma.SortOrder
  perUserLimit?: Prisma.SortOrder
  validFrom?: Prisma.SortOrder
  validUntil?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PromoCodeSumOrderByAggregateInput = {
  discountValue?: Prisma.SortOrder
  minPurchase?: Prisma.SortOrder
  maxDiscount?: Prisma.SortOrder
  usageLimit?: Prisma.SortOrder
  usageCount?: Prisma.SortOrder
  perUserLimit?: Prisma.SortOrder
}

export type PromoCodeCreateNestedManyWithoutPriceTierInput = {
  create?: Prisma.XOR<Prisma.PromoCodeCreateWithoutPriceTierInput, Prisma.PromoCodeUncheckedCreateWithoutPriceTierInput> | Prisma.PromoCodeCreateWithoutPriceTierInput[] | Prisma.PromoCodeUncheckedCreateWithoutPriceTierInput[]
  connectOrCreate?: Prisma.PromoCodeCreateOrConnectWithoutPriceTierInput | Prisma.PromoCodeCreateOrConnectWithoutPriceTierInput[]
  createMany?: Prisma.PromoCodeCreateManyPriceTierInputEnvelope
  connect?: Prisma.PromoCodeWhereUniqueInput | Prisma.PromoCodeWhereUniqueInput[]
}

export type PromoCodeUncheckedCreateNestedManyWithoutPriceTierInput = {
  create?: Prisma.XOR<Prisma.PromoCodeCreateWithoutPriceTierInput, Prisma.PromoCodeUncheckedCreateWithoutPriceTierInput> | Prisma.PromoCodeCreateWithoutPriceTierInput[] | Prisma.PromoCodeUncheckedCreateWithoutPriceTierInput[]
  connectOrCreate?: Prisma.PromoCodeCreateOrConnectWithoutPriceTierInput | Prisma.PromoCodeCreateOrConnectWithoutPriceTierInput[]
  createMany?: Prisma.PromoCodeCreateManyPriceTierInputEnvelope
  connect?: Prisma.PromoCodeWhereUniqueInput | Prisma.PromoCodeWhereUniqueInput[]
}

export type PromoCodeUpdateManyWithoutPriceTierNestedInput = {
  create?: Prisma.XOR<Prisma.PromoCodeCreateWithoutPriceTierInput, Prisma.PromoCodeUncheckedCreateWithoutPriceTierInput> | Prisma.PromoCodeCreateWithoutPriceTierInput[] | Prisma.PromoCodeUncheckedCreateWithoutPriceTierInput[]
  connectOrCreate?: Prisma.PromoCodeCreateOrConnectWithoutPriceTierInput | Prisma.PromoCodeCreateOrConnectWithoutPriceTierInput[]
  upsert?: Prisma.PromoCodeUpsertWithWhereUniqueWithoutPriceTierInput | Prisma.PromoCodeUpsertWithWhereUniqueWithoutPriceTierInput[]
  createMany?: Prisma.PromoCodeCreateManyPriceTierInputEnvelope
  set?: Prisma.PromoCodeWhereUniqueInput | Prisma.PromoCodeWhereUniqueInput[]
  disconnect?: Prisma.PromoCodeWhereUniqueInput | Prisma.PromoCodeWhereUniqueInput[]
  delete?: Prisma.PromoCodeWhereUniqueInput | Prisma.PromoCodeWhereUniqueInput[]
  connect?: Prisma.PromoCodeWhereUniqueInput | Prisma.PromoCodeWhereUniqueInput[]
  update?: Prisma.PromoCodeUpdateWithWhereUniqueWithoutPriceTierInput | Prisma.PromoCodeUpdateWithWhereUniqueWithoutPriceTierInput[]
  updateMany?: Prisma.PromoCodeUpdateManyWithWhereWithoutPriceTierInput | Prisma.PromoCodeUpdateManyWithWhereWithoutPriceTierInput[]
  deleteMany?: Prisma.PromoCodeScalarWhereInput | Prisma.PromoCodeScalarWhereInput[]
}

export type PromoCodeUncheckedUpdateManyWithoutPriceTierNestedInput = {
  create?: Prisma.XOR<Prisma.PromoCodeCreateWithoutPriceTierInput, Prisma.PromoCodeUncheckedCreateWithoutPriceTierInput> | Prisma.PromoCodeCreateWithoutPriceTierInput[] | Prisma.PromoCodeUncheckedCreateWithoutPriceTierInput[]
  connectOrCreate?: Prisma.PromoCodeCreateOrConnectWithoutPriceTierInput | Prisma.PromoCodeCreateOrConnectWithoutPriceTierInput[]
  upsert?: Prisma.PromoCodeUpsertWithWhereUniqueWithoutPriceTierInput | Prisma.PromoCodeUpsertWithWhereUniqueWithoutPriceTierInput[]
  createMany?: Prisma.PromoCodeCreateManyPriceTierInputEnvelope
  set?: Prisma.PromoCodeWhereUniqueInput | Prisma.PromoCodeWhereUniqueInput[]
  disconnect?: Prisma.PromoCodeWhereUniqueInput | Prisma.PromoCodeWhereUniqueInput[]
  delete?: Prisma.PromoCodeWhereUniqueInput | Prisma.PromoCodeWhereUniqueInput[]
  connect?: Prisma.PromoCodeWhereUniqueInput | Prisma.PromoCodeWhereUniqueInput[]
  update?: Prisma.PromoCodeUpdateWithWhereUniqueWithoutPriceTierInput | Prisma.PromoCodeUpdateWithWhereUniqueWithoutPriceTierInput[]
  updateMany?: Prisma.PromoCodeUpdateManyWithWhereWithoutPriceTierInput | Prisma.PromoCodeUpdateManyWithWhereWithoutPriceTierInput[]
  deleteMany?: Prisma.PromoCodeScalarWhereInput | Prisma.PromoCodeScalarWhereInput[]
}

export type PromoCodeCreateWithoutPriceTierInput = {
  id?: string
  code: string
  description?: string | null
  discountType: string
  discountValue: number
  minPurchase?: bigint | number | null
  maxDiscount?: bigint | number | null
  usageLimit?: number | null
  usageCount?: number
  perUserLimit?: number | null
  validFrom: Date | string
  validUntil: Date | string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PromoCodeUncheckedCreateWithoutPriceTierInput = {
  id?: string
  code: string
  description?: string | null
  discountType: string
  discountValue: number
  minPurchase?: bigint | number | null
  maxDiscount?: bigint | number | null
  usageLimit?: number | null
  usageCount?: number
  perUserLimit?: number | null
  validFrom: Date | string
  validUntil: Date | string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PromoCodeCreateOrConnectWithoutPriceTierInput = {
  where: Prisma.PromoCodeWhereUniqueInput
  create: Prisma.XOR<Prisma.PromoCodeCreateWithoutPriceTierInput, Prisma.PromoCodeUncheckedCreateWithoutPriceTierInput>
}

export type PromoCodeCreateManyPriceTierInputEnvelope = {
  data: Prisma.PromoCodeCreateManyPriceTierInput | Prisma.PromoCodeCreateManyPriceTierInput[]
  skipDuplicates?: boolean
}

export type PromoCodeUpsertWithWhereUniqueWithoutPriceTierInput = {
  where: Prisma.PromoCodeWhereUniqueInput
  update: Prisma.XOR<Prisma.PromoCodeUpdateWithoutPriceTierInput, Prisma.PromoCodeUncheckedUpdateWithoutPriceTierInput>
  create: Prisma.XOR<Prisma.PromoCodeCreateWithoutPriceTierInput, Prisma.PromoCodeUncheckedCreateWithoutPriceTierInput>
}

export type PromoCodeUpdateWithWhereUniqueWithoutPriceTierInput = {
  where: Prisma.PromoCodeWhereUniqueInput
  data: Prisma.XOR<Prisma.PromoCodeUpdateWithoutPriceTierInput, Prisma.PromoCodeUncheckedUpdateWithoutPriceTierInput>
}

export type PromoCodeUpdateManyWithWhereWithoutPriceTierInput = {
  where: Prisma.PromoCodeScalarWhereInput
  data: Prisma.XOR<Prisma.PromoCodeUpdateManyMutationInput, Prisma.PromoCodeUncheckedUpdateManyWithoutPriceTierInput>
}

export type PromoCodeScalarWhereInput = {
  AND?: Prisma.PromoCodeScalarWhereInput | Prisma.PromoCodeScalarWhereInput[]
  OR?: Prisma.PromoCodeScalarWhereInput[]
  NOT?: Prisma.PromoCodeScalarWhereInput | Prisma.PromoCodeScalarWhereInput[]
  id?: Prisma.StringFilter<"PromoCode"> | string
  code?: Prisma.StringFilter<"PromoCode"> | string
  description?: Prisma.StringNullableFilter<"PromoCode"> | string | null
  discountType?: Prisma.StringFilter<"PromoCode"> | string
  discountValue?: Prisma.IntFilter<"PromoCode"> | number
  priceTierId?: Prisma.StringNullableFilter<"PromoCode"> | string | null
  minPurchase?: Prisma.BigIntNullableFilter<"PromoCode"> | bigint | number | null
  maxDiscount?: Prisma.BigIntNullableFilter<"PromoCode"> | bigint | number | null
  usageLimit?: Prisma.IntNullableFilter<"PromoCode"> | number | null
  usageCount?: Prisma.IntFilter<"PromoCode"> | number
  perUserLimit?: Prisma.IntNullableFilter<"PromoCode"> | number | null
  validFrom?: Prisma.DateTimeFilter<"PromoCode"> | Date | string
  validUntil?: Prisma.DateTimeFilter<"PromoCode"> | Date | string
  isActive?: Prisma.BoolFilter<"PromoCode"> | boolean
  createdAt?: Prisma.DateTimeFilter<"PromoCode"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PromoCode"> | Date | string
}

export type PromoCodeCreateManyPriceTierInput = {
  id?: string
  code: string
  description?: string | null
  discountType: string
  discountValue: number
  minPurchase?: bigint | number | null
  maxDiscount?: bigint | number | null
  usageLimit?: number | null
  usageCount?: number
  perUserLimit?: number | null
  validFrom: Date | string
  validUntil: Date | string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PromoCodeUpdateWithoutPriceTierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discountType?: Prisma.StringFieldUpdateOperationsInput | string
  discountValue?: Prisma.IntFieldUpdateOperationsInput | number
  minPurchase?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  maxDiscount?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  usageLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  usageCount?: Prisma.IntFieldUpdateOperationsInput | number
  perUserLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validUntil?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PromoCodeUncheckedUpdateWithoutPriceTierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discountType?: Prisma.StringFieldUpdateOperationsInput | string
  discountValue?: Prisma.IntFieldUpdateOperationsInput | number
  minPurchase?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  maxDiscount?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  usageLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  usageCount?: Prisma.IntFieldUpdateOperationsInput | number
  perUserLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validUntil?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PromoCodeUncheckedUpdateManyWithoutPriceTierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discountType?: Prisma.StringFieldUpdateOperationsInput | string
  discountValue?: Prisma.IntFieldUpdateOperationsInput | number
  minPurchase?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  maxDiscount?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  usageLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  usageCount?: Prisma.IntFieldUpdateOperationsInput | number
  perUserLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validUntil?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PromoCodeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  description?: boolean
  discountType?: boolean
  discountValue?: boolean
  priceTierId?: boolean
  minPurchase?: boolean
  maxDiscount?: boolean
  usageLimit?: boolean
  usageCount?: boolean
  perUserLimit?: boolean
  validFrom?: boolean
  validUntil?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  priceTier?: boolean | Prisma.PromoCode$priceTierArgs<ExtArgs>
}, ExtArgs["result"]["promoCode"]>

export type PromoCodeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  description?: boolean
  discountType?: boolean
  discountValue?: boolean
  priceTierId?: boolean
  minPurchase?: boolean
  maxDiscount?: boolean
  usageLimit?: boolean
  usageCount?: boolean
  perUserLimit?: boolean
  validFrom?: boolean
  validUntil?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  priceTier?: boolean | Prisma.PromoCode$priceTierArgs<ExtArgs>
}, ExtArgs["result"]["promoCode"]>

export type PromoCodeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  description?: boolean
  discountType?: boolean
  discountValue?: boolean
  priceTierId?: boolean
  minPurchase?: boolean
  maxDiscount?: boolean
  usageLimit?: boolean
  usageCount?: boolean
  perUserLimit?: boolean
  validFrom?: boolean
  validUntil?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  priceTier?: boolean | Prisma.PromoCode$priceTierArgs<ExtArgs>
}, ExtArgs["result"]["promoCode"]>

export type PromoCodeSelectScalar = {
  id?: boolean
  code?: boolean
  description?: boolean
  discountType?: boolean
  discountValue?: boolean
  priceTierId?: boolean
  minPurchase?: boolean
  maxDiscount?: boolean
  usageLimit?: boolean
  usageCount?: boolean
  perUserLimit?: boolean
  validFrom?: boolean
  validUntil?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PromoCodeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "code" | "description" | "discountType" | "discountValue" | "priceTierId" | "minPurchase" | "maxDiscount" | "usageLimit" | "usageCount" | "perUserLimit" | "validFrom" | "validUntil" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["promoCode"]>
export type PromoCodeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  priceTier?: boolean | Prisma.PromoCode$priceTierArgs<ExtArgs>
}
export type PromoCodeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  priceTier?: boolean | Prisma.PromoCode$priceTierArgs<ExtArgs>
}
export type PromoCodeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  priceTier?: boolean | Prisma.PromoCode$priceTierArgs<ExtArgs>
}

export type $PromoCodePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PromoCode"
  objects: {
    priceTier: Prisma.$PriceTierPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    code: string
    description: string | null
    discountType: string
    discountValue: number
    priceTierId: string | null
    minPurchase: bigint | null
    maxDiscount: bigint | null
    usageLimit: number | null
    usageCount: number
    perUserLimit: number | null
    validFrom: Date
    validUntil: Date
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["promoCode"]>
  composites: {}
}

export type PromoCodeGetPayload<S extends boolean | null | undefined | PromoCodeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PromoCodePayload, S>

export type PromoCodeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PromoCodeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PromoCodeCountAggregateInputType | true
  }

export interface PromoCodeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PromoCode'], meta: { name: 'PromoCode' } }
  /**
   * Find zero or one PromoCode that matches the filter.
   * @param {PromoCodeFindUniqueArgs} args - Arguments to find a PromoCode
   * @example
   * // Get one PromoCode
   * const promoCode = await prisma.promoCode.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PromoCodeFindUniqueArgs>(args: Prisma.SelectSubset<T, PromoCodeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PromoCodeClient<runtime.Types.Result.GetResult<Prisma.$PromoCodePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PromoCode that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PromoCodeFindUniqueOrThrowArgs} args - Arguments to find a PromoCode
   * @example
   * // Get one PromoCode
   * const promoCode = await prisma.promoCode.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PromoCodeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PromoCodeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PromoCodeClient<runtime.Types.Result.GetResult<Prisma.$PromoCodePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PromoCode that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromoCodeFindFirstArgs} args - Arguments to find a PromoCode
   * @example
   * // Get one PromoCode
   * const promoCode = await prisma.promoCode.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PromoCodeFindFirstArgs>(args?: Prisma.SelectSubset<T, PromoCodeFindFirstArgs<ExtArgs>>): Prisma.Prisma__PromoCodeClient<runtime.Types.Result.GetResult<Prisma.$PromoCodePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PromoCode that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromoCodeFindFirstOrThrowArgs} args - Arguments to find a PromoCode
   * @example
   * // Get one PromoCode
   * const promoCode = await prisma.promoCode.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PromoCodeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PromoCodeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PromoCodeClient<runtime.Types.Result.GetResult<Prisma.$PromoCodePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PromoCodes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromoCodeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PromoCodes
   * const promoCodes = await prisma.promoCode.findMany()
   * 
   * // Get first 10 PromoCodes
   * const promoCodes = await prisma.promoCode.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const promoCodeWithIdOnly = await prisma.promoCode.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PromoCodeFindManyArgs>(args?: Prisma.SelectSubset<T, PromoCodeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PromoCodePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PromoCode.
   * @param {PromoCodeCreateArgs} args - Arguments to create a PromoCode.
   * @example
   * // Create one PromoCode
   * const PromoCode = await prisma.promoCode.create({
   *   data: {
   *     // ... data to create a PromoCode
   *   }
   * })
   * 
   */
  create<T extends PromoCodeCreateArgs>(args: Prisma.SelectSubset<T, PromoCodeCreateArgs<ExtArgs>>): Prisma.Prisma__PromoCodeClient<runtime.Types.Result.GetResult<Prisma.$PromoCodePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PromoCodes.
   * @param {PromoCodeCreateManyArgs} args - Arguments to create many PromoCodes.
   * @example
   * // Create many PromoCodes
   * const promoCode = await prisma.promoCode.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PromoCodeCreateManyArgs>(args?: Prisma.SelectSubset<T, PromoCodeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PromoCodes and returns the data saved in the database.
   * @param {PromoCodeCreateManyAndReturnArgs} args - Arguments to create many PromoCodes.
   * @example
   * // Create many PromoCodes
   * const promoCode = await prisma.promoCode.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PromoCodes and only return the `id`
   * const promoCodeWithIdOnly = await prisma.promoCode.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PromoCodeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PromoCodeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PromoCodePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PromoCode.
   * @param {PromoCodeDeleteArgs} args - Arguments to delete one PromoCode.
   * @example
   * // Delete one PromoCode
   * const PromoCode = await prisma.promoCode.delete({
   *   where: {
   *     // ... filter to delete one PromoCode
   *   }
   * })
   * 
   */
  delete<T extends PromoCodeDeleteArgs>(args: Prisma.SelectSubset<T, PromoCodeDeleteArgs<ExtArgs>>): Prisma.Prisma__PromoCodeClient<runtime.Types.Result.GetResult<Prisma.$PromoCodePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PromoCode.
   * @param {PromoCodeUpdateArgs} args - Arguments to update one PromoCode.
   * @example
   * // Update one PromoCode
   * const promoCode = await prisma.promoCode.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PromoCodeUpdateArgs>(args: Prisma.SelectSubset<T, PromoCodeUpdateArgs<ExtArgs>>): Prisma.Prisma__PromoCodeClient<runtime.Types.Result.GetResult<Prisma.$PromoCodePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PromoCodes.
   * @param {PromoCodeDeleteManyArgs} args - Arguments to filter PromoCodes to delete.
   * @example
   * // Delete a few PromoCodes
   * const { count } = await prisma.promoCode.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PromoCodeDeleteManyArgs>(args?: Prisma.SelectSubset<T, PromoCodeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PromoCodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromoCodeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PromoCodes
   * const promoCode = await prisma.promoCode.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PromoCodeUpdateManyArgs>(args: Prisma.SelectSubset<T, PromoCodeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PromoCodes and returns the data updated in the database.
   * @param {PromoCodeUpdateManyAndReturnArgs} args - Arguments to update many PromoCodes.
   * @example
   * // Update many PromoCodes
   * const promoCode = await prisma.promoCode.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PromoCodes and only return the `id`
   * const promoCodeWithIdOnly = await prisma.promoCode.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PromoCodeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PromoCodeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PromoCodePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PromoCode.
   * @param {PromoCodeUpsertArgs} args - Arguments to update or create a PromoCode.
   * @example
   * // Update or create a PromoCode
   * const promoCode = await prisma.promoCode.upsert({
   *   create: {
   *     // ... data to create a PromoCode
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PromoCode we want to update
   *   }
   * })
   */
  upsert<T extends PromoCodeUpsertArgs>(args: Prisma.SelectSubset<T, PromoCodeUpsertArgs<ExtArgs>>): Prisma.Prisma__PromoCodeClient<runtime.Types.Result.GetResult<Prisma.$PromoCodePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PromoCodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromoCodeCountArgs} args - Arguments to filter PromoCodes to count.
   * @example
   * // Count the number of PromoCodes
   * const count = await prisma.promoCode.count({
   *   where: {
   *     // ... the filter for the PromoCodes we want to count
   *   }
   * })
  **/
  count<T extends PromoCodeCountArgs>(
    args?: Prisma.Subset<T, PromoCodeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PromoCodeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PromoCode.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromoCodeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PromoCodeAggregateArgs>(args: Prisma.Subset<T, PromoCodeAggregateArgs>): Prisma.PrismaPromise<GetPromoCodeAggregateType<T>>

  /**
   * Group by PromoCode.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromoCodeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PromoCodeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PromoCodeGroupByArgs['orderBy'] }
      : { orderBy?: PromoCodeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PromoCodeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPromoCodeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PromoCode model
 */
readonly fields: PromoCodeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PromoCode.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PromoCodeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  priceTier<T extends Prisma.PromoCode$priceTierArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PromoCode$priceTierArgs<ExtArgs>>): Prisma.Prisma__PriceTierClient<runtime.Types.Result.GetResult<Prisma.$PriceTierPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PromoCode model
 */
export interface PromoCodeFieldRefs {
  readonly id: Prisma.FieldRef<"PromoCode", 'String'>
  readonly code: Prisma.FieldRef<"PromoCode", 'String'>
  readonly description: Prisma.FieldRef<"PromoCode", 'String'>
  readonly discountType: Prisma.FieldRef<"PromoCode", 'String'>
  readonly discountValue: Prisma.FieldRef<"PromoCode", 'Int'>
  readonly priceTierId: Prisma.FieldRef<"PromoCode", 'String'>
  readonly minPurchase: Prisma.FieldRef<"PromoCode", 'BigInt'>
  readonly maxDiscount: Prisma.FieldRef<"PromoCode", 'BigInt'>
  readonly usageLimit: Prisma.FieldRef<"PromoCode", 'Int'>
  readonly usageCount: Prisma.FieldRef<"PromoCode", 'Int'>
  readonly perUserLimit: Prisma.FieldRef<"PromoCode", 'Int'>
  readonly validFrom: Prisma.FieldRef<"PromoCode", 'DateTime'>
  readonly validUntil: Prisma.FieldRef<"PromoCode", 'DateTime'>
  readonly isActive: Prisma.FieldRef<"PromoCode", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"PromoCode", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PromoCode", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PromoCode findUnique
 */
export type PromoCodeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoCode
   */
  select?: Prisma.PromoCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoCode
   */
  omit?: Prisma.PromoCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoCodeInclude<ExtArgs> | null
  /**
   * Filter, which PromoCode to fetch.
   */
  where: Prisma.PromoCodeWhereUniqueInput
}

/**
 * PromoCode findUniqueOrThrow
 */
export type PromoCodeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoCode
   */
  select?: Prisma.PromoCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoCode
   */
  omit?: Prisma.PromoCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoCodeInclude<ExtArgs> | null
  /**
   * Filter, which PromoCode to fetch.
   */
  where: Prisma.PromoCodeWhereUniqueInput
}

/**
 * PromoCode findFirst
 */
export type PromoCodeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoCode
   */
  select?: Prisma.PromoCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoCode
   */
  omit?: Prisma.PromoCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoCodeInclude<ExtArgs> | null
  /**
   * Filter, which PromoCode to fetch.
   */
  where?: Prisma.PromoCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PromoCodes to fetch.
   */
  orderBy?: Prisma.PromoCodeOrderByWithRelationInput | Prisma.PromoCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PromoCodes.
   */
  cursor?: Prisma.PromoCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PromoCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PromoCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PromoCodes.
   */
  distinct?: Prisma.PromoCodeScalarFieldEnum | Prisma.PromoCodeScalarFieldEnum[]
}

/**
 * PromoCode findFirstOrThrow
 */
export type PromoCodeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoCode
   */
  select?: Prisma.PromoCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoCode
   */
  omit?: Prisma.PromoCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoCodeInclude<ExtArgs> | null
  /**
   * Filter, which PromoCode to fetch.
   */
  where?: Prisma.PromoCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PromoCodes to fetch.
   */
  orderBy?: Prisma.PromoCodeOrderByWithRelationInput | Prisma.PromoCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PromoCodes.
   */
  cursor?: Prisma.PromoCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PromoCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PromoCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PromoCodes.
   */
  distinct?: Prisma.PromoCodeScalarFieldEnum | Prisma.PromoCodeScalarFieldEnum[]
}

/**
 * PromoCode findMany
 */
export type PromoCodeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoCode
   */
  select?: Prisma.PromoCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoCode
   */
  omit?: Prisma.PromoCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoCodeInclude<ExtArgs> | null
  /**
   * Filter, which PromoCodes to fetch.
   */
  where?: Prisma.PromoCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PromoCodes to fetch.
   */
  orderBy?: Prisma.PromoCodeOrderByWithRelationInput | Prisma.PromoCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PromoCodes.
   */
  cursor?: Prisma.PromoCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PromoCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PromoCodes.
   */
  skip?: number
  distinct?: Prisma.PromoCodeScalarFieldEnum | Prisma.PromoCodeScalarFieldEnum[]
}

/**
 * PromoCode create
 */
export type PromoCodeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoCode
   */
  select?: Prisma.PromoCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoCode
   */
  omit?: Prisma.PromoCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoCodeInclude<ExtArgs> | null
  /**
   * The data needed to create a PromoCode.
   */
  data: Prisma.XOR<Prisma.PromoCodeCreateInput, Prisma.PromoCodeUncheckedCreateInput>
}

/**
 * PromoCode createMany
 */
export type PromoCodeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PromoCodes.
   */
  data: Prisma.PromoCodeCreateManyInput | Prisma.PromoCodeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PromoCode createManyAndReturn
 */
export type PromoCodeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoCode
   */
  select?: Prisma.PromoCodeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PromoCode
   */
  omit?: Prisma.PromoCodeOmit<ExtArgs> | null
  /**
   * The data used to create many PromoCodes.
   */
  data: Prisma.PromoCodeCreateManyInput | Prisma.PromoCodeCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoCodeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PromoCode update
 */
export type PromoCodeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoCode
   */
  select?: Prisma.PromoCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoCode
   */
  omit?: Prisma.PromoCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoCodeInclude<ExtArgs> | null
  /**
   * The data needed to update a PromoCode.
   */
  data: Prisma.XOR<Prisma.PromoCodeUpdateInput, Prisma.PromoCodeUncheckedUpdateInput>
  /**
   * Choose, which PromoCode to update.
   */
  where: Prisma.PromoCodeWhereUniqueInput
}

/**
 * PromoCode updateMany
 */
export type PromoCodeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PromoCodes.
   */
  data: Prisma.XOR<Prisma.PromoCodeUpdateManyMutationInput, Prisma.PromoCodeUncheckedUpdateManyInput>
  /**
   * Filter which PromoCodes to update
   */
  where?: Prisma.PromoCodeWhereInput
  /**
   * Limit how many PromoCodes to update.
   */
  limit?: number
}

/**
 * PromoCode updateManyAndReturn
 */
export type PromoCodeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoCode
   */
  select?: Prisma.PromoCodeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PromoCode
   */
  omit?: Prisma.PromoCodeOmit<ExtArgs> | null
  /**
   * The data used to update PromoCodes.
   */
  data: Prisma.XOR<Prisma.PromoCodeUpdateManyMutationInput, Prisma.PromoCodeUncheckedUpdateManyInput>
  /**
   * Filter which PromoCodes to update
   */
  where?: Prisma.PromoCodeWhereInput
  /**
   * Limit how many PromoCodes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoCodeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PromoCode upsert
 */
export type PromoCodeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoCode
   */
  select?: Prisma.PromoCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoCode
   */
  omit?: Prisma.PromoCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoCodeInclude<ExtArgs> | null
  /**
   * The filter to search for the PromoCode to update in case it exists.
   */
  where: Prisma.PromoCodeWhereUniqueInput
  /**
   * In case the PromoCode found by the `where` argument doesn't exist, create a new PromoCode with this data.
   */
  create: Prisma.XOR<Prisma.PromoCodeCreateInput, Prisma.PromoCodeUncheckedCreateInput>
  /**
   * In case the PromoCode was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PromoCodeUpdateInput, Prisma.PromoCodeUncheckedUpdateInput>
}

/**
 * PromoCode delete
 */
export type PromoCodeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoCode
   */
  select?: Prisma.PromoCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoCode
   */
  omit?: Prisma.PromoCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoCodeInclude<ExtArgs> | null
  /**
   * Filter which PromoCode to delete.
   */
  where: Prisma.PromoCodeWhereUniqueInput
}

/**
 * PromoCode deleteMany
 */
export type PromoCodeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PromoCodes to delete
   */
  where?: Prisma.PromoCodeWhereInput
  /**
   * Limit how many PromoCodes to delete.
   */
  limit?: number
}

/**
 * PromoCode.priceTier
 */
export type PromoCode$priceTierArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceTier
   */
  select?: Prisma.PriceTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceTier
   */
  omit?: Prisma.PriceTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceTierInclude<ExtArgs> | null
  where?: Prisma.PriceTierWhereInput
}

/**
 * PromoCode without action
 */
export type PromoCodeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoCode
   */
  select?: Prisma.PromoCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoCode
   */
  omit?: Prisma.PromoCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoCodeInclude<ExtArgs> | null
}
