
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SeatLock` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SeatLock
 * 
 */
export type SeatLockModel = runtime.Types.Result.DefaultSelection<Prisma.$SeatLockPayload>

export type AggregateSeatLock = {
  _count: SeatLockCountAggregateOutputType | null
  _min: SeatLockMinAggregateOutputType | null
  _max: SeatLockMaxAggregateOutputType | null
}

export type SeatLockMinAggregateOutputType = {
  id: string | null
  tripScheduleId: string | null
  tripSeatId: string | null
  bookingId: string | null
  lockedById: string | null
  lockedAt: Date | null
  expiresAt: Date | null
}

export type SeatLockMaxAggregateOutputType = {
  id: string | null
  tripScheduleId: string | null
  tripSeatId: string | null
  bookingId: string | null
  lockedById: string | null
  lockedAt: Date | null
  expiresAt: Date | null
}

export type SeatLockCountAggregateOutputType = {
  id: number
  tripScheduleId: number
  tripSeatId: number
  bookingId: number
  lockedById: number
  lockedAt: number
  expiresAt: number
  _all: number
}


export type SeatLockMinAggregateInputType = {
  id?: true
  tripScheduleId?: true
  tripSeatId?: true
  bookingId?: true
  lockedById?: true
  lockedAt?: true
  expiresAt?: true
}

export type SeatLockMaxAggregateInputType = {
  id?: true
  tripScheduleId?: true
  tripSeatId?: true
  bookingId?: true
  lockedById?: true
  lockedAt?: true
  expiresAt?: true
}

export type SeatLockCountAggregateInputType = {
  id?: true
  tripScheduleId?: true
  tripSeatId?: true
  bookingId?: true
  lockedById?: true
  lockedAt?: true
  expiresAt?: true
  _all?: true
}

export type SeatLockAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SeatLock to aggregate.
   */
  where?: Prisma.SeatLockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SeatLocks to fetch.
   */
  orderBy?: Prisma.SeatLockOrderByWithRelationInput | Prisma.SeatLockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SeatLockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SeatLocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SeatLocks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SeatLocks
  **/
  _count?: true | SeatLockCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SeatLockMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SeatLockMaxAggregateInputType
}

export type GetSeatLockAggregateType<T extends SeatLockAggregateArgs> = {
      [P in keyof T & keyof AggregateSeatLock]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSeatLock[P]>
    : Prisma.GetScalarType<T[P], AggregateSeatLock[P]>
}




export type SeatLockGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SeatLockWhereInput
  orderBy?: Prisma.SeatLockOrderByWithAggregationInput | Prisma.SeatLockOrderByWithAggregationInput[]
  by: Prisma.SeatLockScalarFieldEnum[] | Prisma.SeatLockScalarFieldEnum
  having?: Prisma.SeatLockScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SeatLockCountAggregateInputType | true
  _min?: SeatLockMinAggregateInputType
  _max?: SeatLockMaxAggregateInputType
}

export type SeatLockGroupByOutputType = {
  id: string
  tripScheduleId: string
  tripSeatId: string | null
  bookingId: string | null
  lockedById: string | null
  lockedAt: Date
  expiresAt: Date
  _count: SeatLockCountAggregateOutputType | null
  _min: SeatLockMinAggregateOutputType | null
  _max: SeatLockMaxAggregateOutputType | null
}

type GetSeatLockGroupByPayload<T extends SeatLockGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SeatLockGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SeatLockGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SeatLockGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SeatLockGroupByOutputType[P]>
      }
    >
  >



export type SeatLockWhereInput = {
  AND?: Prisma.SeatLockWhereInput | Prisma.SeatLockWhereInput[]
  OR?: Prisma.SeatLockWhereInput[]
  NOT?: Prisma.SeatLockWhereInput | Prisma.SeatLockWhereInput[]
  id?: Prisma.StringFilter<"SeatLock"> | string
  tripScheduleId?: Prisma.StringFilter<"SeatLock"> | string
  tripSeatId?: Prisma.StringNullableFilter<"SeatLock"> | string | null
  bookingId?: Prisma.StringNullableFilter<"SeatLock"> | string | null
  lockedById?: Prisma.UuidNullableFilter<"SeatLock"> | string | null
  lockedAt?: Prisma.DateTimeFilter<"SeatLock"> | Date | string
  expiresAt?: Prisma.DateTimeFilter<"SeatLock"> | Date | string
  tripSchedule?: Prisma.XOR<Prisma.TripScheduleScalarRelationFilter, Prisma.TripScheduleWhereInput>
  tripSeat?: Prisma.XOR<Prisma.TripSeatNullableScalarRelationFilter, Prisma.TripSeatWhereInput> | null
  booking?: Prisma.XOR<Prisma.BookingNullableScalarRelationFilter, Prisma.BookingWhereInput> | null
  lockedBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type SeatLockOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tripScheduleId?: Prisma.SortOrder
  tripSeatId?: Prisma.SortOrderInput | Prisma.SortOrder
  bookingId?: Prisma.SortOrderInput | Prisma.SortOrder
  lockedById?: Prisma.SortOrderInput | Prisma.SortOrder
  lockedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  tripSchedule?: Prisma.TripScheduleOrderByWithRelationInput
  tripSeat?: Prisma.TripSeatOrderByWithRelationInput
  booking?: Prisma.BookingOrderByWithRelationInput
  lockedBy?: Prisma.UserOrderByWithRelationInput
}

export type SeatLockWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  tripScheduleId_tripSeatId?: Prisma.SeatLockTripScheduleIdTripSeatIdCompoundUniqueInput
  AND?: Prisma.SeatLockWhereInput | Prisma.SeatLockWhereInput[]
  OR?: Prisma.SeatLockWhereInput[]
  NOT?: Prisma.SeatLockWhereInput | Prisma.SeatLockWhereInput[]
  tripScheduleId?: Prisma.StringFilter<"SeatLock"> | string
  tripSeatId?: Prisma.StringNullableFilter<"SeatLock"> | string | null
  bookingId?: Prisma.StringNullableFilter<"SeatLock"> | string | null
  lockedById?: Prisma.UuidNullableFilter<"SeatLock"> | string | null
  lockedAt?: Prisma.DateTimeFilter<"SeatLock"> | Date | string
  expiresAt?: Prisma.DateTimeFilter<"SeatLock"> | Date | string
  tripSchedule?: Prisma.XOR<Prisma.TripScheduleScalarRelationFilter, Prisma.TripScheduleWhereInput>
  tripSeat?: Prisma.XOR<Prisma.TripSeatNullableScalarRelationFilter, Prisma.TripSeatWhereInput> | null
  booking?: Prisma.XOR<Prisma.BookingNullableScalarRelationFilter, Prisma.BookingWhereInput> | null
  lockedBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id" | "tripScheduleId_tripSeatId">

export type SeatLockOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tripScheduleId?: Prisma.SortOrder
  tripSeatId?: Prisma.SortOrderInput | Prisma.SortOrder
  bookingId?: Prisma.SortOrderInput | Prisma.SortOrder
  lockedById?: Prisma.SortOrderInput | Prisma.SortOrder
  lockedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  _count?: Prisma.SeatLockCountOrderByAggregateInput
  _max?: Prisma.SeatLockMaxOrderByAggregateInput
  _min?: Prisma.SeatLockMinOrderByAggregateInput
}

export type SeatLockScalarWhereWithAggregatesInput = {
  AND?: Prisma.SeatLockScalarWhereWithAggregatesInput | Prisma.SeatLockScalarWhereWithAggregatesInput[]
  OR?: Prisma.SeatLockScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SeatLockScalarWhereWithAggregatesInput | Prisma.SeatLockScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SeatLock"> | string
  tripScheduleId?: Prisma.StringWithAggregatesFilter<"SeatLock"> | string
  tripSeatId?: Prisma.StringNullableWithAggregatesFilter<"SeatLock"> | string | null
  bookingId?: Prisma.StringNullableWithAggregatesFilter<"SeatLock"> | string | null
  lockedById?: Prisma.UuidNullableWithAggregatesFilter<"SeatLock"> | string | null
  lockedAt?: Prisma.DateTimeWithAggregatesFilter<"SeatLock"> | Date | string
  expiresAt?: Prisma.DateTimeWithAggregatesFilter<"SeatLock"> | Date | string
}

export type SeatLockCreateInput = {
  id?: string
  lockedAt?: Date | string
  expiresAt: Date | string
  tripSchedule: Prisma.TripScheduleCreateNestedOneWithoutSeatLocksInput
  tripSeat?: Prisma.TripSeatCreateNestedOneWithoutSeatLocksInput
  booking?: Prisma.BookingCreateNestedOneWithoutSeatLocksInput
  lockedBy?: Prisma.UserCreateNestedOneWithoutSeatLocksInput
}

export type SeatLockUncheckedCreateInput = {
  id?: string
  tripScheduleId: string
  tripSeatId?: string | null
  bookingId?: string | null
  lockedById?: string | null
  lockedAt?: Date | string
  expiresAt: Date | string
}

export type SeatLockUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tripSchedule?: Prisma.TripScheduleUpdateOneRequiredWithoutSeatLocksNestedInput
  tripSeat?: Prisma.TripSeatUpdateOneWithoutSeatLocksNestedInput
  booking?: Prisma.BookingUpdateOneWithoutSeatLocksNestedInput
  lockedBy?: Prisma.UserUpdateOneWithoutSeatLocksNestedInput
}

export type SeatLockUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tripScheduleId?: Prisma.StringFieldUpdateOperationsInput | string
  tripSeatId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookingId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SeatLockCreateManyInput = {
  id?: string
  tripScheduleId: string
  tripSeatId?: string | null
  bookingId?: string | null
  lockedById?: string | null
  lockedAt?: Date | string
  expiresAt: Date | string
}

export type SeatLockUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SeatLockUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tripScheduleId?: Prisma.StringFieldUpdateOperationsInput | string
  tripSeatId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookingId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SeatLockListRelationFilter = {
  every?: Prisma.SeatLockWhereInput
  some?: Prisma.SeatLockWhereInput
  none?: Prisma.SeatLockWhereInput
}

export type SeatLockOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SeatLockTripScheduleIdTripSeatIdCompoundUniqueInput = {
  tripScheduleId: string
  tripSeatId: string
}

export type SeatLockCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tripScheduleId?: Prisma.SortOrder
  tripSeatId?: Prisma.SortOrder
  bookingId?: Prisma.SortOrder
  lockedById?: Prisma.SortOrder
  lockedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type SeatLockMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tripScheduleId?: Prisma.SortOrder
  tripSeatId?: Prisma.SortOrder
  bookingId?: Prisma.SortOrder
  lockedById?: Prisma.SortOrder
  lockedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type SeatLockMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tripScheduleId?: Prisma.SortOrder
  tripSeatId?: Prisma.SortOrder
  bookingId?: Prisma.SortOrder
  lockedById?: Prisma.SortOrder
  lockedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type SeatLockCreateNestedManyWithoutLockedByInput = {
  create?: Prisma.XOR<Prisma.SeatLockCreateWithoutLockedByInput, Prisma.SeatLockUncheckedCreateWithoutLockedByInput> | Prisma.SeatLockCreateWithoutLockedByInput[] | Prisma.SeatLockUncheckedCreateWithoutLockedByInput[]
  connectOrCreate?: Prisma.SeatLockCreateOrConnectWithoutLockedByInput | Prisma.SeatLockCreateOrConnectWithoutLockedByInput[]
  createMany?: Prisma.SeatLockCreateManyLockedByInputEnvelope
  connect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
}

export type SeatLockUncheckedCreateNestedManyWithoutLockedByInput = {
  create?: Prisma.XOR<Prisma.SeatLockCreateWithoutLockedByInput, Prisma.SeatLockUncheckedCreateWithoutLockedByInput> | Prisma.SeatLockCreateWithoutLockedByInput[] | Prisma.SeatLockUncheckedCreateWithoutLockedByInput[]
  connectOrCreate?: Prisma.SeatLockCreateOrConnectWithoutLockedByInput | Prisma.SeatLockCreateOrConnectWithoutLockedByInput[]
  createMany?: Prisma.SeatLockCreateManyLockedByInputEnvelope
  connect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
}

export type SeatLockUpdateManyWithoutLockedByNestedInput = {
  create?: Prisma.XOR<Prisma.SeatLockCreateWithoutLockedByInput, Prisma.SeatLockUncheckedCreateWithoutLockedByInput> | Prisma.SeatLockCreateWithoutLockedByInput[] | Prisma.SeatLockUncheckedCreateWithoutLockedByInput[]
  connectOrCreate?: Prisma.SeatLockCreateOrConnectWithoutLockedByInput | Prisma.SeatLockCreateOrConnectWithoutLockedByInput[]
  upsert?: Prisma.SeatLockUpsertWithWhereUniqueWithoutLockedByInput | Prisma.SeatLockUpsertWithWhereUniqueWithoutLockedByInput[]
  createMany?: Prisma.SeatLockCreateManyLockedByInputEnvelope
  set?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  disconnect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  delete?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  connect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  update?: Prisma.SeatLockUpdateWithWhereUniqueWithoutLockedByInput | Prisma.SeatLockUpdateWithWhereUniqueWithoutLockedByInput[]
  updateMany?: Prisma.SeatLockUpdateManyWithWhereWithoutLockedByInput | Prisma.SeatLockUpdateManyWithWhereWithoutLockedByInput[]
  deleteMany?: Prisma.SeatLockScalarWhereInput | Prisma.SeatLockScalarWhereInput[]
}

export type SeatLockUncheckedUpdateManyWithoutLockedByNestedInput = {
  create?: Prisma.XOR<Prisma.SeatLockCreateWithoutLockedByInput, Prisma.SeatLockUncheckedCreateWithoutLockedByInput> | Prisma.SeatLockCreateWithoutLockedByInput[] | Prisma.SeatLockUncheckedCreateWithoutLockedByInput[]
  connectOrCreate?: Prisma.SeatLockCreateOrConnectWithoutLockedByInput | Prisma.SeatLockCreateOrConnectWithoutLockedByInput[]
  upsert?: Prisma.SeatLockUpsertWithWhereUniqueWithoutLockedByInput | Prisma.SeatLockUpsertWithWhereUniqueWithoutLockedByInput[]
  createMany?: Prisma.SeatLockCreateManyLockedByInputEnvelope
  set?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  disconnect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  delete?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  connect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  update?: Prisma.SeatLockUpdateWithWhereUniqueWithoutLockedByInput | Prisma.SeatLockUpdateWithWhereUniqueWithoutLockedByInput[]
  updateMany?: Prisma.SeatLockUpdateManyWithWhereWithoutLockedByInput | Prisma.SeatLockUpdateManyWithWhereWithoutLockedByInput[]
  deleteMany?: Prisma.SeatLockScalarWhereInput | Prisma.SeatLockScalarWhereInput[]
}

export type SeatLockCreateNestedManyWithoutTripScheduleInput = {
  create?: Prisma.XOR<Prisma.SeatLockCreateWithoutTripScheduleInput, Prisma.SeatLockUncheckedCreateWithoutTripScheduleInput> | Prisma.SeatLockCreateWithoutTripScheduleInput[] | Prisma.SeatLockUncheckedCreateWithoutTripScheduleInput[]
  connectOrCreate?: Prisma.SeatLockCreateOrConnectWithoutTripScheduleInput | Prisma.SeatLockCreateOrConnectWithoutTripScheduleInput[]
  createMany?: Prisma.SeatLockCreateManyTripScheduleInputEnvelope
  connect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
}

export type SeatLockUncheckedCreateNestedManyWithoutTripScheduleInput = {
  create?: Prisma.XOR<Prisma.SeatLockCreateWithoutTripScheduleInput, Prisma.SeatLockUncheckedCreateWithoutTripScheduleInput> | Prisma.SeatLockCreateWithoutTripScheduleInput[] | Prisma.SeatLockUncheckedCreateWithoutTripScheduleInput[]
  connectOrCreate?: Prisma.SeatLockCreateOrConnectWithoutTripScheduleInput | Prisma.SeatLockCreateOrConnectWithoutTripScheduleInput[]
  createMany?: Prisma.SeatLockCreateManyTripScheduleInputEnvelope
  connect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
}

export type SeatLockUpdateManyWithoutTripScheduleNestedInput = {
  create?: Prisma.XOR<Prisma.SeatLockCreateWithoutTripScheduleInput, Prisma.SeatLockUncheckedCreateWithoutTripScheduleInput> | Prisma.SeatLockCreateWithoutTripScheduleInput[] | Prisma.SeatLockUncheckedCreateWithoutTripScheduleInput[]
  connectOrCreate?: Prisma.SeatLockCreateOrConnectWithoutTripScheduleInput | Prisma.SeatLockCreateOrConnectWithoutTripScheduleInput[]
  upsert?: Prisma.SeatLockUpsertWithWhereUniqueWithoutTripScheduleInput | Prisma.SeatLockUpsertWithWhereUniqueWithoutTripScheduleInput[]
  createMany?: Prisma.SeatLockCreateManyTripScheduleInputEnvelope
  set?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  disconnect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  delete?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  connect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  update?: Prisma.SeatLockUpdateWithWhereUniqueWithoutTripScheduleInput | Prisma.SeatLockUpdateWithWhereUniqueWithoutTripScheduleInput[]
  updateMany?: Prisma.SeatLockUpdateManyWithWhereWithoutTripScheduleInput | Prisma.SeatLockUpdateManyWithWhereWithoutTripScheduleInput[]
  deleteMany?: Prisma.SeatLockScalarWhereInput | Prisma.SeatLockScalarWhereInput[]
}

export type SeatLockUncheckedUpdateManyWithoutTripScheduleNestedInput = {
  create?: Prisma.XOR<Prisma.SeatLockCreateWithoutTripScheduleInput, Prisma.SeatLockUncheckedCreateWithoutTripScheduleInput> | Prisma.SeatLockCreateWithoutTripScheduleInput[] | Prisma.SeatLockUncheckedCreateWithoutTripScheduleInput[]
  connectOrCreate?: Prisma.SeatLockCreateOrConnectWithoutTripScheduleInput | Prisma.SeatLockCreateOrConnectWithoutTripScheduleInput[]
  upsert?: Prisma.SeatLockUpsertWithWhereUniqueWithoutTripScheduleInput | Prisma.SeatLockUpsertWithWhereUniqueWithoutTripScheduleInput[]
  createMany?: Prisma.SeatLockCreateManyTripScheduleInputEnvelope
  set?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  disconnect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  delete?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  connect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  update?: Prisma.SeatLockUpdateWithWhereUniqueWithoutTripScheduleInput | Prisma.SeatLockUpdateWithWhereUniqueWithoutTripScheduleInput[]
  updateMany?: Prisma.SeatLockUpdateManyWithWhereWithoutTripScheduleInput | Prisma.SeatLockUpdateManyWithWhereWithoutTripScheduleInput[]
  deleteMany?: Prisma.SeatLockScalarWhereInput | Prisma.SeatLockScalarWhereInput[]
}

export type SeatLockCreateNestedManyWithoutTripSeatInput = {
  create?: Prisma.XOR<Prisma.SeatLockCreateWithoutTripSeatInput, Prisma.SeatLockUncheckedCreateWithoutTripSeatInput> | Prisma.SeatLockCreateWithoutTripSeatInput[] | Prisma.SeatLockUncheckedCreateWithoutTripSeatInput[]
  connectOrCreate?: Prisma.SeatLockCreateOrConnectWithoutTripSeatInput | Prisma.SeatLockCreateOrConnectWithoutTripSeatInput[]
  createMany?: Prisma.SeatLockCreateManyTripSeatInputEnvelope
  connect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
}

export type SeatLockUncheckedCreateNestedManyWithoutTripSeatInput = {
  create?: Prisma.XOR<Prisma.SeatLockCreateWithoutTripSeatInput, Prisma.SeatLockUncheckedCreateWithoutTripSeatInput> | Prisma.SeatLockCreateWithoutTripSeatInput[] | Prisma.SeatLockUncheckedCreateWithoutTripSeatInput[]
  connectOrCreate?: Prisma.SeatLockCreateOrConnectWithoutTripSeatInput | Prisma.SeatLockCreateOrConnectWithoutTripSeatInput[]
  createMany?: Prisma.SeatLockCreateManyTripSeatInputEnvelope
  connect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
}

export type SeatLockUpdateManyWithoutTripSeatNestedInput = {
  create?: Prisma.XOR<Prisma.SeatLockCreateWithoutTripSeatInput, Prisma.SeatLockUncheckedCreateWithoutTripSeatInput> | Prisma.SeatLockCreateWithoutTripSeatInput[] | Prisma.SeatLockUncheckedCreateWithoutTripSeatInput[]
  connectOrCreate?: Prisma.SeatLockCreateOrConnectWithoutTripSeatInput | Prisma.SeatLockCreateOrConnectWithoutTripSeatInput[]
  upsert?: Prisma.SeatLockUpsertWithWhereUniqueWithoutTripSeatInput | Prisma.SeatLockUpsertWithWhereUniqueWithoutTripSeatInput[]
  createMany?: Prisma.SeatLockCreateManyTripSeatInputEnvelope
  set?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  disconnect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  delete?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  connect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  update?: Prisma.SeatLockUpdateWithWhereUniqueWithoutTripSeatInput | Prisma.SeatLockUpdateWithWhereUniqueWithoutTripSeatInput[]
  updateMany?: Prisma.SeatLockUpdateManyWithWhereWithoutTripSeatInput | Prisma.SeatLockUpdateManyWithWhereWithoutTripSeatInput[]
  deleteMany?: Prisma.SeatLockScalarWhereInput | Prisma.SeatLockScalarWhereInput[]
}

export type SeatLockUncheckedUpdateManyWithoutTripSeatNestedInput = {
  create?: Prisma.XOR<Prisma.SeatLockCreateWithoutTripSeatInput, Prisma.SeatLockUncheckedCreateWithoutTripSeatInput> | Prisma.SeatLockCreateWithoutTripSeatInput[] | Prisma.SeatLockUncheckedCreateWithoutTripSeatInput[]
  connectOrCreate?: Prisma.SeatLockCreateOrConnectWithoutTripSeatInput | Prisma.SeatLockCreateOrConnectWithoutTripSeatInput[]
  upsert?: Prisma.SeatLockUpsertWithWhereUniqueWithoutTripSeatInput | Prisma.SeatLockUpsertWithWhereUniqueWithoutTripSeatInput[]
  createMany?: Prisma.SeatLockCreateManyTripSeatInputEnvelope
  set?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  disconnect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  delete?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  connect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  update?: Prisma.SeatLockUpdateWithWhereUniqueWithoutTripSeatInput | Prisma.SeatLockUpdateWithWhereUniqueWithoutTripSeatInput[]
  updateMany?: Prisma.SeatLockUpdateManyWithWhereWithoutTripSeatInput | Prisma.SeatLockUpdateManyWithWhereWithoutTripSeatInput[]
  deleteMany?: Prisma.SeatLockScalarWhereInput | Prisma.SeatLockScalarWhereInput[]
}

export type SeatLockCreateNestedManyWithoutBookingInput = {
  create?: Prisma.XOR<Prisma.SeatLockCreateWithoutBookingInput, Prisma.SeatLockUncheckedCreateWithoutBookingInput> | Prisma.SeatLockCreateWithoutBookingInput[] | Prisma.SeatLockUncheckedCreateWithoutBookingInput[]
  connectOrCreate?: Prisma.SeatLockCreateOrConnectWithoutBookingInput | Prisma.SeatLockCreateOrConnectWithoutBookingInput[]
  createMany?: Prisma.SeatLockCreateManyBookingInputEnvelope
  connect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
}

export type SeatLockUncheckedCreateNestedManyWithoutBookingInput = {
  create?: Prisma.XOR<Prisma.SeatLockCreateWithoutBookingInput, Prisma.SeatLockUncheckedCreateWithoutBookingInput> | Prisma.SeatLockCreateWithoutBookingInput[] | Prisma.SeatLockUncheckedCreateWithoutBookingInput[]
  connectOrCreate?: Prisma.SeatLockCreateOrConnectWithoutBookingInput | Prisma.SeatLockCreateOrConnectWithoutBookingInput[]
  createMany?: Prisma.SeatLockCreateManyBookingInputEnvelope
  connect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
}

export type SeatLockUpdateManyWithoutBookingNestedInput = {
  create?: Prisma.XOR<Prisma.SeatLockCreateWithoutBookingInput, Prisma.SeatLockUncheckedCreateWithoutBookingInput> | Prisma.SeatLockCreateWithoutBookingInput[] | Prisma.SeatLockUncheckedCreateWithoutBookingInput[]
  connectOrCreate?: Prisma.SeatLockCreateOrConnectWithoutBookingInput | Prisma.SeatLockCreateOrConnectWithoutBookingInput[]
  upsert?: Prisma.SeatLockUpsertWithWhereUniqueWithoutBookingInput | Prisma.SeatLockUpsertWithWhereUniqueWithoutBookingInput[]
  createMany?: Prisma.SeatLockCreateManyBookingInputEnvelope
  set?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  disconnect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  delete?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  connect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  update?: Prisma.SeatLockUpdateWithWhereUniqueWithoutBookingInput | Prisma.SeatLockUpdateWithWhereUniqueWithoutBookingInput[]
  updateMany?: Prisma.SeatLockUpdateManyWithWhereWithoutBookingInput | Prisma.SeatLockUpdateManyWithWhereWithoutBookingInput[]
  deleteMany?: Prisma.SeatLockScalarWhereInput | Prisma.SeatLockScalarWhereInput[]
}

export type SeatLockUncheckedUpdateManyWithoutBookingNestedInput = {
  create?: Prisma.XOR<Prisma.SeatLockCreateWithoutBookingInput, Prisma.SeatLockUncheckedCreateWithoutBookingInput> | Prisma.SeatLockCreateWithoutBookingInput[] | Prisma.SeatLockUncheckedCreateWithoutBookingInput[]
  connectOrCreate?: Prisma.SeatLockCreateOrConnectWithoutBookingInput | Prisma.SeatLockCreateOrConnectWithoutBookingInput[]
  upsert?: Prisma.SeatLockUpsertWithWhereUniqueWithoutBookingInput | Prisma.SeatLockUpsertWithWhereUniqueWithoutBookingInput[]
  createMany?: Prisma.SeatLockCreateManyBookingInputEnvelope
  set?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  disconnect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  delete?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  connect?: Prisma.SeatLockWhereUniqueInput | Prisma.SeatLockWhereUniqueInput[]
  update?: Prisma.SeatLockUpdateWithWhereUniqueWithoutBookingInput | Prisma.SeatLockUpdateWithWhereUniqueWithoutBookingInput[]
  updateMany?: Prisma.SeatLockUpdateManyWithWhereWithoutBookingInput | Prisma.SeatLockUpdateManyWithWhereWithoutBookingInput[]
  deleteMany?: Prisma.SeatLockScalarWhereInput | Prisma.SeatLockScalarWhereInput[]
}

export type SeatLockCreateWithoutLockedByInput = {
  id?: string
  lockedAt?: Date | string
  expiresAt: Date | string
  tripSchedule: Prisma.TripScheduleCreateNestedOneWithoutSeatLocksInput
  tripSeat?: Prisma.TripSeatCreateNestedOneWithoutSeatLocksInput
  booking?: Prisma.BookingCreateNestedOneWithoutSeatLocksInput
}

export type SeatLockUncheckedCreateWithoutLockedByInput = {
  id?: string
  tripScheduleId: string
  tripSeatId?: string | null
  bookingId?: string | null
  lockedAt?: Date | string
  expiresAt: Date | string
}

export type SeatLockCreateOrConnectWithoutLockedByInput = {
  where: Prisma.SeatLockWhereUniqueInput
  create: Prisma.XOR<Prisma.SeatLockCreateWithoutLockedByInput, Prisma.SeatLockUncheckedCreateWithoutLockedByInput>
}

export type SeatLockCreateManyLockedByInputEnvelope = {
  data: Prisma.SeatLockCreateManyLockedByInput | Prisma.SeatLockCreateManyLockedByInput[]
  skipDuplicates?: boolean
}

export type SeatLockUpsertWithWhereUniqueWithoutLockedByInput = {
  where: Prisma.SeatLockWhereUniqueInput
  update: Prisma.XOR<Prisma.SeatLockUpdateWithoutLockedByInput, Prisma.SeatLockUncheckedUpdateWithoutLockedByInput>
  create: Prisma.XOR<Prisma.SeatLockCreateWithoutLockedByInput, Prisma.SeatLockUncheckedCreateWithoutLockedByInput>
}

export type SeatLockUpdateWithWhereUniqueWithoutLockedByInput = {
  where: Prisma.SeatLockWhereUniqueInput
  data: Prisma.XOR<Prisma.SeatLockUpdateWithoutLockedByInput, Prisma.SeatLockUncheckedUpdateWithoutLockedByInput>
}

export type SeatLockUpdateManyWithWhereWithoutLockedByInput = {
  where: Prisma.SeatLockScalarWhereInput
  data: Prisma.XOR<Prisma.SeatLockUpdateManyMutationInput, Prisma.SeatLockUncheckedUpdateManyWithoutLockedByInput>
}

export type SeatLockScalarWhereInput = {
  AND?: Prisma.SeatLockScalarWhereInput | Prisma.SeatLockScalarWhereInput[]
  OR?: Prisma.SeatLockScalarWhereInput[]
  NOT?: Prisma.SeatLockScalarWhereInput | Prisma.SeatLockScalarWhereInput[]
  id?: Prisma.StringFilter<"SeatLock"> | string
  tripScheduleId?: Prisma.StringFilter<"SeatLock"> | string
  tripSeatId?: Prisma.StringNullableFilter<"SeatLock"> | string | null
  bookingId?: Prisma.StringNullableFilter<"SeatLock"> | string | null
  lockedById?: Prisma.UuidNullableFilter<"SeatLock"> | string | null
  lockedAt?: Prisma.DateTimeFilter<"SeatLock"> | Date | string
  expiresAt?: Prisma.DateTimeFilter<"SeatLock"> | Date | string
}

export type SeatLockCreateWithoutTripScheduleInput = {
  id?: string
  lockedAt?: Date | string
  expiresAt: Date | string
  tripSeat?: Prisma.TripSeatCreateNestedOneWithoutSeatLocksInput
  booking?: Prisma.BookingCreateNestedOneWithoutSeatLocksInput
  lockedBy?: Prisma.UserCreateNestedOneWithoutSeatLocksInput
}

export type SeatLockUncheckedCreateWithoutTripScheduleInput = {
  id?: string
  tripSeatId?: string | null
  bookingId?: string | null
  lockedById?: string | null
  lockedAt?: Date | string
  expiresAt: Date | string
}

export type SeatLockCreateOrConnectWithoutTripScheduleInput = {
  where: Prisma.SeatLockWhereUniqueInput
  create: Prisma.XOR<Prisma.SeatLockCreateWithoutTripScheduleInput, Prisma.SeatLockUncheckedCreateWithoutTripScheduleInput>
}

export type SeatLockCreateManyTripScheduleInputEnvelope = {
  data: Prisma.SeatLockCreateManyTripScheduleInput | Prisma.SeatLockCreateManyTripScheduleInput[]
  skipDuplicates?: boolean
}

export type SeatLockUpsertWithWhereUniqueWithoutTripScheduleInput = {
  where: Prisma.SeatLockWhereUniqueInput
  update: Prisma.XOR<Prisma.SeatLockUpdateWithoutTripScheduleInput, Prisma.SeatLockUncheckedUpdateWithoutTripScheduleInput>
  create: Prisma.XOR<Prisma.SeatLockCreateWithoutTripScheduleInput, Prisma.SeatLockUncheckedCreateWithoutTripScheduleInput>
}

export type SeatLockUpdateWithWhereUniqueWithoutTripScheduleInput = {
  where: Prisma.SeatLockWhereUniqueInput
  data: Prisma.XOR<Prisma.SeatLockUpdateWithoutTripScheduleInput, Prisma.SeatLockUncheckedUpdateWithoutTripScheduleInput>
}

export type SeatLockUpdateManyWithWhereWithoutTripScheduleInput = {
  where: Prisma.SeatLockScalarWhereInput
  data: Prisma.XOR<Prisma.SeatLockUpdateManyMutationInput, Prisma.SeatLockUncheckedUpdateManyWithoutTripScheduleInput>
}

export type SeatLockCreateWithoutTripSeatInput = {
  id?: string
  lockedAt?: Date | string
  expiresAt: Date | string
  tripSchedule: Prisma.TripScheduleCreateNestedOneWithoutSeatLocksInput
  booking?: Prisma.BookingCreateNestedOneWithoutSeatLocksInput
  lockedBy?: Prisma.UserCreateNestedOneWithoutSeatLocksInput
}

export type SeatLockUncheckedCreateWithoutTripSeatInput = {
  id?: string
  tripScheduleId: string
  bookingId?: string | null
  lockedById?: string | null
  lockedAt?: Date | string
  expiresAt: Date | string
}

export type SeatLockCreateOrConnectWithoutTripSeatInput = {
  where: Prisma.SeatLockWhereUniqueInput
  create: Prisma.XOR<Prisma.SeatLockCreateWithoutTripSeatInput, Prisma.SeatLockUncheckedCreateWithoutTripSeatInput>
}

export type SeatLockCreateManyTripSeatInputEnvelope = {
  data: Prisma.SeatLockCreateManyTripSeatInput | Prisma.SeatLockCreateManyTripSeatInput[]
  skipDuplicates?: boolean
}

export type SeatLockUpsertWithWhereUniqueWithoutTripSeatInput = {
  where: Prisma.SeatLockWhereUniqueInput
  update: Prisma.XOR<Prisma.SeatLockUpdateWithoutTripSeatInput, Prisma.SeatLockUncheckedUpdateWithoutTripSeatInput>
  create: Prisma.XOR<Prisma.SeatLockCreateWithoutTripSeatInput, Prisma.SeatLockUncheckedCreateWithoutTripSeatInput>
}

export type SeatLockUpdateWithWhereUniqueWithoutTripSeatInput = {
  where: Prisma.SeatLockWhereUniqueInput
  data: Prisma.XOR<Prisma.SeatLockUpdateWithoutTripSeatInput, Prisma.SeatLockUncheckedUpdateWithoutTripSeatInput>
}

export type SeatLockUpdateManyWithWhereWithoutTripSeatInput = {
  where: Prisma.SeatLockScalarWhereInput
  data: Prisma.XOR<Prisma.SeatLockUpdateManyMutationInput, Prisma.SeatLockUncheckedUpdateManyWithoutTripSeatInput>
}

export type SeatLockCreateWithoutBookingInput = {
  id?: string
  lockedAt?: Date | string
  expiresAt: Date | string
  tripSchedule: Prisma.TripScheduleCreateNestedOneWithoutSeatLocksInput
  tripSeat?: Prisma.TripSeatCreateNestedOneWithoutSeatLocksInput
  lockedBy?: Prisma.UserCreateNestedOneWithoutSeatLocksInput
}

export type SeatLockUncheckedCreateWithoutBookingInput = {
  id?: string
  tripScheduleId: string
  tripSeatId?: string | null
  lockedById?: string | null
  lockedAt?: Date | string
  expiresAt: Date | string
}

export type SeatLockCreateOrConnectWithoutBookingInput = {
  where: Prisma.SeatLockWhereUniqueInput
  create: Prisma.XOR<Prisma.SeatLockCreateWithoutBookingInput, Prisma.SeatLockUncheckedCreateWithoutBookingInput>
}

export type SeatLockCreateManyBookingInputEnvelope = {
  data: Prisma.SeatLockCreateManyBookingInput | Prisma.SeatLockCreateManyBookingInput[]
  skipDuplicates?: boolean
}

export type SeatLockUpsertWithWhereUniqueWithoutBookingInput = {
  where: Prisma.SeatLockWhereUniqueInput
  update: Prisma.XOR<Prisma.SeatLockUpdateWithoutBookingInput, Prisma.SeatLockUncheckedUpdateWithoutBookingInput>
  create: Prisma.XOR<Prisma.SeatLockCreateWithoutBookingInput, Prisma.SeatLockUncheckedCreateWithoutBookingInput>
}

export type SeatLockUpdateWithWhereUniqueWithoutBookingInput = {
  where: Prisma.SeatLockWhereUniqueInput
  data: Prisma.XOR<Prisma.SeatLockUpdateWithoutBookingInput, Prisma.SeatLockUncheckedUpdateWithoutBookingInput>
}

export type SeatLockUpdateManyWithWhereWithoutBookingInput = {
  where: Prisma.SeatLockScalarWhereInput
  data: Prisma.XOR<Prisma.SeatLockUpdateManyMutationInput, Prisma.SeatLockUncheckedUpdateManyWithoutBookingInput>
}

export type SeatLockCreateManyLockedByInput = {
  id?: string
  tripScheduleId: string
  tripSeatId?: string | null
  bookingId?: string | null
  lockedAt?: Date | string
  expiresAt: Date | string
}

export type SeatLockUpdateWithoutLockedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tripSchedule?: Prisma.TripScheduleUpdateOneRequiredWithoutSeatLocksNestedInput
  tripSeat?: Prisma.TripSeatUpdateOneWithoutSeatLocksNestedInput
  booking?: Prisma.BookingUpdateOneWithoutSeatLocksNestedInput
}

export type SeatLockUncheckedUpdateWithoutLockedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tripScheduleId?: Prisma.StringFieldUpdateOperationsInput | string
  tripSeatId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookingId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SeatLockUncheckedUpdateManyWithoutLockedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tripScheduleId?: Prisma.StringFieldUpdateOperationsInput | string
  tripSeatId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookingId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SeatLockCreateManyTripScheduleInput = {
  id?: string
  tripSeatId?: string | null
  bookingId?: string | null
  lockedById?: string | null
  lockedAt?: Date | string
  expiresAt: Date | string
}

export type SeatLockUpdateWithoutTripScheduleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tripSeat?: Prisma.TripSeatUpdateOneWithoutSeatLocksNestedInput
  booking?: Prisma.BookingUpdateOneWithoutSeatLocksNestedInput
  lockedBy?: Prisma.UserUpdateOneWithoutSeatLocksNestedInput
}

export type SeatLockUncheckedUpdateWithoutTripScheduleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tripSeatId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookingId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SeatLockUncheckedUpdateManyWithoutTripScheduleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tripSeatId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookingId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SeatLockCreateManyTripSeatInput = {
  id?: string
  tripScheduleId: string
  bookingId?: string | null
  lockedById?: string | null
  lockedAt?: Date | string
  expiresAt: Date | string
}

export type SeatLockUpdateWithoutTripSeatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tripSchedule?: Prisma.TripScheduleUpdateOneRequiredWithoutSeatLocksNestedInput
  booking?: Prisma.BookingUpdateOneWithoutSeatLocksNestedInput
  lockedBy?: Prisma.UserUpdateOneWithoutSeatLocksNestedInput
}

export type SeatLockUncheckedUpdateWithoutTripSeatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tripScheduleId?: Prisma.StringFieldUpdateOperationsInput | string
  bookingId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SeatLockUncheckedUpdateManyWithoutTripSeatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tripScheduleId?: Prisma.StringFieldUpdateOperationsInput | string
  bookingId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SeatLockCreateManyBookingInput = {
  id?: string
  tripScheduleId: string
  tripSeatId?: string | null
  lockedById?: string | null
  lockedAt?: Date | string
  expiresAt: Date | string
}

export type SeatLockUpdateWithoutBookingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tripSchedule?: Prisma.TripScheduleUpdateOneRequiredWithoutSeatLocksNestedInput
  tripSeat?: Prisma.TripSeatUpdateOneWithoutSeatLocksNestedInput
  lockedBy?: Prisma.UserUpdateOneWithoutSeatLocksNestedInput
}

export type SeatLockUncheckedUpdateWithoutBookingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tripScheduleId?: Prisma.StringFieldUpdateOperationsInput | string
  tripSeatId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SeatLockUncheckedUpdateManyWithoutBookingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tripScheduleId?: Prisma.StringFieldUpdateOperationsInput | string
  tripSeatId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SeatLockSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tripScheduleId?: boolean
  tripSeatId?: boolean
  bookingId?: boolean
  lockedById?: boolean
  lockedAt?: boolean
  expiresAt?: boolean
  tripSchedule?: boolean | Prisma.TripScheduleDefaultArgs<ExtArgs>
  tripSeat?: boolean | Prisma.SeatLock$tripSeatArgs<ExtArgs>
  booking?: boolean | Prisma.SeatLock$bookingArgs<ExtArgs>
  lockedBy?: boolean | Prisma.SeatLock$lockedByArgs<ExtArgs>
}, ExtArgs["result"]["seatLock"]>

export type SeatLockSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tripScheduleId?: boolean
  tripSeatId?: boolean
  bookingId?: boolean
  lockedById?: boolean
  lockedAt?: boolean
  expiresAt?: boolean
  tripSchedule?: boolean | Prisma.TripScheduleDefaultArgs<ExtArgs>
  tripSeat?: boolean | Prisma.SeatLock$tripSeatArgs<ExtArgs>
  booking?: boolean | Prisma.SeatLock$bookingArgs<ExtArgs>
  lockedBy?: boolean | Prisma.SeatLock$lockedByArgs<ExtArgs>
}, ExtArgs["result"]["seatLock"]>

export type SeatLockSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tripScheduleId?: boolean
  tripSeatId?: boolean
  bookingId?: boolean
  lockedById?: boolean
  lockedAt?: boolean
  expiresAt?: boolean
  tripSchedule?: boolean | Prisma.TripScheduleDefaultArgs<ExtArgs>
  tripSeat?: boolean | Prisma.SeatLock$tripSeatArgs<ExtArgs>
  booking?: boolean | Prisma.SeatLock$bookingArgs<ExtArgs>
  lockedBy?: boolean | Prisma.SeatLock$lockedByArgs<ExtArgs>
}, ExtArgs["result"]["seatLock"]>

export type SeatLockSelectScalar = {
  id?: boolean
  tripScheduleId?: boolean
  tripSeatId?: boolean
  bookingId?: boolean
  lockedById?: boolean
  lockedAt?: boolean
  expiresAt?: boolean
}

export type SeatLockOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tripScheduleId" | "tripSeatId" | "bookingId" | "lockedById" | "lockedAt" | "expiresAt", ExtArgs["result"]["seatLock"]>
export type SeatLockInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tripSchedule?: boolean | Prisma.TripScheduleDefaultArgs<ExtArgs>
  tripSeat?: boolean | Prisma.SeatLock$tripSeatArgs<ExtArgs>
  booking?: boolean | Prisma.SeatLock$bookingArgs<ExtArgs>
  lockedBy?: boolean | Prisma.SeatLock$lockedByArgs<ExtArgs>
}
export type SeatLockIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tripSchedule?: boolean | Prisma.TripScheduleDefaultArgs<ExtArgs>
  tripSeat?: boolean | Prisma.SeatLock$tripSeatArgs<ExtArgs>
  booking?: boolean | Prisma.SeatLock$bookingArgs<ExtArgs>
  lockedBy?: boolean | Prisma.SeatLock$lockedByArgs<ExtArgs>
}
export type SeatLockIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tripSchedule?: boolean | Prisma.TripScheduleDefaultArgs<ExtArgs>
  tripSeat?: boolean | Prisma.SeatLock$tripSeatArgs<ExtArgs>
  booking?: boolean | Prisma.SeatLock$bookingArgs<ExtArgs>
  lockedBy?: boolean | Prisma.SeatLock$lockedByArgs<ExtArgs>
}

export type $SeatLockPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SeatLock"
  objects: {
    tripSchedule: Prisma.$TripSchedulePayload<ExtArgs>
    tripSeat: Prisma.$TripSeatPayload<ExtArgs> | null
    booking: Prisma.$BookingPayload<ExtArgs> | null
    lockedBy: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    tripScheduleId: string
    tripSeatId: string | null
    bookingId: string | null
    lockedById: string | null
    lockedAt: Date
    expiresAt: Date
  }, ExtArgs["result"]["seatLock"]>
  composites: {}
}

export type SeatLockGetPayload<S extends boolean | null | undefined | SeatLockDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SeatLockPayload, S>

export type SeatLockCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SeatLockFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SeatLockCountAggregateInputType | true
  }

export interface SeatLockDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SeatLock'], meta: { name: 'SeatLock' } }
  /**
   * Find zero or one SeatLock that matches the filter.
   * @param {SeatLockFindUniqueArgs} args - Arguments to find a SeatLock
   * @example
   * // Get one SeatLock
   * const seatLock = await prisma.seatLock.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SeatLockFindUniqueArgs>(args: Prisma.SelectSubset<T, SeatLockFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SeatLockClient<runtime.Types.Result.GetResult<Prisma.$SeatLockPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SeatLock that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SeatLockFindUniqueOrThrowArgs} args - Arguments to find a SeatLock
   * @example
   * // Get one SeatLock
   * const seatLock = await prisma.seatLock.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SeatLockFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SeatLockFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SeatLockClient<runtime.Types.Result.GetResult<Prisma.$SeatLockPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SeatLock that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatLockFindFirstArgs} args - Arguments to find a SeatLock
   * @example
   * // Get one SeatLock
   * const seatLock = await prisma.seatLock.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SeatLockFindFirstArgs>(args?: Prisma.SelectSubset<T, SeatLockFindFirstArgs<ExtArgs>>): Prisma.Prisma__SeatLockClient<runtime.Types.Result.GetResult<Prisma.$SeatLockPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SeatLock that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatLockFindFirstOrThrowArgs} args - Arguments to find a SeatLock
   * @example
   * // Get one SeatLock
   * const seatLock = await prisma.seatLock.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SeatLockFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SeatLockFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SeatLockClient<runtime.Types.Result.GetResult<Prisma.$SeatLockPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SeatLocks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatLockFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SeatLocks
   * const seatLocks = await prisma.seatLock.findMany()
   * 
   * // Get first 10 SeatLocks
   * const seatLocks = await prisma.seatLock.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const seatLockWithIdOnly = await prisma.seatLock.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SeatLockFindManyArgs>(args?: Prisma.SelectSubset<T, SeatLockFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeatLockPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SeatLock.
   * @param {SeatLockCreateArgs} args - Arguments to create a SeatLock.
   * @example
   * // Create one SeatLock
   * const SeatLock = await prisma.seatLock.create({
   *   data: {
   *     // ... data to create a SeatLock
   *   }
   * })
   * 
   */
  create<T extends SeatLockCreateArgs>(args: Prisma.SelectSubset<T, SeatLockCreateArgs<ExtArgs>>): Prisma.Prisma__SeatLockClient<runtime.Types.Result.GetResult<Prisma.$SeatLockPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SeatLocks.
   * @param {SeatLockCreateManyArgs} args - Arguments to create many SeatLocks.
   * @example
   * // Create many SeatLocks
   * const seatLock = await prisma.seatLock.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SeatLockCreateManyArgs>(args?: Prisma.SelectSubset<T, SeatLockCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SeatLocks and returns the data saved in the database.
   * @param {SeatLockCreateManyAndReturnArgs} args - Arguments to create many SeatLocks.
   * @example
   * // Create many SeatLocks
   * const seatLock = await prisma.seatLock.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SeatLocks and only return the `id`
   * const seatLockWithIdOnly = await prisma.seatLock.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SeatLockCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SeatLockCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeatLockPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SeatLock.
   * @param {SeatLockDeleteArgs} args - Arguments to delete one SeatLock.
   * @example
   * // Delete one SeatLock
   * const SeatLock = await prisma.seatLock.delete({
   *   where: {
   *     // ... filter to delete one SeatLock
   *   }
   * })
   * 
   */
  delete<T extends SeatLockDeleteArgs>(args: Prisma.SelectSubset<T, SeatLockDeleteArgs<ExtArgs>>): Prisma.Prisma__SeatLockClient<runtime.Types.Result.GetResult<Prisma.$SeatLockPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SeatLock.
   * @param {SeatLockUpdateArgs} args - Arguments to update one SeatLock.
   * @example
   * // Update one SeatLock
   * const seatLock = await prisma.seatLock.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SeatLockUpdateArgs>(args: Prisma.SelectSubset<T, SeatLockUpdateArgs<ExtArgs>>): Prisma.Prisma__SeatLockClient<runtime.Types.Result.GetResult<Prisma.$SeatLockPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SeatLocks.
   * @param {SeatLockDeleteManyArgs} args - Arguments to filter SeatLocks to delete.
   * @example
   * // Delete a few SeatLocks
   * const { count } = await prisma.seatLock.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SeatLockDeleteManyArgs>(args?: Prisma.SelectSubset<T, SeatLockDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SeatLocks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatLockUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SeatLocks
   * const seatLock = await prisma.seatLock.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SeatLockUpdateManyArgs>(args: Prisma.SelectSubset<T, SeatLockUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SeatLocks and returns the data updated in the database.
   * @param {SeatLockUpdateManyAndReturnArgs} args - Arguments to update many SeatLocks.
   * @example
   * // Update many SeatLocks
   * const seatLock = await prisma.seatLock.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SeatLocks and only return the `id`
   * const seatLockWithIdOnly = await prisma.seatLock.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SeatLockUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SeatLockUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeatLockPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SeatLock.
   * @param {SeatLockUpsertArgs} args - Arguments to update or create a SeatLock.
   * @example
   * // Update or create a SeatLock
   * const seatLock = await prisma.seatLock.upsert({
   *   create: {
   *     // ... data to create a SeatLock
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SeatLock we want to update
   *   }
   * })
   */
  upsert<T extends SeatLockUpsertArgs>(args: Prisma.SelectSubset<T, SeatLockUpsertArgs<ExtArgs>>): Prisma.Prisma__SeatLockClient<runtime.Types.Result.GetResult<Prisma.$SeatLockPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SeatLocks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatLockCountArgs} args - Arguments to filter SeatLocks to count.
   * @example
   * // Count the number of SeatLocks
   * const count = await prisma.seatLock.count({
   *   where: {
   *     // ... the filter for the SeatLocks we want to count
   *   }
   * })
  **/
  count<T extends SeatLockCountArgs>(
    args?: Prisma.Subset<T, SeatLockCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SeatLockCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SeatLock.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatLockAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SeatLockAggregateArgs>(args: Prisma.Subset<T, SeatLockAggregateArgs>): Prisma.PrismaPromise<GetSeatLockAggregateType<T>>

  /**
   * Group by SeatLock.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatLockGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SeatLockGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SeatLockGroupByArgs['orderBy'] }
      : { orderBy?: SeatLockGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SeatLockGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSeatLockGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SeatLock model
 */
readonly fields: SeatLockFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SeatLock.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SeatLockClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tripSchedule<T extends Prisma.TripScheduleDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TripScheduleDefaultArgs<ExtArgs>>): Prisma.Prisma__TripScheduleClient<runtime.Types.Result.GetResult<Prisma.$TripSchedulePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  tripSeat<T extends Prisma.SeatLock$tripSeatArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SeatLock$tripSeatArgs<ExtArgs>>): Prisma.Prisma__TripSeatClient<runtime.Types.Result.GetResult<Prisma.$TripSeatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  booking<T extends Prisma.SeatLock$bookingArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SeatLock$bookingArgs<ExtArgs>>): Prisma.Prisma__BookingClient<runtime.Types.Result.GetResult<Prisma.$BookingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  lockedBy<T extends Prisma.SeatLock$lockedByArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SeatLock$lockedByArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SeatLock model
 */
export interface SeatLockFieldRefs {
  readonly id: Prisma.FieldRef<"SeatLock", 'String'>
  readonly tripScheduleId: Prisma.FieldRef<"SeatLock", 'String'>
  readonly tripSeatId: Prisma.FieldRef<"SeatLock", 'String'>
  readonly bookingId: Prisma.FieldRef<"SeatLock", 'String'>
  readonly lockedById: Prisma.FieldRef<"SeatLock", 'String'>
  readonly lockedAt: Prisma.FieldRef<"SeatLock", 'DateTime'>
  readonly expiresAt: Prisma.FieldRef<"SeatLock", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SeatLock findUnique
 */
export type SeatLockFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatLock
   */
  select?: Prisma.SeatLockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatLock
   */
  omit?: Prisma.SeatLockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatLockInclude<ExtArgs> | null
  /**
   * Filter, which SeatLock to fetch.
   */
  where: Prisma.SeatLockWhereUniqueInput
}

/**
 * SeatLock findUniqueOrThrow
 */
export type SeatLockFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatLock
   */
  select?: Prisma.SeatLockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatLock
   */
  omit?: Prisma.SeatLockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatLockInclude<ExtArgs> | null
  /**
   * Filter, which SeatLock to fetch.
   */
  where: Prisma.SeatLockWhereUniqueInput
}

/**
 * SeatLock findFirst
 */
export type SeatLockFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatLock
   */
  select?: Prisma.SeatLockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatLock
   */
  omit?: Prisma.SeatLockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatLockInclude<ExtArgs> | null
  /**
   * Filter, which SeatLock to fetch.
   */
  where?: Prisma.SeatLockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SeatLocks to fetch.
   */
  orderBy?: Prisma.SeatLockOrderByWithRelationInput | Prisma.SeatLockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SeatLocks.
   */
  cursor?: Prisma.SeatLockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SeatLocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SeatLocks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SeatLocks.
   */
  distinct?: Prisma.SeatLockScalarFieldEnum | Prisma.SeatLockScalarFieldEnum[]
}

/**
 * SeatLock findFirstOrThrow
 */
export type SeatLockFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatLock
   */
  select?: Prisma.SeatLockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatLock
   */
  omit?: Prisma.SeatLockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatLockInclude<ExtArgs> | null
  /**
   * Filter, which SeatLock to fetch.
   */
  where?: Prisma.SeatLockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SeatLocks to fetch.
   */
  orderBy?: Prisma.SeatLockOrderByWithRelationInput | Prisma.SeatLockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SeatLocks.
   */
  cursor?: Prisma.SeatLockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SeatLocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SeatLocks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SeatLocks.
   */
  distinct?: Prisma.SeatLockScalarFieldEnum | Prisma.SeatLockScalarFieldEnum[]
}

/**
 * SeatLock findMany
 */
export type SeatLockFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatLock
   */
  select?: Prisma.SeatLockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatLock
   */
  omit?: Prisma.SeatLockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatLockInclude<ExtArgs> | null
  /**
   * Filter, which SeatLocks to fetch.
   */
  where?: Prisma.SeatLockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SeatLocks to fetch.
   */
  orderBy?: Prisma.SeatLockOrderByWithRelationInput | Prisma.SeatLockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SeatLocks.
   */
  cursor?: Prisma.SeatLockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SeatLocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SeatLocks.
   */
  skip?: number
  distinct?: Prisma.SeatLockScalarFieldEnum | Prisma.SeatLockScalarFieldEnum[]
}

/**
 * SeatLock create
 */
export type SeatLockCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatLock
   */
  select?: Prisma.SeatLockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatLock
   */
  omit?: Prisma.SeatLockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatLockInclude<ExtArgs> | null
  /**
   * The data needed to create a SeatLock.
   */
  data: Prisma.XOR<Prisma.SeatLockCreateInput, Prisma.SeatLockUncheckedCreateInput>
}

/**
 * SeatLock createMany
 */
export type SeatLockCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SeatLocks.
   */
  data: Prisma.SeatLockCreateManyInput | Prisma.SeatLockCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SeatLock createManyAndReturn
 */
export type SeatLockCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatLock
   */
  select?: Prisma.SeatLockSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SeatLock
   */
  omit?: Prisma.SeatLockOmit<ExtArgs> | null
  /**
   * The data used to create many SeatLocks.
   */
  data: Prisma.SeatLockCreateManyInput | Prisma.SeatLockCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatLockIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SeatLock update
 */
export type SeatLockUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatLock
   */
  select?: Prisma.SeatLockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatLock
   */
  omit?: Prisma.SeatLockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatLockInclude<ExtArgs> | null
  /**
   * The data needed to update a SeatLock.
   */
  data: Prisma.XOR<Prisma.SeatLockUpdateInput, Prisma.SeatLockUncheckedUpdateInput>
  /**
   * Choose, which SeatLock to update.
   */
  where: Prisma.SeatLockWhereUniqueInput
}

/**
 * SeatLock updateMany
 */
export type SeatLockUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SeatLocks.
   */
  data: Prisma.XOR<Prisma.SeatLockUpdateManyMutationInput, Prisma.SeatLockUncheckedUpdateManyInput>
  /**
   * Filter which SeatLocks to update
   */
  where?: Prisma.SeatLockWhereInput
  /**
   * Limit how many SeatLocks to update.
   */
  limit?: number
}

/**
 * SeatLock updateManyAndReturn
 */
export type SeatLockUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatLock
   */
  select?: Prisma.SeatLockSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SeatLock
   */
  omit?: Prisma.SeatLockOmit<ExtArgs> | null
  /**
   * The data used to update SeatLocks.
   */
  data: Prisma.XOR<Prisma.SeatLockUpdateManyMutationInput, Prisma.SeatLockUncheckedUpdateManyInput>
  /**
   * Filter which SeatLocks to update
   */
  where?: Prisma.SeatLockWhereInput
  /**
   * Limit how many SeatLocks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatLockIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SeatLock upsert
 */
export type SeatLockUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatLock
   */
  select?: Prisma.SeatLockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatLock
   */
  omit?: Prisma.SeatLockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatLockInclude<ExtArgs> | null
  /**
   * The filter to search for the SeatLock to update in case it exists.
   */
  where: Prisma.SeatLockWhereUniqueInput
  /**
   * In case the SeatLock found by the `where` argument doesn't exist, create a new SeatLock with this data.
   */
  create: Prisma.XOR<Prisma.SeatLockCreateInput, Prisma.SeatLockUncheckedCreateInput>
  /**
   * In case the SeatLock was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SeatLockUpdateInput, Prisma.SeatLockUncheckedUpdateInput>
}

/**
 * SeatLock delete
 */
export type SeatLockDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatLock
   */
  select?: Prisma.SeatLockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatLock
   */
  omit?: Prisma.SeatLockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatLockInclude<ExtArgs> | null
  /**
   * Filter which SeatLock to delete.
   */
  where: Prisma.SeatLockWhereUniqueInput
}

/**
 * SeatLock deleteMany
 */
export type SeatLockDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SeatLocks to delete
   */
  where?: Prisma.SeatLockWhereInput
  /**
   * Limit how many SeatLocks to delete.
   */
  limit?: number
}

/**
 * SeatLock.tripSeat
 */
export type SeatLock$tripSeatArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TripSeat
   */
  select?: Prisma.TripSeatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TripSeat
   */
  omit?: Prisma.TripSeatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripSeatInclude<ExtArgs> | null
  where?: Prisma.TripSeatWhereInput
}

/**
 * SeatLock.booking
 */
export type SeatLock$bookingArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Booking
   */
  select?: Prisma.BookingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Booking
   */
  omit?: Prisma.BookingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingInclude<ExtArgs> | null
  where?: Prisma.BookingWhereInput
}

/**
 * SeatLock.lockedBy
 */
export type SeatLock$lockedByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * SeatLock without action
 */
export type SeatLockDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatLock
   */
  select?: Prisma.SeatLockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatLock
   */
  omit?: Prisma.SeatLockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatLockInclude<ExtArgs> | null
}
