
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Vessel` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Vessel
 * 
 */
export type VesselModel = runtime.Types.Result.DefaultSelection<Prisma.$VesselPayload>

export type AggregateVessel = {
  _count: VesselCountAggregateOutputType | null
  _avg: VesselAvgAggregateOutputType | null
  _sum: VesselSumAggregateOutputType | null
  _min: VesselMinAggregateOutputType | null
  _max: VesselMaxAggregateOutputType | null
}

export type VesselAvgAggregateOutputType = {
  capacity: number | null
}

export type VesselSumAggregateOutputType = {
  capacity: number | null
}

export type VesselMinAggregateOutputType = {
  id: string | null
  operatorId: string | null
  name: string | null
  registrationNo: string | null
  capacity: number | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type VesselMaxAggregateOutputType = {
  id: string | null
  operatorId: string | null
  name: string | null
  registrationNo: string | null
  capacity: number | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type VesselCountAggregateOutputType = {
  id: number
  operatorId: number
  name: number
  registrationNo: number
  capacity: number
  description: number
  vesselMetadata: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type VesselAvgAggregateInputType = {
  capacity?: true
}

export type VesselSumAggregateInputType = {
  capacity?: true
}

export type VesselMinAggregateInputType = {
  id?: true
  operatorId?: true
  name?: true
  registrationNo?: true
  capacity?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type VesselMaxAggregateInputType = {
  id?: true
  operatorId?: true
  name?: true
  registrationNo?: true
  capacity?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type VesselCountAggregateInputType = {
  id?: true
  operatorId?: true
  name?: true
  registrationNo?: true
  capacity?: true
  description?: true
  vesselMetadata?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type VesselAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Vessel to aggregate.
   */
  where?: Prisma.VesselWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Vessels to fetch.
   */
  orderBy?: Prisma.VesselOrderByWithRelationInput | Prisma.VesselOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VesselWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Vessels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Vessels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Vessels
  **/
  _count?: true | VesselCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: VesselAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: VesselSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VesselMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VesselMaxAggregateInputType
}

export type GetVesselAggregateType<T extends VesselAggregateArgs> = {
      [P in keyof T & keyof AggregateVessel]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVessel[P]>
    : Prisma.GetScalarType<T[P], AggregateVessel[P]>
}




export type VesselGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VesselWhereInput
  orderBy?: Prisma.VesselOrderByWithAggregationInput | Prisma.VesselOrderByWithAggregationInput[]
  by: Prisma.VesselScalarFieldEnum[] | Prisma.VesselScalarFieldEnum
  having?: Prisma.VesselScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VesselCountAggregateInputType | true
  _avg?: VesselAvgAggregateInputType
  _sum?: VesselSumAggregateInputType
  _min?: VesselMinAggregateInputType
  _max?: VesselMaxAggregateInputType
}

export type VesselGroupByOutputType = {
  id: string
  operatorId: string
  name: string
  registrationNo: string | null
  capacity: number
  description: string | null
  vesselMetadata: runtime.JsonValue | null
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: VesselCountAggregateOutputType | null
  _avg: VesselAvgAggregateOutputType | null
  _sum: VesselSumAggregateOutputType | null
  _min: VesselMinAggregateOutputType | null
  _max: VesselMaxAggregateOutputType | null
}

type GetVesselGroupByPayload<T extends VesselGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VesselGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VesselGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VesselGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VesselGroupByOutputType[P]>
      }
    >
  >



export type VesselWhereInput = {
  AND?: Prisma.VesselWhereInput | Prisma.VesselWhereInput[]
  OR?: Prisma.VesselWhereInput[]
  NOT?: Prisma.VesselWhereInput | Prisma.VesselWhereInput[]
  id?: Prisma.StringFilter<"Vessel"> | string
  operatorId?: Prisma.StringFilter<"Vessel"> | string
  name?: Prisma.StringFilter<"Vessel"> | string
  registrationNo?: Prisma.StringNullableFilter<"Vessel"> | string | null
  capacity?: Prisma.IntFilter<"Vessel"> | number
  description?: Prisma.StringNullableFilter<"Vessel"> | string | null
  vesselMetadata?: Prisma.JsonNullableFilter<"Vessel">
  createdAt?: Prisma.DateTimeFilter<"Vessel"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Vessel"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Vessel"> | Date | string | null
  operator?: Prisma.XOR<Prisma.OperatorScalarRelationFilter, Prisma.OperatorWhereInput>
  trips?: Prisma.TripListRelationFilter
}

export type VesselOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  operatorId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  registrationNo?: Prisma.SortOrderInput | Prisma.SortOrder
  capacity?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  vesselMetadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  operator?: Prisma.OperatorOrderByWithRelationInput
  trips?: Prisma.TripOrderByRelationAggregateInput
}

export type VesselWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.VesselWhereInput | Prisma.VesselWhereInput[]
  OR?: Prisma.VesselWhereInput[]
  NOT?: Prisma.VesselWhereInput | Prisma.VesselWhereInput[]
  operatorId?: Prisma.StringFilter<"Vessel"> | string
  name?: Prisma.StringFilter<"Vessel"> | string
  registrationNo?: Prisma.StringNullableFilter<"Vessel"> | string | null
  capacity?: Prisma.IntFilter<"Vessel"> | number
  description?: Prisma.StringNullableFilter<"Vessel"> | string | null
  vesselMetadata?: Prisma.JsonNullableFilter<"Vessel">
  createdAt?: Prisma.DateTimeFilter<"Vessel"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Vessel"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Vessel"> | Date | string | null
  operator?: Prisma.XOR<Prisma.OperatorScalarRelationFilter, Prisma.OperatorWhereInput>
  trips?: Prisma.TripListRelationFilter
}, "id">

export type VesselOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  operatorId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  registrationNo?: Prisma.SortOrderInput | Prisma.SortOrder
  capacity?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  vesselMetadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.VesselCountOrderByAggregateInput
  _avg?: Prisma.VesselAvgOrderByAggregateInput
  _max?: Prisma.VesselMaxOrderByAggregateInput
  _min?: Prisma.VesselMinOrderByAggregateInput
  _sum?: Prisma.VesselSumOrderByAggregateInput
}

export type VesselScalarWhereWithAggregatesInput = {
  AND?: Prisma.VesselScalarWhereWithAggregatesInput | Prisma.VesselScalarWhereWithAggregatesInput[]
  OR?: Prisma.VesselScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VesselScalarWhereWithAggregatesInput | Prisma.VesselScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Vessel"> | string
  operatorId?: Prisma.StringWithAggregatesFilter<"Vessel"> | string
  name?: Prisma.StringWithAggregatesFilter<"Vessel"> | string
  registrationNo?: Prisma.StringNullableWithAggregatesFilter<"Vessel"> | string | null
  capacity?: Prisma.IntWithAggregatesFilter<"Vessel"> | number
  description?: Prisma.StringNullableWithAggregatesFilter<"Vessel"> | string | null
  vesselMetadata?: Prisma.JsonNullableWithAggregatesFilter<"Vessel">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Vessel"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Vessel"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Vessel"> | Date | string | null
}

export type VesselCreateInput = {
  id?: string
  name: string
  registrationNo?: string | null
  capacity: number
  description?: string | null
  vesselMetadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  operator: Prisma.OperatorCreateNestedOneWithoutVesselsInput
  trips?: Prisma.TripCreateNestedManyWithoutVesselInput
}

export type VesselUncheckedCreateInput = {
  id?: string
  operatorId: string
  name: string
  registrationNo?: string | null
  capacity: number
  description?: string | null
  vesselMetadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  trips?: Prisma.TripUncheckedCreateNestedManyWithoutVesselInput
}

export type VesselUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  registrationNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  vesselMetadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  operator?: Prisma.OperatorUpdateOneRequiredWithoutVesselsNestedInput
  trips?: Prisma.TripUpdateManyWithoutVesselNestedInput
}

export type VesselUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  operatorId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  registrationNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  vesselMetadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  trips?: Prisma.TripUncheckedUpdateManyWithoutVesselNestedInput
}

export type VesselCreateManyInput = {
  id?: string
  operatorId: string
  name: string
  registrationNo?: string | null
  capacity: number
  description?: string | null
  vesselMetadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type VesselUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  registrationNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  vesselMetadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type VesselUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  operatorId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  registrationNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  vesselMetadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type VesselListRelationFilter = {
  every?: Prisma.VesselWhereInput
  some?: Prisma.VesselWhereInput
  none?: Prisma.VesselWhereInput
}

export type VesselOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type VesselCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  operatorId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  registrationNo?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
  description?: Prisma.SortOrder
  vesselMetadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type VesselAvgOrderByAggregateInput = {
  capacity?: Prisma.SortOrder
}

export type VesselMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  operatorId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  registrationNo?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type VesselMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  operatorId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  registrationNo?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type VesselSumOrderByAggregateInput = {
  capacity?: Prisma.SortOrder
}

export type VesselScalarRelationFilter = {
  is?: Prisma.VesselWhereInput
  isNot?: Prisma.VesselWhereInput
}

export type VesselCreateNestedManyWithoutOperatorInput = {
  create?: Prisma.XOR<Prisma.VesselCreateWithoutOperatorInput, Prisma.VesselUncheckedCreateWithoutOperatorInput> | Prisma.VesselCreateWithoutOperatorInput[] | Prisma.VesselUncheckedCreateWithoutOperatorInput[]
  connectOrCreate?: Prisma.VesselCreateOrConnectWithoutOperatorInput | Prisma.VesselCreateOrConnectWithoutOperatorInput[]
  createMany?: Prisma.VesselCreateManyOperatorInputEnvelope
  connect?: Prisma.VesselWhereUniqueInput | Prisma.VesselWhereUniqueInput[]
}

export type VesselUncheckedCreateNestedManyWithoutOperatorInput = {
  create?: Prisma.XOR<Prisma.VesselCreateWithoutOperatorInput, Prisma.VesselUncheckedCreateWithoutOperatorInput> | Prisma.VesselCreateWithoutOperatorInput[] | Prisma.VesselUncheckedCreateWithoutOperatorInput[]
  connectOrCreate?: Prisma.VesselCreateOrConnectWithoutOperatorInput | Prisma.VesselCreateOrConnectWithoutOperatorInput[]
  createMany?: Prisma.VesselCreateManyOperatorInputEnvelope
  connect?: Prisma.VesselWhereUniqueInput | Prisma.VesselWhereUniqueInput[]
}

export type VesselUpdateManyWithoutOperatorNestedInput = {
  create?: Prisma.XOR<Prisma.VesselCreateWithoutOperatorInput, Prisma.VesselUncheckedCreateWithoutOperatorInput> | Prisma.VesselCreateWithoutOperatorInput[] | Prisma.VesselUncheckedCreateWithoutOperatorInput[]
  connectOrCreate?: Prisma.VesselCreateOrConnectWithoutOperatorInput | Prisma.VesselCreateOrConnectWithoutOperatorInput[]
  upsert?: Prisma.VesselUpsertWithWhereUniqueWithoutOperatorInput | Prisma.VesselUpsertWithWhereUniqueWithoutOperatorInput[]
  createMany?: Prisma.VesselCreateManyOperatorInputEnvelope
  set?: Prisma.VesselWhereUniqueInput | Prisma.VesselWhereUniqueInput[]
  disconnect?: Prisma.VesselWhereUniqueInput | Prisma.VesselWhereUniqueInput[]
  delete?: Prisma.VesselWhereUniqueInput | Prisma.VesselWhereUniqueInput[]
  connect?: Prisma.VesselWhereUniqueInput | Prisma.VesselWhereUniqueInput[]
  update?: Prisma.VesselUpdateWithWhereUniqueWithoutOperatorInput | Prisma.VesselUpdateWithWhereUniqueWithoutOperatorInput[]
  updateMany?: Prisma.VesselUpdateManyWithWhereWithoutOperatorInput | Prisma.VesselUpdateManyWithWhereWithoutOperatorInput[]
  deleteMany?: Prisma.VesselScalarWhereInput | Prisma.VesselScalarWhereInput[]
}

export type VesselUncheckedUpdateManyWithoutOperatorNestedInput = {
  create?: Prisma.XOR<Prisma.VesselCreateWithoutOperatorInput, Prisma.VesselUncheckedCreateWithoutOperatorInput> | Prisma.VesselCreateWithoutOperatorInput[] | Prisma.VesselUncheckedCreateWithoutOperatorInput[]
  connectOrCreate?: Prisma.VesselCreateOrConnectWithoutOperatorInput | Prisma.VesselCreateOrConnectWithoutOperatorInput[]
  upsert?: Prisma.VesselUpsertWithWhereUniqueWithoutOperatorInput | Prisma.VesselUpsertWithWhereUniqueWithoutOperatorInput[]
  createMany?: Prisma.VesselCreateManyOperatorInputEnvelope
  set?: Prisma.VesselWhereUniqueInput | Prisma.VesselWhereUniqueInput[]
  disconnect?: Prisma.VesselWhereUniqueInput | Prisma.VesselWhereUniqueInput[]
  delete?: Prisma.VesselWhereUniqueInput | Prisma.VesselWhereUniqueInput[]
  connect?: Prisma.VesselWhereUniqueInput | Prisma.VesselWhereUniqueInput[]
  update?: Prisma.VesselUpdateWithWhereUniqueWithoutOperatorInput | Prisma.VesselUpdateWithWhereUniqueWithoutOperatorInput[]
  updateMany?: Prisma.VesselUpdateManyWithWhereWithoutOperatorInput | Prisma.VesselUpdateManyWithWhereWithoutOperatorInput[]
  deleteMany?: Prisma.VesselScalarWhereInput | Prisma.VesselScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type VesselCreateNestedOneWithoutTripsInput = {
  create?: Prisma.XOR<Prisma.VesselCreateWithoutTripsInput, Prisma.VesselUncheckedCreateWithoutTripsInput>
  connectOrCreate?: Prisma.VesselCreateOrConnectWithoutTripsInput
  connect?: Prisma.VesselWhereUniqueInput
}

export type VesselUpdateOneRequiredWithoutTripsNestedInput = {
  create?: Prisma.XOR<Prisma.VesselCreateWithoutTripsInput, Prisma.VesselUncheckedCreateWithoutTripsInput>
  connectOrCreate?: Prisma.VesselCreateOrConnectWithoutTripsInput
  upsert?: Prisma.VesselUpsertWithoutTripsInput
  connect?: Prisma.VesselWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.VesselUpdateToOneWithWhereWithoutTripsInput, Prisma.VesselUpdateWithoutTripsInput>, Prisma.VesselUncheckedUpdateWithoutTripsInput>
}

export type VesselCreateWithoutOperatorInput = {
  id?: string
  name: string
  registrationNo?: string | null
  capacity: number
  description?: string | null
  vesselMetadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  trips?: Prisma.TripCreateNestedManyWithoutVesselInput
}

export type VesselUncheckedCreateWithoutOperatorInput = {
  id?: string
  name: string
  registrationNo?: string | null
  capacity: number
  description?: string | null
  vesselMetadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  trips?: Prisma.TripUncheckedCreateNestedManyWithoutVesselInput
}

export type VesselCreateOrConnectWithoutOperatorInput = {
  where: Prisma.VesselWhereUniqueInput
  create: Prisma.XOR<Prisma.VesselCreateWithoutOperatorInput, Prisma.VesselUncheckedCreateWithoutOperatorInput>
}

export type VesselCreateManyOperatorInputEnvelope = {
  data: Prisma.VesselCreateManyOperatorInput | Prisma.VesselCreateManyOperatorInput[]
  skipDuplicates?: boolean
}

export type VesselUpsertWithWhereUniqueWithoutOperatorInput = {
  where: Prisma.VesselWhereUniqueInput
  update: Prisma.XOR<Prisma.VesselUpdateWithoutOperatorInput, Prisma.VesselUncheckedUpdateWithoutOperatorInput>
  create: Prisma.XOR<Prisma.VesselCreateWithoutOperatorInput, Prisma.VesselUncheckedCreateWithoutOperatorInput>
}

export type VesselUpdateWithWhereUniqueWithoutOperatorInput = {
  where: Prisma.VesselWhereUniqueInput
  data: Prisma.XOR<Prisma.VesselUpdateWithoutOperatorInput, Prisma.VesselUncheckedUpdateWithoutOperatorInput>
}

export type VesselUpdateManyWithWhereWithoutOperatorInput = {
  where: Prisma.VesselScalarWhereInput
  data: Prisma.XOR<Prisma.VesselUpdateManyMutationInput, Prisma.VesselUncheckedUpdateManyWithoutOperatorInput>
}

export type VesselScalarWhereInput = {
  AND?: Prisma.VesselScalarWhereInput | Prisma.VesselScalarWhereInput[]
  OR?: Prisma.VesselScalarWhereInput[]
  NOT?: Prisma.VesselScalarWhereInput | Prisma.VesselScalarWhereInput[]
  id?: Prisma.StringFilter<"Vessel"> | string
  operatorId?: Prisma.StringFilter<"Vessel"> | string
  name?: Prisma.StringFilter<"Vessel"> | string
  registrationNo?: Prisma.StringNullableFilter<"Vessel"> | string | null
  capacity?: Prisma.IntFilter<"Vessel"> | number
  description?: Prisma.StringNullableFilter<"Vessel"> | string | null
  vesselMetadata?: Prisma.JsonNullableFilter<"Vessel">
  createdAt?: Prisma.DateTimeFilter<"Vessel"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Vessel"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Vessel"> | Date | string | null
}

export type VesselCreateWithoutTripsInput = {
  id?: string
  name: string
  registrationNo?: string | null
  capacity: number
  description?: string | null
  vesselMetadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  operator: Prisma.OperatorCreateNestedOneWithoutVesselsInput
}

export type VesselUncheckedCreateWithoutTripsInput = {
  id?: string
  operatorId: string
  name: string
  registrationNo?: string | null
  capacity: number
  description?: string | null
  vesselMetadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type VesselCreateOrConnectWithoutTripsInput = {
  where: Prisma.VesselWhereUniqueInput
  create: Prisma.XOR<Prisma.VesselCreateWithoutTripsInput, Prisma.VesselUncheckedCreateWithoutTripsInput>
}

export type VesselUpsertWithoutTripsInput = {
  update: Prisma.XOR<Prisma.VesselUpdateWithoutTripsInput, Prisma.VesselUncheckedUpdateWithoutTripsInput>
  create: Prisma.XOR<Prisma.VesselCreateWithoutTripsInput, Prisma.VesselUncheckedCreateWithoutTripsInput>
  where?: Prisma.VesselWhereInput
}

export type VesselUpdateToOneWithWhereWithoutTripsInput = {
  where?: Prisma.VesselWhereInput
  data: Prisma.XOR<Prisma.VesselUpdateWithoutTripsInput, Prisma.VesselUncheckedUpdateWithoutTripsInput>
}

export type VesselUpdateWithoutTripsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  registrationNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  vesselMetadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  operator?: Prisma.OperatorUpdateOneRequiredWithoutVesselsNestedInput
}

export type VesselUncheckedUpdateWithoutTripsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  operatorId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  registrationNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  vesselMetadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type VesselCreateManyOperatorInput = {
  id?: string
  name: string
  registrationNo?: string | null
  capacity: number
  description?: string | null
  vesselMetadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type VesselUpdateWithoutOperatorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  registrationNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  vesselMetadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  trips?: Prisma.TripUpdateManyWithoutVesselNestedInput
}

export type VesselUncheckedUpdateWithoutOperatorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  registrationNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  vesselMetadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  trips?: Prisma.TripUncheckedUpdateManyWithoutVesselNestedInput
}

export type VesselUncheckedUpdateManyWithoutOperatorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  registrationNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  vesselMetadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type VesselCountOutputType
 */

export type VesselCountOutputType = {
  trips: number
}

export type VesselCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  trips?: boolean | VesselCountOutputTypeCountTripsArgs
}

/**
 * VesselCountOutputType without action
 */
export type VesselCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VesselCountOutputType
   */
  select?: Prisma.VesselCountOutputTypeSelect<ExtArgs> | null
}

/**
 * VesselCountOutputType without action
 */
export type VesselCountOutputTypeCountTripsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TripWhereInput
}


export type VesselSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  operatorId?: boolean
  name?: boolean
  registrationNo?: boolean
  capacity?: boolean
  description?: boolean
  vesselMetadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  operator?: boolean | Prisma.OperatorDefaultArgs<ExtArgs>
  trips?: boolean | Prisma.Vessel$tripsArgs<ExtArgs>
  _count?: boolean | Prisma.VesselCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vessel"]>

export type VesselSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  operatorId?: boolean
  name?: boolean
  registrationNo?: boolean
  capacity?: boolean
  description?: boolean
  vesselMetadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  operator?: boolean | Prisma.OperatorDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vessel"]>

export type VesselSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  operatorId?: boolean
  name?: boolean
  registrationNo?: boolean
  capacity?: boolean
  description?: boolean
  vesselMetadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  operator?: boolean | Prisma.OperatorDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vessel"]>

export type VesselSelectScalar = {
  id?: boolean
  operatorId?: boolean
  name?: boolean
  registrationNo?: boolean
  capacity?: boolean
  description?: boolean
  vesselMetadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type VesselOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "operatorId" | "name" | "registrationNo" | "capacity" | "description" | "vesselMetadata" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["vessel"]>
export type VesselInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  operator?: boolean | Prisma.OperatorDefaultArgs<ExtArgs>
  trips?: boolean | Prisma.Vessel$tripsArgs<ExtArgs>
  _count?: boolean | Prisma.VesselCountOutputTypeDefaultArgs<ExtArgs>
}
export type VesselIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  operator?: boolean | Prisma.OperatorDefaultArgs<ExtArgs>
}
export type VesselIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  operator?: boolean | Prisma.OperatorDefaultArgs<ExtArgs>
}

export type $VesselPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Vessel"
  objects: {
    operator: Prisma.$OperatorPayload<ExtArgs>
    trips: Prisma.$TripPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    operatorId: string
    name: string
    registrationNo: string | null
    capacity: number
    description: string | null
    vesselMetadata: runtime.JsonValue | null
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["vessel"]>
  composites: {}
}

export type VesselGetPayload<S extends boolean | null | undefined | VesselDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VesselPayload, S>

export type VesselCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VesselFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VesselCountAggregateInputType | true
  }

export interface VesselDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Vessel'], meta: { name: 'Vessel' } }
  /**
   * Find zero or one Vessel that matches the filter.
   * @param {VesselFindUniqueArgs} args - Arguments to find a Vessel
   * @example
   * // Get one Vessel
   * const vessel = await prisma.vessel.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VesselFindUniqueArgs>(args: Prisma.SelectSubset<T, VesselFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VesselClient<runtime.Types.Result.GetResult<Prisma.$VesselPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Vessel that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VesselFindUniqueOrThrowArgs} args - Arguments to find a Vessel
   * @example
   * // Get one Vessel
   * const vessel = await prisma.vessel.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VesselFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VesselFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VesselClient<runtime.Types.Result.GetResult<Prisma.$VesselPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Vessel that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VesselFindFirstArgs} args - Arguments to find a Vessel
   * @example
   * // Get one Vessel
   * const vessel = await prisma.vessel.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VesselFindFirstArgs>(args?: Prisma.SelectSubset<T, VesselFindFirstArgs<ExtArgs>>): Prisma.Prisma__VesselClient<runtime.Types.Result.GetResult<Prisma.$VesselPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Vessel that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VesselFindFirstOrThrowArgs} args - Arguments to find a Vessel
   * @example
   * // Get one Vessel
   * const vessel = await prisma.vessel.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VesselFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VesselFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VesselClient<runtime.Types.Result.GetResult<Prisma.$VesselPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Vessels that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VesselFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Vessels
   * const vessels = await prisma.vessel.findMany()
   * 
   * // Get first 10 Vessels
   * const vessels = await prisma.vessel.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const vesselWithIdOnly = await prisma.vessel.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VesselFindManyArgs>(args?: Prisma.SelectSubset<T, VesselFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VesselPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Vessel.
   * @param {VesselCreateArgs} args - Arguments to create a Vessel.
   * @example
   * // Create one Vessel
   * const Vessel = await prisma.vessel.create({
   *   data: {
   *     // ... data to create a Vessel
   *   }
   * })
   * 
   */
  create<T extends VesselCreateArgs>(args: Prisma.SelectSubset<T, VesselCreateArgs<ExtArgs>>): Prisma.Prisma__VesselClient<runtime.Types.Result.GetResult<Prisma.$VesselPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Vessels.
   * @param {VesselCreateManyArgs} args - Arguments to create many Vessels.
   * @example
   * // Create many Vessels
   * const vessel = await prisma.vessel.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VesselCreateManyArgs>(args?: Prisma.SelectSubset<T, VesselCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Vessels and returns the data saved in the database.
   * @param {VesselCreateManyAndReturnArgs} args - Arguments to create many Vessels.
   * @example
   * // Create many Vessels
   * const vessel = await prisma.vessel.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Vessels and only return the `id`
   * const vesselWithIdOnly = await prisma.vessel.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VesselCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VesselCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VesselPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Vessel.
   * @param {VesselDeleteArgs} args - Arguments to delete one Vessel.
   * @example
   * // Delete one Vessel
   * const Vessel = await prisma.vessel.delete({
   *   where: {
   *     // ... filter to delete one Vessel
   *   }
   * })
   * 
   */
  delete<T extends VesselDeleteArgs>(args: Prisma.SelectSubset<T, VesselDeleteArgs<ExtArgs>>): Prisma.Prisma__VesselClient<runtime.Types.Result.GetResult<Prisma.$VesselPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Vessel.
   * @param {VesselUpdateArgs} args - Arguments to update one Vessel.
   * @example
   * // Update one Vessel
   * const vessel = await prisma.vessel.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VesselUpdateArgs>(args: Prisma.SelectSubset<T, VesselUpdateArgs<ExtArgs>>): Prisma.Prisma__VesselClient<runtime.Types.Result.GetResult<Prisma.$VesselPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Vessels.
   * @param {VesselDeleteManyArgs} args - Arguments to filter Vessels to delete.
   * @example
   * // Delete a few Vessels
   * const { count } = await prisma.vessel.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VesselDeleteManyArgs>(args?: Prisma.SelectSubset<T, VesselDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Vessels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VesselUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Vessels
   * const vessel = await prisma.vessel.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VesselUpdateManyArgs>(args: Prisma.SelectSubset<T, VesselUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Vessels and returns the data updated in the database.
   * @param {VesselUpdateManyAndReturnArgs} args - Arguments to update many Vessels.
   * @example
   * // Update many Vessels
   * const vessel = await prisma.vessel.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Vessels and only return the `id`
   * const vesselWithIdOnly = await prisma.vessel.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VesselUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VesselUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VesselPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Vessel.
   * @param {VesselUpsertArgs} args - Arguments to update or create a Vessel.
   * @example
   * // Update or create a Vessel
   * const vessel = await prisma.vessel.upsert({
   *   create: {
   *     // ... data to create a Vessel
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Vessel we want to update
   *   }
   * })
   */
  upsert<T extends VesselUpsertArgs>(args: Prisma.SelectSubset<T, VesselUpsertArgs<ExtArgs>>): Prisma.Prisma__VesselClient<runtime.Types.Result.GetResult<Prisma.$VesselPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Vessels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VesselCountArgs} args - Arguments to filter Vessels to count.
   * @example
   * // Count the number of Vessels
   * const count = await prisma.vessel.count({
   *   where: {
   *     // ... the filter for the Vessels we want to count
   *   }
   * })
  **/
  count<T extends VesselCountArgs>(
    args?: Prisma.Subset<T, VesselCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VesselCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Vessel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VesselAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VesselAggregateArgs>(args: Prisma.Subset<T, VesselAggregateArgs>): Prisma.PrismaPromise<GetVesselAggregateType<T>>

  /**
   * Group by Vessel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VesselGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VesselGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VesselGroupByArgs['orderBy'] }
      : { orderBy?: VesselGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VesselGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVesselGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Vessel model
 */
readonly fields: VesselFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Vessel.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VesselClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  operator<T extends Prisma.OperatorDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OperatorDefaultArgs<ExtArgs>>): Prisma.Prisma__OperatorClient<runtime.Types.Result.GetResult<Prisma.$OperatorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  trips<T extends Prisma.Vessel$tripsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Vessel$tripsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Vessel model
 */
export interface VesselFieldRefs {
  readonly id: Prisma.FieldRef<"Vessel", 'String'>
  readonly operatorId: Prisma.FieldRef<"Vessel", 'String'>
  readonly name: Prisma.FieldRef<"Vessel", 'String'>
  readonly registrationNo: Prisma.FieldRef<"Vessel", 'String'>
  readonly capacity: Prisma.FieldRef<"Vessel", 'Int'>
  readonly description: Prisma.FieldRef<"Vessel", 'String'>
  readonly vesselMetadata: Prisma.FieldRef<"Vessel", 'Json'>
  readonly createdAt: Prisma.FieldRef<"Vessel", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Vessel", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"Vessel", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Vessel findUnique
 */
export type VesselFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vessel
   */
  select?: Prisma.VesselSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vessel
   */
  omit?: Prisma.VesselOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VesselInclude<ExtArgs> | null
  /**
   * Filter, which Vessel to fetch.
   */
  where: Prisma.VesselWhereUniqueInput
}

/**
 * Vessel findUniqueOrThrow
 */
export type VesselFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vessel
   */
  select?: Prisma.VesselSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vessel
   */
  omit?: Prisma.VesselOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VesselInclude<ExtArgs> | null
  /**
   * Filter, which Vessel to fetch.
   */
  where: Prisma.VesselWhereUniqueInput
}

/**
 * Vessel findFirst
 */
export type VesselFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vessel
   */
  select?: Prisma.VesselSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vessel
   */
  omit?: Prisma.VesselOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VesselInclude<ExtArgs> | null
  /**
   * Filter, which Vessel to fetch.
   */
  where?: Prisma.VesselWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Vessels to fetch.
   */
  orderBy?: Prisma.VesselOrderByWithRelationInput | Prisma.VesselOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Vessels.
   */
  cursor?: Prisma.VesselWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Vessels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Vessels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Vessels.
   */
  distinct?: Prisma.VesselScalarFieldEnum | Prisma.VesselScalarFieldEnum[]
}

/**
 * Vessel findFirstOrThrow
 */
export type VesselFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vessel
   */
  select?: Prisma.VesselSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vessel
   */
  omit?: Prisma.VesselOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VesselInclude<ExtArgs> | null
  /**
   * Filter, which Vessel to fetch.
   */
  where?: Prisma.VesselWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Vessels to fetch.
   */
  orderBy?: Prisma.VesselOrderByWithRelationInput | Prisma.VesselOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Vessels.
   */
  cursor?: Prisma.VesselWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Vessels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Vessels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Vessels.
   */
  distinct?: Prisma.VesselScalarFieldEnum | Prisma.VesselScalarFieldEnum[]
}

/**
 * Vessel findMany
 */
export type VesselFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vessel
   */
  select?: Prisma.VesselSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vessel
   */
  omit?: Prisma.VesselOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VesselInclude<ExtArgs> | null
  /**
   * Filter, which Vessels to fetch.
   */
  where?: Prisma.VesselWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Vessels to fetch.
   */
  orderBy?: Prisma.VesselOrderByWithRelationInput | Prisma.VesselOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Vessels.
   */
  cursor?: Prisma.VesselWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Vessels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Vessels.
   */
  skip?: number
  distinct?: Prisma.VesselScalarFieldEnum | Prisma.VesselScalarFieldEnum[]
}

/**
 * Vessel create
 */
export type VesselCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vessel
   */
  select?: Prisma.VesselSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vessel
   */
  omit?: Prisma.VesselOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VesselInclude<ExtArgs> | null
  /**
   * The data needed to create a Vessel.
   */
  data: Prisma.XOR<Prisma.VesselCreateInput, Prisma.VesselUncheckedCreateInput>
}

/**
 * Vessel createMany
 */
export type VesselCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Vessels.
   */
  data: Prisma.VesselCreateManyInput | Prisma.VesselCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Vessel createManyAndReturn
 */
export type VesselCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vessel
   */
  select?: Prisma.VesselSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Vessel
   */
  omit?: Prisma.VesselOmit<ExtArgs> | null
  /**
   * The data used to create many Vessels.
   */
  data: Prisma.VesselCreateManyInput | Prisma.VesselCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VesselIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Vessel update
 */
export type VesselUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vessel
   */
  select?: Prisma.VesselSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vessel
   */
  omit?: Prisma.VesselOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VesselInclude<ExtArgs> | null
  /**
   * The data needed to update a Vessel.
   */
  data: Prisma.XOR<Prisma.VesselUpdateInput, Prisma.VesselUncheckedUpdateInput>
  /**
   * Choose, which Vessel to update.
   */
  where: Prisma.VesselWhereUniqueInput
}

/**
 * Vessel updateMany
 */
export type VesselUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Vessels.
   */
  data: Prisma.XOR<Prisma.VesselUpdateManyMutationInput, Prisma.VesselUncheckedUpdateManyInput>
  /**
   * Filter which Vessels to update
   */
  where?: Prisma.VesselWhereInput
  /**
   * Limit how many Vessels to update.
   */
  limit?: number
}

/**
 * Vessel updateManyAndReturn
 */
export type VesselUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vessel
   */
  select?: Prisma.VesselSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Vessel
   */
  omit?: Prisma.VesselOmit<ExtArgs> | null
  /**
   * The data used to update Vessels.
   */
  data: Prisma.XOR<Prisma.VesselUpdateManyMutationInput, Prisma.VesselUncheckedUpdateManyInput>
  /**
   * Filter which Vessels to update
   */
  where?: Prisma.VesselWhereInput
  /**
   * Limit how many Vessels to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VesselIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Vessel upsert
 */
export type VesselUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vessel
   */
  select?: Prisma.VesselSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vessel
   */
  omit?: Prisma.VesselOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VesselInclude<ExtArgs> | null
  /**
   * The filter to search for the Vessel to update in case it exists.
   */
  where: Prisma.VesselWhereUniqueInput
  /**
   * In case the Vessel found by the `where` argument doesn't exist, create a new Vessel with this data.
   */
  create: Prisma.XOR<Prisma.VesselCreateInput, Prisma.VesselUncheckedCreateInput>
  /**
   * In case the Vessel was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VesselUpdateInput, Prisma.VesselUncheckedUpdateInput>
}

/**
 * Vessel delete
 */
export type VesselDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vessel
   */
  select?: Prisma.VesselSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vessel
   */
  omit?: Prisma.VesselOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VesselInclude<ExtArgs> | null
  /**
   * Filter which Vessel to delete.
   */
  where: Prisma.VesselWhereUniqueInput
}

/**
 * Vessel deleteMany
 */
export type VesselDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Vessels to delete
   */
  where?: Prisma.VesselWhereInput
  /**
   * Limit how many Vessels to delete.
   */
  limit?: number
}

/**
 * Vessel.trips
 */
export type Vessel$tripsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
  where?: Prisma.TripWhereInput
  orderBy?: Prisma.TripOrderByWithRelationInput | Prisma.TripOrderByWithRelationInput[]
  cursor?: Prisma.TripWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TripScalarFieldEnum | Prisma.TripScalarFieldEnum[]
}

/**
 * Vessel without action
 */
export type VesselDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vessel
   */
  select?: Prisma.VesselSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vessel
   */
  omit?: Prisma.VesselOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VesselInclude<ExtArgs> | null
}
