
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Operator
 * 
 */
export type Operator = Prisma.OperatorModel
/**
 * Model Vessel
 * 
 */
export type Vessel = Prisma.VesselModel
/**
 * Model Trip
 * 
 */
export type Trip = Prisma.TripModel
/**
 * Model TripSchedule
 * 
 */
export type TripSchedule = Prisma.TripScheduleModel
/**
 * Model PriceTier
 * 
 */
export type PriceTier = Prisma.PriceTierModel
/**
 * Model TripSeat
 * 
 */
export type TripSeat = Prisma.TripSeatModel
/**
 * Model Booking
 * 
 */
export type Booking = Prisma.BookingModel
/**
 * Model BookingItem
 * 
 */
export type BookingItem = Prisma.BookingItemModel
/**
 * Model Payment
 * 
 */
export type Payment = Prisma.PaymentModel
/**
 * Model WebhookEvent
 * 
 */
export type WebhookEvent = Prisma.WebhookEventModel
/**
 * Model Manifest
 * 
 */
export type Manifest = Prisma.ManifestModel
/**
 * Model Passenger
 * 
 */
export type Passenger = Prisma.PassengerModel
/**
 * Model Checkin
 * 
 */
export type Checkin = Prisma.CheckinModel
/**
 * Model SeatLock
 * 
 */
export type SeatLock = Prisma.SeatLockModel
/**
 * Model AuditLog
 * 
 */
export type AuditLog = Prisma.AuditLogModel
/**
 * Model EmailLog
 * 
 */
export type EmailLog = Prisma.EmailLogModel
/**
 * Model Review
 * 
 */
export type Review = Prisma.ReviewModel
/**
 * Model PromoCode
 * 
 */
export type PromoCode = Prisma.PromoCodeModel
