
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const TripScheduleStatus = {
  scheduled: 'scheduled',
  in_progress: 'in_progress',
  completed: 'completed',
  cancelled: 'cancelled'
} as const

export type TripScheduleStatus = (typeof TripScheduleStatus)[keyof typeof TripScheduleStatus]


export const BookingStatus = {
  pending: 'pending',
  held: 'held',
  paid: 'paid',
  confirmed: 'confirmed',
  cancelled: 'cancelled',
  refunded: 'refunded',
  expired: 'expired'
} as const

export type BookingStatus = (typeof BookingStatus)[keyof typeof BookingStatus]


export const PaymentStatus = {
  pending: 'pending',
  succeeded: 'succeeded',
  failed: 'failed',
  refunded: 'refunded',
  refund_pending: 'refund_pending'
} as const

export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus]


export const CheckinStatus = {
  not_checked_in: 'not_checked_in',
  checked_in: 'checked_in',
  no_show: 'no_show'
} as const

export type CheckinStatus = (typeof CheckinStatus)[keyof typeof CheckinStatus]


export const UserRole = {
  customer: 'customer',
  operator: 'operator',
  staff: 'staff',
  admin: 'admin'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const EmailType = {
  booking_confirmation: 'booking_confirmation',
  payment_receipt: 'payment_receipt',
  booking_reminder: 'booking_reminder',
  cancellation_notice: 'cancellation_notice',
  password_reset: 'password_reset',
  welcome: 'welcome'
} as const

export type EmailType = (typeof EmailType)[keyof typeof EmailType]


export const NotificationChannel = {
  email: 'email',
  sms: 'sms',
  push: 'push'
} as const

export type NotificationChannel = (typeof NotificationChannel)[keyof typeof NotificationChannel]
