"use strict";
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/
Object.defineProperty(exports, "__esModule", { value: true });
exports.NotificationChannel = exports.EmailType = exports.UserRole = exports.CheckinStatus = exports.PaymentStatus = exports.BookingStatus = exports.TripScheduleStatus = void 0;
exports.TripScheduleStatus = {
    scheduled: 'scheduled',
    in_progress: 'in_progress',
    completed: 'completed',
    cancelled: 'cancelled'
};
exports.BookingStatus = {
    pending: 'pending',
    held: 'held',
    paid: 'paid',
    confirmed: 'confirmed',
    cancelled: 'cancelled',
    refunded: 'refunded',
    expired: 'expired'
};
exports.PaymentStatus = {
    pending: 'pending',
    succeeded: 'succeeded',
    failed: 'failed',
    refunded: 'refunded',
    refund_pending: 'refund_pending'
};
exports.CheckinStatus = {
    not_checked_in: 'not_checked_in',
    checked_in: 'checked_in',
    no_show: 'no_show'
};
exports.UserRole = {
    customer: 'customer',
    operator: 'operator',
    staff: 'staff',
    admin: 'admin'
};
exports.EmailType = {
    booking_confirmation: 'booking_confirmation',
    payment_receipt: 'payment_receipt',
    booking_reminder: 'booking_reminder',
    cancellation_notice: 'cancellation_notice',
    password_reset: 'password_reset',
    welcome: 'welcome'
};
exports.NotificationChannel = {
    email: 'email',
    sms: 'sms',
    push: 'push'
};
